src/index.html, src/phoenix/init_vfs.js, src/phoenix/shell.js
Phoenix shell will init as the first js module to init.
=> Creating base phoenix shell with virtual filesystem init.

src/JSUtils/HintUtils.js, src/JSUtils/Session.js
https://github.com/aicore/phoenix/issues/11
* Changed acorn to be loaded from the third-party modules folder as Acorn is already available there.
* All unit tests passing as expected with no new failures noted.
=> Move acorn dep from node_modules to thirdparty lib folder. 

src/brackets.js, src/filesystem/impls/appshell/AppshellFileSystem.js, src/project/ProjectManager.js
* Loading default project from VFS at startup 
* Disabling unsupported file watcher for now. tracked in https://github.com/aicore/phoenix/issues/47
* Remove brackets remote debugging as its not required in the browser.
https://github.com/aicore/phoenix/issues/22
=> Loading default project at startup 

src/extensions/default/DefaultExtensions.json, src/utils/ExtensionLoader.js, src/utils/ExtensionUtils.js
- Sanitise extension loading paths.
- Default extensions load working. https://github.com/aicore/phoenix/issues/26
- Code folding extension enabled and working.
* Default extensions disabling workflow is broken
=> Default extensions loading fix

src/index.html
* We will only be sending page view count to analytics.
=> Prevent sending page title to google analytics for privacy.

test/SpecRunner.html, test/SpecRunner.js
Base unit tests working.
launch test/SpecRunner.js from a static server to launch tests.
=> Base unit tests working.

src/extensions/default/DarkTheme/main.less, src/styles/brackets_codemirror_override.less
* In google chrome, when we scroll any multi-page code file with the mouse scroll wheel, the scroll is very slow. This change fixes the issue.
* Problem not noted in Firefox.
* Tested working in chrome and firefox with the dark and light theme.
* On the first launch no themes are loaded, This is a brackets theme loading issue and not related tho this change. Reload phoenix to load themes.
=> Fix chrome slow scroll with scroll wheel bug

src/phoenix/fslib.js, src/phoenix/fslib_mounts.js, src/phoenix/fslib_native.js, test/SpecRunner.html
As fs access APIs do not support copy/rename functions, we have to implement these functions manually. This PR implements file copy within mount points.
This copy impl follows the semantics of Linux cp command: https://www.geeksforgeeks.org/cp-command-linux-examples/
* copy is currently not supported between filer and mount points.
* not supported within filer, we can use filer.rename when needed for rename, copy is to be implemented.
https://github.com/aicore/phoenix/issues/3
=> Copy file API for fs native

src/phoenix/fslib.js, src/phoenix/fslib_watch.js
File/dir create/change watchers. 
sync of file content across different phoenix tab instances working. 
https://github.com/aicore/phoenix/issues/3
=> File/dir create/change watchers. 

LICENSE, README.md
Phoenix is based on Adobe Brackets released under the MIT license. Phoenix was started when Adobe decided to pull the plug on brackets in a complicated dance that is a topic of another blog post some other day. Being part of the brackets core team from the initial days of brackets, we stuck to the MIT license to continue the true spirit of the original devs of brackets. Phoenix was designed to work only in web browsers, it will not have a native desktop counterpart. 
We later joined our efforts to help rebuild the brackets community under the brackets continued community. Phoenix being an active contributor to the brackets Org will help to continue the legacy of the original devs of brackets under the MIT license. Phoenix features relevant to brackets will also be added to brackets under …
=> Pheonix transitions to AGPL Licence

src/document/DocumentCommandHandlers.js, src/view/MainViewManager.js
- Removing unused browser cache on reload workflow. This will be done by native dev tools.
- Saving state of current UI before exit. 
Fixes: https://github.com/aicore/phoenix/issues/172
=> Saving state of current UI before exit.

src/phoenix/constants.js, src/phoenix/errno.js, src/phoenix/fslib.js, src/phoenix/fslib_mounts.js, src/phoenix/fslib_native.js, src/phoenix/fslib_watch.js, src/phoenix/init_vfs.js, src/phoenix/mount_point_storage.js, src/phoenix/nohost_server.js, src/phoenix/shell.js, src/phoenix/utils.js
All files in the phoenix folder are added with the following GNU AGPL license header
#186 
```
GNU AGPL-3.0 License
Modified work Copyright (c) 2021 - present Core.ai
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see …
```
=> Add GNU AGPL license header for files in phoenix folder

README.md, gulpfile.js/index.js, test/SpecRunner.html, test/SpecRunner.js
- Extract unit test files to phoenix fs on start. 
- Adding reset and reload tests option 
- docs: docs update for running tests 
* 230 unit tests failing after fix reduced from 350. https://github.com/aicore/phoenix/issues/91
=> Testing framework enable

src/index.html
*  limit page details from being logged in google analytics 
* Earlier page title used to be sent with page_vide event when ga inits. Page title contained project file path that needs to be not logged. Overriding those titles to contacts to prevent logging user private information.
=> fix: limit page details from being logged in page view to improve privacy

src/extensions/default/HealthData/HealthDataManager.js, src/index.html
* Problem was all deployments default to dev ga id hardcoded in index.html file.
* Changes impl to load ga scripts at runtime after load.
* Tested ga dev endpoints hitting as expected.
=> fix: defer loading of gtag manager till brackets config with Google Analytics id is loaded

src/extensions/default/Phoenix-markdown-toolbar/dialogs.js, src/extensions/default/Phoenix-markdown-toolbar/handler.js, src/extensions/default/Phoenix-markdown-toolbar/lines.js, src/extensions/default/Phoenix-markdown-toolbar/main.js, src/extensions/default/Phoenix-markdown-toolbar/nls/strings.js, src/extensions/default/Phoenix-markdown-toolbar/paragraphs.js, src/extensions/default/Phoenix-markdown-toolbar/selections.js, src/extensions/default/Phoenix-markdown-toolbar/strings.js, src/extensions/default/Phoenix-markdownPreview/main.js
Markdown feature extensions have added
1. markdown preview support
2. markdown toolbar support
3. AGPL license headers update in docs
4. toolbar-code editor ux fixes
modified from pull request #256 with reference to issue #140
=> Markdown features added (preview and toolbar)

src/main.js
Brackets change: https://github.com/brackets-cont/brackets/pull/85
* Removed in assuming that no extensions were using it https://github.com/adobe/brackets/pull/11589
* Caused extension break https://github.com/jadbox/brackets-integrated-development
* and general extension issues later https://github.com/adobe/brackets/issues/11960
We just create an alias here as the Panel manager. Workspace manager is a superset of panel manager APIs
* Brackets IDE extension now works with python
* Extension load that used old panel APIs working
=> Adding require alias for view/panelManager older extension compatibility

src/extensions/default/JavaScriptQuickEdit/unittests.js, src/extensions/default/RemoteFileAdapter/main.js, src/filesystem/FileSystem.js, src/filesystem/RemoteFile.js
* Move remote file adapter to core Reading HTTP/HTTPS remote content as a file is a core requirement. 
* Fixes MDN Docs(except 1) and remote file extension Tests
* Added support for file reads on any browser supported encoding from HTTP/HTTPS links
- fix: remove unused import
* All but 1 MDN Docs extension tests working
* All remote file extension tests working.
* Varified `ctrl_shift+o` to open an http/s URL works.
* 1 more unit test passing from general tests.
=> Move remote file adapter to core from extension

src/extensions/default/RemoteFileAdapter/main.js
- feat: github remote file link open using quick open
- feat: gitlab remote file link open using quick open
- GitLab URLs currently do not support CORS. So this will only work for brackets for now. We can enable cors if we have a backend.
=> Github and Gitlab file URL opening support

src/extensions/default/DebugCommands/main.js, src/nls/root/strings.js
Added Debug Menu items
* Open Virtual File System: opens `/` folder as current project
* Open virtual server: Opens vfs url to prowse in new tab
=> Debug commands to browse virtual fs and server

src/command/DefaultMenus.js, src/htmlContent/main-view.html, src/project/SidebarView.js, src/styles/brackets.less
Earlier we had two separate icons like shown in this image 
Now we merged the gear icon(doing workspace file sort) and workspace split-view icon into a single unified workspace icon.
- feat: changed working set split-view icon
- feat: add working set sort options to a unified working set menu
- feat: unified working set menu and removed old gear menu
Unit and workspace integration tests pass with no changes.
=> unified working set menu

src/extensions/default/NavigationAndHistory/NavigationProvider.js, src/styles/brackets.less, src/styles/images/sprites.svg
- feat: forward and backward nav button tooltips
- feat: show in file tree navigation button
=> show in file tree navigation button

.commitlintrc.json, .husky/commit-msg, package-lock.json, package.json
https://github.com/conventional-changelog/commitlint
* This is because we moved org wide to new commit linter standard here: https://github.com/aicore/template-nodejs/pull/10
* Older lib didn't support ES6 modules
=> feat: change commit linter with stantard for core.ai 

src/extensions/default/Phoenix/main.js, src/extensions/default/Phoenix/survey-template.html
* Survey is disabled for now, uncomment the line in the pull request to enable.
* The survey is shown after 30 seconds of use exactly once for a specific survey URL.
* to redisplay the server, either provide a new survey URL, or increment the survey version
=> surveyplanet survey dialog after 30 seconds of use once per survey

src/htmlContent/main-view.html, src/styles/brackets_patterns_override.less, src/view/WorkspaceManager.js, test/spec/EditorRedraw-test.js
* layout the editor on resize as content panel ui had layout problems on resizing the plugin panel.
* Fix editor relayout unit tests, 1741 pass/63 fail as before.
=> fix: relayout ui on plugin panel resize and unit test fixes

src/utils/Resizer.js, src/view/WorkspaceManager.js
* plugin panels are closed by clicking the corresponding plugin icon in the toolbar. removing double click to close workflow.
Double click to close was causing problems with layout and the fix was taking a long time. defer to later if the feature is requested as it is a non-p1 feature.
=> fix: remove collapse feature for plugin panels

src/extensions/default/Phoenix-Markdown/main.js, src/utils/Resizer.js, src/view/PluginPanelView.js, src/view/WorkspaceManager.js
* The plugin panel was showing up with 0 width (not showing up in UI) on the first launch. Fixed to honor minWidth specified on the first launch.
=> fix: plugin panel layout fixes

src/view/PluginPanelView.js, src/view/WorkspaceManager.js
* Only one plugin panel should be active at a time.
* opening a new plugin panel by clicking on a toolbar icon should hide the old plugin panel that is currently being displayed and then show the new panel.
=> fix: pluginPanel show/hide visibility issues

src/phoenix/fslib_native.js
In newly created files, the encoder was returning empty string `""` and javascript treats an empty string as falsey and the check was causing false positives.
This only happens in the native file system, ie folders mounted from the actual user's system into phoenix. This peobelm doesn't happen in browser filer fs.
If decoding fails, `null` string is returned. So we specifically check for null string to verify decode failure.
=> fix: cannot read newly created file in native file system

src/utils/ExtensionInterface.js, test/UnitTestSuite.js, test/spec/ExtensionInterface-test.js
There should be a way for extensions to effectively communicate with each other. Currently, the command manager can be used to register custom extension commands. But it is quite limiting for use cases involving direct function calls/event triggering. 
With this change, a new ExtensionInterface is defined that can be used by extensions to register named interfaces. Extensions in brackets are loaded unpredictably/when deemed required by brackets and getting an interface can only work after the extension is loaded. Methods are provided that allow getting hold of these interfaces as and when they are registered as part of the extension life cycle.
=> feat: extension interface for inter extension communication

src/extensions/default/Phoenix-live-preview/main.js
- fix: removed unused variables
- feat: live preview panel shows up on app start
=> feat: live preview panel shows up on app start

src/utils/ExtensionInterface.js, src/utils/FeatureGate.js, test/UnitTestSuite.js, test/spec/ExtensionInterface-test.js, test/spec/FeatureGate-test.js
* During development, users can enable or disable features setting `feature.<featureName>`  to `enabled` or `disabled` 
* Extensions should use the FeatureGate API to expose named feature gates.
* Minor change in API name fore ExtensionInterface
=> feat: feature gate to selectively enable features in development

README.md, src/brackets.js, src/command/KeyBindingManager.js, src/extensions/default/DebugCommands/main.js, src/filesystem/FileIndex.js, src/filesystem/FileSystem.js, src/preferences/PreferencesBase.js, src/preferences/PreferencesImpl.js, src/project/ProjectManager.js
* If the startup project could not be read, we will launch the default project. A startup
project load can fail if it is a native mounted folder which doesnt have permissions.
* Fixes to always index /app/state.json preferences file. Earlier, the index was getting reset
on project switch and save of preferences was failing as the rpeferences saver saw two files,
one with an index entry and one without.
=> fix: boot project load recovery on failure

src/extensions/default/DefaultExtensions.json, src/extensions/default/Phoenix-live-preview/main.js, src/extensions/default/Phoenix-live-preview/utils.js
- feat: remember last previewed file when switching between project files
- chore: temporarily remove prettier WIP extension from loading
=> feat: remember last previewed file when switching between project files

src/index.html
If we see that the url ends with a/b/index.html, we will redirect to a/b/
=> chore: always load from url like x/ instead of x/index.html

src/command/DefaultMenus.js, src/document/DocumentCommandHandlers.js
* remove show in os from context menu.
* fs access apis does not support opening file in explorer and may not be likely to in the near future. We need to do this maybe as part of phoenix local daemons or somthing.
=> chore: remove show in os file, no browser support

src/assets/phoenix-splash/index.html, src/extensions/default/Phoenix-live-preview/main.js, src/extensions/default/Phoenix-live-preview/utils.js, src/extensions/default/Phoenix/serverSync.js, src/extensions/default/RemoteFileAdapter/main.js, test/spec/Menu-test.js
* Force reload live preview on project switch if live preview panel is shown.
* live preview was loading phoenix URL itself if there was nothing to preview in a project and we tried to click on live preview toolbar icon.
=> chore: dedupe files to sync before publish and live preview usability improvements

src/extensions/default/Phoenix-live-preview/main.js, src/utils/Resizer.js, src/view/PluginPanelView.js, src/view/WorkspaceManager.js
This happened as the live preview panel was resizing to min size when there was no values to choose from(Eg. saved panel size from last boot).
Added an initial size hint to the panel constructor to fall back to instead of min size in case of first time panel creation.
=> fix: on fresh install live preview panel had width of 50px

src/utils/Resizer.js
We were not saving the panel size on collapse of live preview. now we save it .
=> fix: live preview collapse to min size when clicking toolbar icon twice

src/extensions/default/DefaultExtensions.json
We will most likely moving markdown into live preview. so removing the current markdown extension as it is not confirming to phoenix UX.
=> chore: removing phoenix markdown extension till we have better ux

src/base-config/keyboard.json, src/command/DefaultMenus.js, src/command/KeyBindingManager.js
* Since https://github.com/phcode-dev/phoenix/pull/406, modifying shortcut framework to identify arrow keys
* Browser doesn't allow to overwrite tab management shortcuts like `ctrl-w`. Changed it to `alt-w` instead.
* Remove menu items that is not available in phoenix
=> fix: keyboard shortcuts and removed unavailable menu items

src/brackets.js
=> fix: safari overlay visible over image previews

src/search/FindInFiles.js
* Disable file system caching at boot as it scans all files in large project. This causes chrome to be stuck and crash. This is a chrome bug as the browser should not crash on reading large number of files.
* Search will still work without the caching.
* Search on a large project will still crash due to large file read operation.
=> fix: large project open crashes

package-lock.json, package.json, src/filesystem/impls/appshell/AppshellFileSystem.js
When reading dirs with fs.readdir in phoenix, we were subsequently queuing fs.stat for every sub entry. This causes large fs read queues.
To mitigate this, fs.readdir can be specified with an optional `withFileTypes` parameter that will return the file stat along with the readdir API reducing fs calls significantly. filer already supports this option. We added the option to phoenix fs native API with this commit: https://github.com/phcode-dev/phoenix-fs/commit/1c808c4dbf5bd6af0c3f076281be689a0c393e13
Updating phoenix to use latest phoenix fs api with  `withFileTypes` support and related handler changes.
Folder open in file tree times improved significantly from more than 25 seconds with 1000 files in a dir to under 1 second.
=> chore: performance improvement with large folders in file tree

src/extensions/default/Phoenix-live-preview/main.js
* Images like png files is not associated with an editor and hence `activeEditorChange` event will not be dispatched for images like png.
* We now listen to `currentFileChange` event instead
=> fix: live preview not updating when switching png files

src/extensions/default/Phoenix-live-preview/main.js
We have attached certain event handlers to the _loadPreview method (Eg. `MainViewManager.on("currentFileChange", _loadPreview);` ) . The event handler will trigger _loadPreview with event args, which was being treated as `force = true` as we did not explicitly check for true. This resulted in inconsistent live preview renders even when live preview was pinned.
=> fix: pin live preview not working

src/extensions/default/HealthData/HealthDataManager.js, src/extensions/default/HealthData/SendToAnalytics.js, src/extensions/default/HealthData/main.js, src/search/FindInFiles.js, src/utils/HealthLogger.js
* remove project stats health as these were generated with node file indexer which is not available in phoenix. To be considered later. https://github.com/phcode-dev/phoenix/issues/444
* Wire  in preference `healthDataTracking` to enable/disable analytics
=> chore: remove project related health data as it uses node

docs/utils/Metrics.md, gulpfile.js/index.js, gulpfile.js/jsDocGenerate.js, package-lock.json, package.json, src/utils/Metrics.js
Put the below comment in any js file to include it in API DOCS:
```js
// @INCLUDE_IN_API_DOCS
```
Gulp scripts will process those files and generate markdown. 
JSDoc and Markdown syntax compatible (work in progress for full syntax support as required).
Based on https://www.npmjs.com/package/parse-comments library that generates abstract syntax tree for comments.
- feat: automatic API doc generation gulp script
- feat: jsdoc auto generation scripts initial draft
related to: https://github.com/phcode-dev/phoenix/issues/450
=> Auto generate API docs in markdown format

src/command/Commands.js, src/extensions/default/Phoenix/new-project.js, src/extensions/default/RecentProjects/htmlContent/projects-menu.html, src/extensions/default/RecentProjects/main.js, src/extensions/default/RecentProjects/styles/styles.less, src/nls/root/strings.js, src/utils/Metrics.js
- `Alt+shift+N` will open new project dialogue.
- added menu entries: see images below:
- chore: update google analytics tag name order
- feat: new project file menu entries and shortcuts
=> new project file menu entries and shortcuts

docs/generatedApiDocs/widgets/NotificationUI-API.md, src/extensions/default/NavigationAndHistory/NavigationProvider.js, src/extensions/default/Phoenix/new-project.js, src/htmlContent/main-view.html, src/styles/brackets.less
The NavBar now takes a dedicated toolbar in top of the sidebar. This is required as we add more features in the navbar,
in translated languages where the string for `working files` is long or in long project names, the nav bar icons get hidden.
=> fix: nav bar alignment issues with long project names

.gitignore, gulpfile.js/index.js, package-lock.json, package.json, src/extensions/default/Phoenix-live-preview/main.js, src/extensions/default/Phoenix-live-preview/markdown.html, src/thirdparty/licences/bootstrap.markdown, src/thirdparty/licences/credits.md, src/thirdparty/licences/highlight.js.markdown
* integrate markdown live preview libs in src directly as the load of the lib from cdn was taking time and inconsistently.
* add github code styles for code in markdown
=> fix: integrate third party markdown render libs instead of cdn load

src/filesystem/FileSystemEntry.js, src/project/ProjectModel.js, test/spec/LowLevelFileIO-test.js
- fix: crash when searching large projects
- fix: dont cache node_modeuls
- fix low level file io tests regression as we changed copy behavior to comply with unix copy semantics. The copy api was only used by the tests module as i remember, so fixed the tests.
=> fix: crash when searching large projects

src/command/Commands.js, src/command/DefaultMenus.js, src/extensions/default/icons/main.js, src/nls/root/strings.js, src/project/ProjectManager.js
* In Mac, by default we were using system sort order and not segregating files and folders. All code editors in mac- vscode, webstorm. we will follow the same for consistency and provide an option an option. 
* adds folder icons
=> feat: sort dirs first option and folder icons

src/extensions/default/icons/main.js, src/language/languages.json, src/styles/brackets_codemirror_override.less
* Support syntax highlighting for typescript, objective-c, kotlin, swift
* Added icons support for newly defined languages
* Made GitHub markdown the default markdown format instead of commonmark.
The selection dimensions was improper. See image below
=> fix: selection layout bug and add more lanuguage types

.github/workflows/dev-deploy.yml, README.md, src/extensions/default/DebugCommands/main.js
The tests assumes that the path is `baseurl/src` and `test` . So a large number of tests are failing at this time. 
We do not have the necessary resources to do a refactor of large number of tests assets to its own folder at this time, so putting it to the required folders for now.
=> fix: test suits not working in deployed stages

src/extensions/default/CSSAtRuleCodeHints/unittests.js, src/extensions/default/CSSCodeHints/unittests.js, src/extensions/default/CSSPseudoSelectorHints/unittests.js, src/extensions/default/CloseOthers/unittests.js, src/extensions/default/CodeFolding/unittests.js, src/extensions/default/HTMLCodeHints/unittests.js, src/extensions/default/HealthData/unittests.js, src/extensions/default/HtmlEntityCodeHints/unittests.js, src/extensions/default/InlineColorEditor/unittests.js, src/extensions/default/InlineTimingFunctionEditor/unittests.js, test/BootstrapReporterView.js, test/SpecRunner.html, test/SpecRunner.js, test/spec/ViewUtils-test.js
- feat: test framework for extensions and enable closeOthers test
- test: enable extension test code-folding
- test: enable extension test CSSAtRuleCodeHints
- test: enable extension test CSSCodeHints
- test: enable extension test CSSPseudoSelectorHints
- test: enable extension test HealthData
- test: enable HTMLCodeHints and remove flakey tests
- test: enable HtmlEntityCodeHints
- test: enable InlineColorEditor
- test: enable InlineTimingFunctionEditor
=> extensions testing framework and enabling extension tests batch 1

src/view/PanelView.js, src/view/PluginPanelView.js, src/view/WorkspaceManager.js, test/spec/MainViewManager-integ-test.js
- feat: shift escape will now close all panels one by one in LRU order
- feat: add panel and plugin panel CanBeShownHandler
- integration tests
=> ecape closes panels and shift escape brings them back

src/search/FindInFilesUI.js
When searching, we might want to copy text from the preview editor by double clicking and then triggering search. We will now auto fill the search term if there is a selection in preview editor and the preview editor is in focus.
=> feat: find in files search term copy from preview editor

docs/generatedApiDocs/utils/EventDispatcher-API.md, docs/generatedApiDocs/worker/WorkerComm-API.md, src/command/KeyBindingManager.js, src/command/Menus.js, src/extensions/default/JavaScriptRefactoring/RefactoringUtils.js, src/extensions/default/JavaScriptRefactoring/keyboard.json, src/extensions/default/Phoenix-live-preview/main.js, src/project/ProjectManager.js, src/utils/EventDispatcher.js, src/view/MainViewManager.js
1. shift key presses was raising a no event listener attached message in console.
2. refactor-rename is not tied to shortcut `Shift-F2`
3. refactoring not working if there was invalid syntax
4. fix: leaky event listener messages in console
- Added `setLeakThresholdForEvent` in event dispatcher and docs.
By default, we consider any events having more than 15 listeners to be leaky. But sometimes there may be
genuine use cases where an event can have a large number of listeners. For those events, it is recommended
to increase the leaky warning threshold individually with this API.
Type: [function][2]
*   `eventName` **[string][3]** 
*   `threshold` **[number][4]** The new threshold to set. Will only be set if the new threshold is greater than
the current threshold.
=> Fix: bugs, leaky event listener messages in console

docs/generatedApiDocs/worker/IndexingWorker-API.md, src/base-config/keyboard.json, src/editor/Editor.js, src/extensions/default/JavaScriptRefactoring/keyboard.json, src/view/WorkspaceManager.js, test/spec/MainViewManager-integ-test.js
* Escape key press will first ask the active editor if there is something it can do before we consume it for panel toggle.
* This will fix issues where editor need to dismiss multi cursor or selections on escape
* Editor will now clear all selections on escape key press too apart from multi cursor.
* Change of shourtcut keys.
* Rename file shorcut is now `Shift-F2` instead of earlier `F2` . Eventually we will wire this to `F2` too if the files panel has focus.
* Rename variable/refactor shortcut is now `F2` instead of earlier `Shift-F2`.
* New integration tests
* current tests working as expected.
=> fix: escape key handling and change refactor f2 shortcut

src/JSUtils/worker/tern-main.js
Jump to definition and codehints now works from requirejs contexts
* All unit tests passing as before
* Verified manually that jump to def and codehints is working on bracktes project src, sample node module project, es6 project
https://github.com/phcode-dev/phoenix/issues/601
=> feat: nodejs, requirejs, commonjs code intelligence integration

src/preferences/PreferencesBase.js, test/spec/CodeInspection-integ-test.js
* fix code inspection tests, the tests was failing as we moved to js promise with jquery deffered compatability instead of jquery deferred.
* Fix preferences base that was using deferred.then wrongly instead of deferred.done
=> fix: code-inspection integration tests

src/editor/Editor.js, src/language/CodeInspection.js, src/styles/brackets.less, src/styles/brackets_core_ui_variables.less, test/spec/CodeInspection-integ-test.js, test/spec/Editor-test.js
- feat: editor error, warn,info markers and wire it to lint results
- fix: recompute error markers on file save
- test: editor marking API unit tests
- test: error priority and code inspection integration tests
=> editor error, warn,info markers and wire it to lint results

src/editor/Editor.js, src/editor/EditorHelper/EditorPreferences.js, src/extensions/default/JSHint/main.js, src/language/CodeInspection.js, src/styles/brackets.less, test/spec/Editor-test.js
- fix: either JSHint take config from prefs or defaults but not mixes in both
- feat: editor gutter markers for error/warn/info line
- feat: hover on gutter markers will show all errors on line
- test: editor unit tests
=> editor gutter markers for error/warn/info line

src/base-config/keyboard.json, src/editor/Editor.js, src/extensions/default/QuickView/ImagePreviewProvider.js, src/extensions/default/QuickView/QuickView.less, src/extensions/default/QuickView/colorGradientProvider.js, src/extensions/default/QuickView/main.js, src/language/CodeInspection.js
* Refactor quickview as we are moving the base feature into core for generic hover popup support.
* Change QuickDocs shortcut to `F1` instead of `ctrl-shift-e`.` F1` used to open Phoenix discussion forum which was quite rarely used. So Remapped it to `shift-F1`. Also help and support has its dedicated icon in the plugin panel.
* ADD precise flag to editor getToken APIs.
* CodeInspection gutter will only be shown in supported languages to improve screen real-estate use.
=> refactor: quickview and F1 now bings quickdocs instead of ctrl-shift-e

src/JSUtils/worker/tern-main.js, src/base-config/keyboard.json, src/command/KeyBindingManager.js, src/editor/CodeHintManager.js, src/editor/Editor.js, src/features/JumpToDefManager.js, src/features/ParameterHintsManager.js, test/spec/KeyBindingManager-test.js, test/spec/MainViewManager-integ-test.js
* We will now display function parameter hints when `ctrl-space` is typed.
* Ctrl-click to jump to definition. - UI underline update pending.
* change `edit.splitSelIntoLines` short cut to `Ctrl-Shift-L`
* Change key binding manager to not blindly swallow undo/copy paste related commands
=> feat: improve js code intelligence

src/extensions/default/JSHint/main.js, src/features/QuickViewManager.js, src/language/CodeInspection.js, src/styles/brackets.less
* wired code inspection error messages to quickview
* Fix bug where js hint errors where being offset by 1 char
* removed the pointy thing as aligning it to ui anchor editor chars were proving difficult.
=> feat: code inspection hover error quickview

src/extensions/default/JavaScriptRefactoring/HighLightReferences.js, src/extensions/default/JavaScriptRefactoring/unittests.js
=> fix: selecting text with double click should not show references highlight

src/editor/Editor.js, src/features/ParameterHintsManager.js, src/view/WorkspaceManager.js, test/spec/MainViewManager-integ-test.js
When user press escape key, we have to decide if the action leads to panel toggle behavior or other specific escape behavior.
features can use this API available in workspace manager to override the default panel toggle behavior if they wish to handle escape key of a higher priority.
* integration tests
* manually tested codehint/parameter hint popup flows too.
=> feat: add workspacemanager.addEscapeKeyEventHandler and remove too

.github/workflows/dev-deploy.yml, CNAME
- ci: dev.phcode.dev will be deployed to its own repo
Currently, all the release artifacts are deployed to a branch in the main phcode src repo itself which is consuming unwanted binary space in this repo. The repo size is bloating to over 140 mb. So we are moving built artifacts into its own repo.
=> dev.phcode.dev will be deployed to its own repo

src/view/ThemeManager.js
The theme change triggered by, os preference change is handled slightly differently(as compared to user switching). hence, it does not get reported to the event dispatcher. This commit fixed that.
- current state ( os triggered theme change is not reported to the event Dispatcher)
- with this change ( dark /light mode change is reported to event dispatcher)
=> feat: Report os triggered light/dark mode change to EventDispacher

src/phoenix/virtual-server-loader.js, src/phoenix/virtualServer/mime-db.js, src/phoenix/virtualServer/mime-types.js, src/virtual-server-main.js
- fix: mime-db not loaded at times causing download of live preview html
- feat: cache first always and refresh cache after app start. This drasticaly improves load times to under one second mostly after caching
=> cache first always and refresh cache after app start

src/brackets.js, src/worker/ExtensionsWorker.js, src/worker/IndexingWorker.js
* EventDispatcher module must be loaded before workerComm Module.
* Sometimes, in slow networks this load was done out of order. Now during brackets.js app start, we do the pre- require load in correct order so that modules may load in any order.
=> fix: inconsistant load failures on very slow networks

src/brackets.js, src/main.js, src/virtual-server-main.js
https://github.com/phcode-dev/phoenix/pull/678 didn't fix the issue.
Requirejs seems to load all files in brackets.js in any order it likes and then only execute the define function in the right order. Since we use the define function in a special way in workercomm and event dispatcher, the invoke of code that was out of the define scope in those files was being done at random order based on network timing. So adding the require in brackets.js in https://github.com/phcode-dev/phoenix/pull/678 didn't fix the issue.
Here, we load EventDispatcher as a dependency before brackets.js is loaded, which will ensure the load timing.
1. with throttling in fast and slow 3g networks without and with cacheing several times in chrome.
2. works in Firefox too.
=> fix: intermittent load issues in very slow networks

src/assets/phoenix-splash/index.html, src/main.js
- splits load count and js file name in to two fields
- fix jslint warning
https://user-images.githubusercontent.com/78793827/190875258-c2f7e2b7-56ae-47c5-b220-94eedbc65fa3.mp4
https://user-images.githubusercontent.com/78793827/190875268-7dc0e545-f1c0-4b72-a8cb-428f88530fd7.mp4
=> fix: prevent splash screen text from jumping around

src/LiveDevelopment/BrowserScripts/ServiceWorkerTransportRemote.js, src/LiveDevelopment/MultiBrowserImpl/transports/ServiceWorkerTransport.js, src/extensions/default/Phoenix-live-preview/main.js, src/extensions/default/StaticServer/StaticServer.js, src/phoenix/virtualServer/webserver.js, src/virtual-server-main.js
* improves stability as the service woker may be killed anytime by the browser as needed and we do not need to constantly ping the reliability if the service worker
=> chore: live preview use broadcast channel instead of service worker for inter window messaging

src/LiveDevelopment/LiveDevMultiBrowser.js, src/LiveDevelopment/MultiBrowserImpl/transports/ServiceWorkerTransport.js, src/index.html
Earlier, when we navigated to a non HTML/CSS file (Eg. markdown file), after 5 seconds, live preview session used to close. Since Phoenix live previews are always on, removed the code.
Minor refactor of live preview logging.
=> fix: live preview will not close while navigating to md/svg or other non html live previews

src/extensions/default/Phoenix-live-preview/live-preview.css, src/extensions/default/Phoenix-live-preview/main.js, src/extensions/default/Phoenix-live-preview/panel.html
Live preview titles are now trimmed to 50% of available width after which its ellipsed.
=> fix: live preview panel long title trim

src/LiveDevelopment/LiveDevMultiBrowser.js, src/LiveDevelopment/MultiBrowserImpl/protocol/LiveDevProtocol.js, src/LiveDevelopment/main.js, src/extensions/default/Phoenix-live-preview/main.js, src/extensions/default/Phoenix-live-preview/utils.js
- Open the appropriate document in the editor if a user clicks on the live preview and that doc is not open in the editor.
- feat: live preview auto enable and disable based on UX context
- feat: stop live preview if there is no live preview tab/iframe open
=> live preview auto enable and disable based on UX context

src/LiveDevelopment/LiveDevMultiBrowser.js, src/LiveDevelopment/MultiBrowserImpl/transports/ServiceWorkerTransport.js, src/extensions/default/Phoenix-live-preview/main.js
* Added metrics for the number and size of live preview transport messages sent. Will help to identify the scale of backend needed for advanced live preview services.
* Metrics for live preview tab popout, reload and pin
* Number of concurrent live previews used.
=> chore: live preview metrics

src/extensions/default/Phoenix-live-preview/main.js, src/extensions/default/Phoenix-live-preview/utils.js
Earlier for every save live preview used to get reloaded, causing flickering and bad UX. 
With this change, we force reload live preview on save
* for all non-HTML preview-able files only
* or if HTML file and live preview isn't active.
=> feat: live preview will not reload on save for html files

src/command/DefaultMenus.js, src/extensions/default/HTMLCodeHints/HTMLJumpToDef.js, src/extensions/default/HTMLCodeHints/integ-tests.js, src/extensions/default/HTMLCodeHints/main.js, src/extensions/default/HTMLCodeHints/unittests.js, src/extensions/default/JavaScriptCodeHints/main.js, src/features/JumpToDefManager.js, test/spec/LiveDevelopment-MultiBrowser-test-files/jumpToDef.html
- feat: ctrl-click to jump to definition on html files. 
- For tag/css class/id attribute, jump to def will initiate quick edit.
- For src/href attribute, we will attempt to find and open the src file.
- test: integ tests for ctrl-click to jump to definition on html files
- chore: refactor jump to def provider hover highlights
=> ctrl-click to jump to definition on html files

.gitignore, docs/generatedApiDocs/features/QuickViewManager-API.md, docs/generatedApiDocs/features/SelectionViewManager-API.md, src/editor/Editor.js, src/extensions/default/QuickView/ImagePreviewProvider.js, src/extensions/default/QuickView/colorGradientProvider.js, src/extensions/default/QuickView/main.js, src/extensions/default/QuickView/numberPreviewProvider.js, src/extensions/default/QuickView/thirdparty/jquery.knob.modified.js, src/extensions/default/QuickView/unittests.js, src/features/PriorityBasedRegistration.js, src/features/QuickViewManager.js, src/features/SelectionViewManager.js, src/language/CodeInspection.js, src/nls/root/strings.js, src/thirdparty/licences/jquery-knob.markdown, src/utils/Metrics.js, test/spec/QuickViewManager-test.js
- chore: add quick view exclusive flag to show only one quick view instead of all for a location
- feat: numeric quick view for live preview
- feat: knob with infinite scroll and  works with negative values touch plus mouse
- feat: knob edit left and right arrow working inside text edit
- feat: quickview language mode detection change on hover
- feat: quickview doesnt dismiss on document change
- fix: quickview number filed update on keyboard edit
- docs: update quickviewManager
- fix: number quick view negative number up and down
* unit and integ tests
* number editor in inline html styles
=>  numeric quick view for live preview

src/phoenix/shell.js, src/phoenix/tauriShell.js
- feat: Tauri shell adapter and window size and positioning logic
- fix: browser load fail after Tauri shell adapter init
* Phoenix will remember the last window's size and resize the window on launch.
* Edge case check like min window size is 800x600, max size should not be larger than monitor size.
=> tauri shell adpater and window size and positioning logic

src/extensions/default/Phoenix/main.js, src/nls/root/strings.js
mitigates https://github.com/phcode-dev/phoenix/issues/703
better error messaging specific to mobile devices not supported
=> fix: showing mobile device is not supported message instead of browser not supported

.github/PULL_REQUEST_TEMPLATE.md, src/devEnable.html, src/index.html
addresses https://github.com/phcode-dev/phoenix/issues/804
Visitors to `dev.phcode.dev` and `staging.phcode.dev` will be redirected to `phcode.dev` unless they go to `dev.phcode.dev/devEnable.html` and `staging.phcode.dev/devEnable.html` to enable dev site access
=> feat: gating development sites behind devEnable flag

src/document/DocumentCommandHandlers.js
* right on file tree and > click new file
* press escape to cancel new file creation
* The new file gets created as untitled - bug 1
* right on file tree and > click new file : nothing happens - bug 2
=> fix: cancelling file>new on escape key caused new file creation to not work again

src/extensions/default/Phoenix/newly-added-features.js, src/phoenix/virtual-server-loader.js, src/virtual-server-main.js
Addresses more of https://github.com/phcode-dev/phoenix/issues/802
Transparent updates mostly without showing an update dialogue to the user.
* change made to cache refresh infra so that cache is only refreshed after phoenix is loaded to prevent inconsistent loads from cached and non-cached js files.
* The update dialogue will now only be shown now if an explicit cache version bump is made in virtual-server-loader.js::_forceClearCacheIfNeeded
* Added metrics for cache stats and errors
=> feat: transparent updates and delay cache refresh till after app loads

src/index.html, src/logger.js, src/phoenix/virtual-server-loader.js, src/virtual-server-main.js
Earlier cache reset was spear across the service worker, the loader script and it brought in too many inconsistent cache management issues as there were too many moving parts and each at varying state of cache.
* Moved all cache reset management to `index.html` . Since it is loaded in a cache first policy, it is guaranteed to be refreshed on second load, and then the main index itself force cleans the cache. This brings in much more cache predictability.
* Phoenix will not load while a reset is in progress and, If the reset succeeded, Phoenix is reloaded again
* Else on cache rest failure, we try to load phoenix as is hoping for the best.
* Cache refresh will be directed by phoenix and will be done after app start. While this can be a problem if we load any files after the app start, this …
=> fix: prevent inconsistant browser cache reset and updates

src/index.html
We are seeing increased startup times in analytics due to defer loading.
* Manually verified in android mobile and browser tabs that the load with cache is around 50% slower than the previous implementation.
* However, the deferred load performed faster without our custom browser cache/ ie on first load.
* Changed all third party libs to defer load as it is safe and doesn't depend on phoenix APIs.
* manually tested that load speed improved in localhost
=> fix: increase load speed by non difer load of third party libs

src/assets/new-project/assets/css/style.css, src/assets/new-project/code-editor.html, src/assets/new-project/new-project-from-url.html, src/assets/new-project/new-project-github.html, src/assets/new-project/new-project-more.html, src/assets/new-project/new-project-website.html, src/assets/phoenix-splash/index.html, src/assets/phoenix-splash/safari.html, src/assets/phoenix-splash/styles.css, src/main.js
Remove google fonts in favor of brackets UI font source-sans pro for better UI consistency, improved load speed from cache, better offline support
- chore: remove google fonts from the splash screen in favor of brackets fonts
- chore: remove google fonts from all new project dialogues
- https://github.com/phcode-dev/phoenix/issues/827
=> Remove google fonts in favor of brackets UI font source-sans pro for better UI consistency, 

src/loggerSetup.js, src/phoenix/init_vfs.js, src/phoenix/shell.js, src/utils/ExtensionLoader.js
* As we enable Extensions, there is a risk that the extension errors will be high and reduce the visibility of core errors. So now, we raise metrics only if we find an extension in the crash stack.
* Extensions are from random sources, and we cannot Quality Control the error stability of extensions.
=> chore: only metrics for extensions errors no bugsnag

src/command/CommandManager.js, src/extensions/default/Phoenix/guided-tour.js, src/view/MainViewManager.js
Right now, there are too many distracting popups on first boot. reduce the,:
1. First, we show the popup in the new project window to select the default project - see the HTML in assets folder
2. After the user opens the default project, we show "edit code for live preview popup."
3. When the user changes a file by clicking on the files panel, we show "click here to open new project window"
this will continue showing every session until the user clicks on the new project icon
4. After about 3 minutes, the health popup will show up.
5. When the user clicks on live preview, we show "click here to pop out live preview"
=> chore: guided tour ux improvement and show actions based on context

src/index.html, src/main.js
* We are seeing higher startup times on the first boot. so reverting in favor of faster first boot times. 
* reload times might be slower by .5 secs.
* Also try to refresh cache if require load failed.
=> chore: deferred load scripts and cache refresh on require load fail

src/styles/brackets.less, src/styles/brackets_variables.less
* Panels hid main menus. Fixed it.
* resize panels, sidebar, plugin and bottom panels work as expected.
=> fix: z-indexes of core ui

src/assets/new-project/assets/css/responsive.css, src/assets/new-project/assets/js/code-editor.js
- Bugfix - currently the newly added "no project video" causes overflow to the right on 720p screens .
- Currently the newly added "no project video" causes overflow to the right 720p screens .
- with this change.
~This will remove the extra padding on both sides of the video.~
- Describe unit tests done -->none
- Describe integration tests done -->none
- Describe manual tests done -->visual inspection
=> fix: project-content-right overflow on 720p screens. 

src/extensions/default/Phoenix/guided-tour.js, src/utils/Metrics.js
* Repeat users are those users who have visited phcode after a day for first use and raise all events with a `R.` prefix.
* Fix guided tour UTC date conversion bug.
=> chore: separate metrics for new and repeat users

src/extensions/default/DefaultExtensions.json, src/extensions/default/Phoenix/main.js, src/styles/brackets_patterns_override.less, src/utils/ExtensionLoader.js, src/utils/Metrics.js, src/view/ThemeManager.js
- refactor: defaultExtension.json loading, metrics for repeat users, error logs
- Extension tests now start loading up in firefox, though most integ tests fail, likely due to some firefox related test infrastructure misconfig.
- fix: removed browser not supported warning showing up in firefox test windows
=> defaultExtension.json loading, metrics for repeat users, error logs

src/brackets.js, src/extensibility/ExtensionManager.js, src/extensions/default/DefaultExtensions.json, src/utils/ExtensionLoader.js, src/view/ThemeManager.js
* we will show the ui as soon as the first theme is loaded instead of waiting for full UI to render. This will significantly boost first-paint times. 
* Also the UI will not flicker from light to dark theme on first boot with this change.
* changed default extension load order to first load light and dark themes.
* Tested in chrome, firefox and edge.
=> feat: increase load speed by showing ui just after first theme load, also reduces boot time flicker

src/command/KeyBindingManager.js, src/features/JumpToDefManager.js, test/spec/KeyBindingManager-test.js, test/spec/Metrics-test.js
* Regression: events like `ctrl-e`/ quick edit if unporcessed were leaking to the browser, causing browser default action on no quick edit.
* fixed and put unit tests
* fixed all failing unit tests except 1 depending on third party.
=> fix: keybord events not being swallowed properly and tests

src/utils/ExtensionLoader.js, src/worker/WorkerComm.js, test/spec/WorkerComm-test.js
- fix: firefox ut failures in worker comm
- fix: flakey firefox extension tests
* Edge/chrome:- full test suite run, works same as before. sanity tests: beautify, find in files, jshint working
* Firefox- 1 unit test breaking of 2259 tests that doesn't break in chrome. integration, tests also have few issues. Other tests mostly inline with chrome.
=> fix FireFox tests

package.json
This is to fix https://github.com/phcode-dev/dev.phcode.dev/actions/runs/4031652849
=> ci: npm test will install playright dependencies before running tests

.github/workflows/create-deploy.yml
For extension authoring, create a seperate https://create.phcode.dev domain that tracks the production branch but builds debug builds so that extension authors can leverage better debug symbols.
=> chore: create.phcode.dev site publish action

src/index.html
Critical load error fix.
This causes repeating users to not be able to use phoenix and be stuck at the splash screen.
Caught by bugsnag. This happens likely as less is invited but less.refresh is not available yet.
=> fix: bugsnag detected app crash on launch if less refresh not present

.github/workflows/pull_request_verify.yml
- Improve future security posture as push action has secret access but not pull requests. I gave a message so that someone in the future doesn't work around this security restriction for pull request secrets. 
- also the build verify badge in readme will only track main branch stability instead fo pull request stability which is the actual intended requirement.
=> ci: separate out build and pull request verify action

package-lock.json, src/extensions/default/Phoenix-live-preview/main.js, src/nls/root/strings.js
Based on user feedback, the following changes were made:
- chore: published sites validity raised to 30 days from 7 based on user feedback
- chore: popout live preview button will now hide the live preview panel
=> popout live preview button will now hide the live preview panel

src/base-config/keyboard.json, src/command/CommandManager.js, src/command/Commands.js, src/command/DefaultMenus.js, src/command/KeyBindingManager.js, src/command/Menus.js, src/nls/root/strings.js, src/view/ViewCommandHandlers.js, test/spec/CommandManager-test.js
More natural browser native zoom.
We could have set the zoom programmatically if we do set document.body.style=zoom = 1,5 ,
But then the new project window or generally any iframes based ui with in phcode will not be affected by zoom resulting in widely inconsistent ux on zoom.
Further, in Firefox, we cannot programmatically zoom, but user can zoom with Ctrl-+ or - shortcut. So if user click on ui menu, all we can do is to show a dialogue asking them to press ctrl + / minus.
VSCode gets away with this as they just have chromium to deal with and not filefox/safari/mobile in native builds. In web based vscode.dev, they don't show the zoom option altogether. We could do similar things in Tauri.
If someone clicks on zoom-in or out menu from the view zoom submenu, we show the dialogue below to …
=> feat: revert to browser native zoom. brackets zoom changed to ctrl-shift-+ or -

package-lock.json, src/extensions/default/CodeFolding/main.js
Fix for: Collapse All does not seem to do what you would want. It collapses all the way to the top indent, usually the tag, which is great. But when you start expanding sub-elements, not all of them are collapsed as well, meaning Collapse All did not really do anything useful. It would be great if Collapse All would collapse all of the elements, as the name implies.
part of https://github.com/phcode-dev/phoenix/issues/1034
=> fix: view > collapse all not working as expected

package-lock.json, src/phoenix/virtualServer/config.js, src/phoenix/virtualServer/content-type.js, src/phoenix/virtualServer/html-formatter.js, src/phoenix/virtualServer/mime-types.js, src/phoenix/virtualServer/webserver.js, test/spec/LiveDevelopmentMultiBrowser-test.js
Fixes:
1. Live preview not working in safari
2. extensions and themes not installable in safari
Caused by safari's JS engine dropping scoped variables in `if` block statements in the service worker, causing variables(Eg. db) not found errors. Now, we create a separate function block.
1. Tested Live preview is working in chrome, Edge, Firefox and Safari in Mac
2. Tested Live preview integration tests is working in chrome, Edge, Firefox and Safari in Mac
3. Tested Extensions and themes install and use is working in chrome, Edge, Firefox and Safari in Mac 
4. Tested Extensions integration tests is working in Safari in Mac
=> Safari Support for live preview and extensions

package-lock.json, src/editor/EditorHelper/EditorPreferences.js
fixes: https://github.com/phcode-dev/phoenix/issues/1058
=> fix: keep Find/Replace dialog open even if user clicks out

package.json, src/extensions/default/NavigationAndHistory/FileRecovery.js
* fix benign issue in js console due to a race condition in project open when no restore data is present.
* metrics for file recovery
We had to do this change as we got a [moderate vulneribility](https://github.com/advisories/GHSA-c2qf-rxjj-qqgw) for lessJS. Less haven't updated their code, so there is nothing we can do other than to upgrade a whole lot of deps that is not worth effort now. So only braking builds for high sev vulnerabilities.
https://stackoverflow.com/questions/61875736/the-command-npm-audit-level-is-not-working-when-trying-to-change-level-to-high
=> fix: file recovery error message in console and add metrics

src/LiveDevelopment/LiveDevServerManager.js, src/extensions/default/Phoenix-live-preview/main.js
1. In chrome incognito mode, live preview doesn't work as it blocks third party cookies which prevents service worker registration somehow. Doesnt happen in edge.
1. works in chrome/chromium except in the incognito mode
2. works in edge in both private/normal mode
3. Works in firefox in normal mode. phoenix wont load in ff in private mode as idb is not available in private mode.
4. to test in safari
=> chore: move to prod url phcode.live for live preview

src/extensions/default/Phoenix-live-preview/main.js
we have to create a new iframe on every switch as we use cross domain iframes for phcode.live which
the browser sandboxes strictly and sometimes it wont allow a src change on our iframe causing live
preview breaks sporadically. to alleviate this, we create a new iframe every time instead of setting the existing iframe.src.
We will have to follow up with disabling popout live preview feature in web builds as it causes breakage due to the web sandbox issues to be outlines in another pr.
=> fix: live preview stability by creating a new iframe on url change instead of reuse

src/LiveDevelopment/BrowserScripts/DocumentObserver.js, src/extensions/default/Phoenix-live-preview/StaticServer.js, src/extensions/default/Phoenix-live-preview/main.js, src/extensions/default/Phoenix-live-preview/markdown.html, src/extensions/default/Phoenix-live-preview/utils.js
* Images are now rendered in live preview iframe using the `pageLoader.html` which disables ctrl-s on live preview panel for images. This files save dialog popup on press of ctrl-s in images
* streamline live preview code
=> fix: live preview stability images in iframe panel in page loader

src/assets/default-project/en/Newly_added_features.md, src/assets/phoenix-splash/live-preview-error.html, src/extensions/default/Phoenix-live-preview/StaticServer.js, src/extensions/default/Phoenix-live-preview/main.js, src/extensions/default/Phoenix-live-preview/utils.js, src/nls/root/strings.js, src/phoenix/virtualServer/webserver.js
live preview can be popped out currently in only chrome based browsers. The cross domain iframe
that serves the live preview(phcode.live) is sandboxed to the tab in which phcode.dev resides.
all iframes in the tab can communicate between each other, but when you popout another tab, it forms
its own sandbox and firefox/safari prevents communication from iframe in one tab to another. chrome
doesn't seem to enforce this restriction. Since this is a core usecase, we will try to enable this
workflow whenever possible.
In tauri based native builds, this will not be an issue as IPC is done via node. Hence popout feature will be supported in all browsers in tauri.
in safari, service workers are disabled in third party iframes. We use phcode.live for secure sandboxing
live previews into its own …
=> safari support is deprecated, use native builds in mac

src/LiveDevelopment/LiveDevMultiBrowser.js, src/extensions/default/Phoenix-live-preview/StaticServer.js, src/extensions/default/Phoenix-live-preview/main.js, src/extensions/default/Phoenix-live-preview/redirectPage.html, src/extensions/default/Phoenix-live-preview/utils.js
When users rapidly switch between HTML files in the file panel, race conditions may arise. This happens when a request to serve the last live previewed page reaches the server just as the live preview is switched to another file. If the server realizes that the current request isn't for the actively live previewed page, it defaults to serving the raw, non-instrumented HTML file.
This can create a problem since the raw HTML file doesn't contain the necessary page navigation hooks. As a result, subsequent switches of HTML files in the file panel don't have any effect and the live preview appears to freeze on one page. This issue is particularly noticeable with popped-out tabs, while the embedded live preview can directly override the iframe URL, circumventing the issue.
To rectify this, we …
=> fix: live preview navigation robustness on fast live preview switch with tabs

.gitignore, gulpfile.js/index.js, src/assets/new-project/assets/css/responsive.css, src/assets/new-project/assets/css/style.css, src/assets/new-project/assets/js/code-editor.js, src/assets/new-project/code-editor.html, src/extensions/default/Phoenix/new-project.js, src/index.html, src/nls/root/strings.js, src/phoenix/init_vfs.js, test/SpecRunner.html, test/index-dist-test.html
We will load `dist-test` folder to run tests in Tauri with GitHub actions..
Initial draft.
If path is larger than what can be shown, hovering will open a tooltip with the full path. 
Inline text marquee not used as it was not good UX- the path was always running.
1. in firefox and safari, the new project window used to flicker on hover on any icons in new project section.
This was due to https://stackoverflow.com/questions/22422926/css-transition-div-shaking and is now fixed
1. the marquee code in CSS is kept though unused for future reference.
=> UI change, show paths in recent project, dist test runner folder setup ofr tauri

src/assets/new-project/assets/css/responsive.css, src/assets/new-project/assets/css/style.css, src/assets/new-project/assets/js/code-editor.js, src/assets/new-project/code-editor.html, src/extensions/default/HealthData/HealthDataNotification.js, src/extensions/default/Phoenix/guided-tour.js, src/extensions/default/Phoenix/new-project.js, src/nls/root/strings.js, src/phoenix/init_vfs.js
1. About Box
2. Show the welcome screen on startup
1. `click here to open new project dialogue` notification will now only be shown once instead of showing it till the user presses the button.
2. Fixed bug in which closing new project dialogue on first launch causes multiple health data popup notifications with every close.
=> feat: new project-welcome screen settings

src/base-config/keyboard.json, src/command/Commands.js, src/command/DefaultMenus.js, src/document/DocumentCommandHandlers.js, src/extensions/default/DebugCommands/main.js, src/extensions/default/Phoenix/main.js, src/extensions/default/Phoenix/new-project.js, src/nls/root/strings.js, src/phoenix/init_vfs.js, src/phoenix/shell.js
1. Test runner now launches in tauri
2. `Phoenix.app.openURLInDefaultBrowser(url)` 
3. `Phoenix.app.openURLInPhoenixWindow`
* In tauri, it will open a tauri window and load that url
* In browser, it will create a new popout window. 
```js
openURLInPhoenixWindow: function (url, {
windowTitle, windowLabel, fullscreen, resizable,
height, minHeight, width, minWidth, acceptFirstMouse, preferTabs
} = {})
``` 
1. Add `file > New Window` menu to open a new phcode window, the shortcut is `Alt-Shift-N`
2. The shortcut is `Alt-Shift-N` was mapped to new Project, as we had only 2 people use the shortcut in the last month from health data, changes it to `New Window` (Same shortcut as vscode).
3. `File>New Project` shortcut is now `Alt-Shift-P`
4. `File>New Folder` shortcut added as `Ctrl-Alt-N`
5. …
=> open test runner in tauri and Phoenix.app.openURLInPhoenixWindow API

.github/workflows/playwright-firefox-integ.yml, playwright.config.js, src/LiveDevelopment/LiveDevMultiBrowser.js, src/LiveDevelopment/MultiBrowserImpl/protocol/LiveDevProtocol.js, src/LiveDevelopment/main.js, src/extensions/default/Phoenix-live-preview/main.js, test/spec/LiveDevelopmentMultiBrowser-test.js, test/spec/SpecRunnerUtils.js, tests-playwright/integration/integration-test-suite.spec.js
unfortunateley, we can run the live preview integ tests only in chrome
In Firefox playwright setup, sandbox prevents service worker access from nested iframes. So the virtual server itself will
not be loaded in firefox tests in playwright.
Do note that this limit is only observed when running tests in firefox under playwright. If you run the live preview integ tests
directly in firefox, the tests run just fine.
In tauri, we use node server, so this limitation doesn't apply in tauri test runners. This restriction is
only there for firefox tests in playwright.
=> feat: enable live preview tests in chromium in GitHub Actions

src/command/DefaultMenus.js, src/filesystem/impls/appshell/AppshellFileSystem.js, src/nls/root/strings.js
[Screencast from 27-10-23 07:33:19 PM IST.webm](https://github.com/phcode-dev/phoenix/assets/5336369/5ee08bfd-b3dc-4a02-b9f3-a6a6c8f9f6d0)
=> feat: enable open files menu in tauri

src/document/DocumentCommandHandlers.js, src/nls/root/strings.js, src/phoenix/shell.js
Closing tauri windows when there are unsaved changes will now popup the unsaved changes dialog and prevent window close
=> fix: close with unsaved changes warning dialog in tauri

src/command/DefaultMenus.js, src/view/ViewCommandHandlers.js, src/view/fontrules/font-based-rules.less
tauri doesnt support zoomin/out and the document.body.style.zoom = 1.5 trick didnt work
as code mirror doesnt support css transform styles. so we just show increase and decrease font size as zoom in tauri.
Browser will default to browser native zoom that works.
Related: https://github.com/phcode-dev/phoenix/issues/1168 address when tauri fixes the issue.
Unable to set file tree font sizes as it has custom selection hilight logic. need to use browser selection logic. Cant fix eazily without major refactor
We should use font size css variables to eazily adjust fonts. Right now there is too many places to adjust css values.
=> feat: zoom in tauri at reduced capacity

src/phoenix/init_vfs.js, src/utils/ExtensionLoader.js
it was found that older document toolbar extension overwrote the window.fs object as window.fs is a phcode new construct. This lead to fs becoming inoperative and unable to uninstall extension in phcode.
putting in guards to safeguard fs lib as much as possible.
=> chore: fs lib overwrite protection

src/project/FileTreeView.js
* Double click to rename is a mac feature in finder. This is not available in windows or linux file explorers.
* Brackets implementing it across all os is confusing to the user in windows and linux when the user doesnt expect the file to be renamed on double clicked.
* On mac, other code editors like vscode do not have this feature. So it will be confusing workflow to mac devs too.
* Also for larger files, the file load delay will interfear with the double click timers and it will confuse the user as to weather the double click worked to rename or to open the file and ad to working set.
=> fix: remove double click to rename feature as its bad ux

src/extensionsIntegrated/NoDistractions/main.js
* In Mac `fullscreen` shortcut is `Cmd-F11` and in Win/Linux Its Just `F11`
* Changes No distractions mode shortcut to `Shift-F11` in all platforms instead of `Ctrl-Shift-2` to be more intuitive as people using no distractions are also more likeley to use full screen and shence can do both without moving hands much.
Toggle Panels and Toggle sidebar not changed as it will likeley in future change to `Shift-Escape` key workflow, See: https://github.com/phcode-dev/phoenix/issues/1234
=> fix: mac fullscreen shortcut f11 is system shortcut show desktop

src/document/DocumentCommandHandlers.js, test/spec/DocumentCommandHandlers-integ-test.js
This will help eazily identify projects if there are multiple windows and tabs instead of file names that may be common in many projects.
Fixes: https://github.com/phcode-dev/phoenix/issues/945
=> style: window titles will start with project names instead of file name

src/editor/EditorCommandHandlers.js, src/phoenix/shell.js, test/spec/EditorCommandHandlers-integ-test.js
The issue at hand is that users are unable to perform paste actions when clicking on "Edit" menu > "Paste" or the editor context menu > "Paste" in Tauri desktop builds. This problem arises because the browser clipboard APIs are not available in Tauri, necessitating the use of Tauri's own clipboard access APIs.
Clipboard API in browser will usually popup a clipboard access popup which the user have to click agree manually. In tauri this popup never comes. So we add tauris clipboard APIs.
Integration tests for Tauri clipboard access added. It's important to note that these tests will exclusively function in the Tauri environment. Regrettably, browsers do not permit unattended clipboard access due to security considerations. As a result, the copy-paste test is disabled when running in a …
=> fix: clipboard edit menu>paste not working in tauri

src/extensions/default/DebugCommands/main.js, src/nls/root/strings.js
UX change so that the user doesnt get confused with debug and dev tools for their project vs tools to debug and diagnose phoenix.
=> feat: sub menu refactor phoenix diagnostic tools to not confuse user

docs/generatedApiDocs/NodeConnector-API.md, src-node/node-connector.js, src-node/test-connection.js, src/NodeConnector.js, src/document/DocumentCommandHandlers.js, src/extensions/default/DebugCommands/main.js, src/node-loader.js, test/spec/NodeConnection-test.js
Node Connector Communication Module
This module simplifies communication between Node.js and Phoenix (phcode). A `NodeConnector` acts as an intermediary,
allowing you to execute functions in Node.js from Phoenix and vice versa. You can use the `execPeer` method to call
functions on the other side and handle communication seamlessly. Use `triggerPeer` to trigger events
on the other side.
To establish communication between two modules, such as `x.js` in Phoenix and `y.js` in Node.js, follow these steps:
```js
const NodeConnector = require('NodeConnector');
const XY_NODE_CONNECTOR_ID = 'ext_x_y'; // Use a unique ID
let nodeConnector = NodeConnector.createNodeConnector(XY_NODE_CONNECTOR_ID, exports);
exports.modifyImage = async function(imageName, imageArrayBuffer) {
// Perform image …
```
=> chore: createNodeConnector API returns ready to use node connector instead of promise

src-node/index.js, src/node-loader.js
* Catch uncaught exceptions and erros in node and log in bugsnag, strip all user file system paths from stack for privacy.
* fix: bind phNode api server to localhost only to prevent windows firewall dialog
=> chore: privacy aware node bugsnag crash reporting

docs/generatedApiDocs/utils/FeatureGate-API.md, src/base-config/keyboard.json, src/command/DefaultMenus.js, src/command/KeyBindingManager.js, src/document/DocumentCommandHandlers.js, src/editor/CodeHintManager.js, src/extensions/default/CodeFolding/main.js, src/extensions/default/DebugCommands/main.js, src/extensions/default/NavigationAndHistory/FileRecovery.js, src/extensions/default/NavigationAndHistory/NavigationProvider.js, src/extensions/default/NavigationAndHistory/keyboard.json, src/extensions/default/Phoenix-live-preview/main.js, src/extensions/default/Phoenix/guided-tour.js, src/extensions/default/Phoenix/new-project.js, src/index.html, src/nls/root/strings.js, src/search/FindBar.js, src/view/ViewCommandHandlers.js, test/BootstrapReporterView.js, test/SpecRunner.html, test/spec/KeyBindingManager-test-files/duplicateShortcuts.json, test/spec/KeyBindingManager-test-files/keymap.json, test/spec/KeyBindingManager-test-files/macKeymap.json, test/spec/KeyBindingManager-test.js, test/spec/SpecRunnerUtils.js
1. Add Keyboard shortcuts on hover of top nav bar ![image](https://github.com/phcode-dev/phoenix/assets/5336369/077d46da-7543-4254-b6fd-30ed87d06abd)
2. Change nav shortcuts- `Alt-Left arrow` for nav back and `Alt-Right arrow` to nav forward
3. `Ctrl-Shift-0` - show in file tree
4. new file - `Ctrl-N` - desktop only and `Ctrl-1`(all platforms)
5. new folder - `Ctrl-3`(all platforms)
6. new window - `Ctrl-Shift-N` - desktop only. In browser, use can do `ctrl-T` and type phcode.dev using browser shortcuts itself. So we dont make a browser shortcut for this.
7. file Close - `Ctrl-W` - desktop only and `` Ctrl-` `` (all platforms)
8. Open file - `Ctrl-O` in desktop only as browser doesnt support open file feature
9. Open Folder - `Ctrl-O` browser only, open folder has no shortcut in desktop …
=> Shortcut refactor and fix UX issues with keyboard shortcuts

src/LiveDevelopment/BrowserScripts/LivePreviewTransportRemote.js, src/LiveDevelopment/BrowserScripts/pageLoaderWorker.js, src/LiveDevelopment/LiveDevMultiBrowser.js, src/document/DocumentManager.js, src/extensions/default/HealthData/SendToAnalytics.js, src/extensions/default/Phoenix-live-preview/StaticServer.js, src/extensions/default/Phoenix-live-preview/main.js, src/extensions/default/Phoenix-live-preview/markdown.html, src/extensions/default/Phoenix-live-preview/panel.html, src/extensions/default/Phoenix-live-preview/utils.js, src/index.html, src/live-preview-loader.html, src/live-preview.html, src/nls/root/strings.js, src/node-loader.js, src/phoenix/shell.js, src/storage.js, src/utils/PerfUtils.js, test/SpecRunner.html, test/spec/LiveDevelopmentMultiBrowser-test.js
Externally opened tabs will now show a live preview warning. This is so that if a live preview has the same url as `phcode.dev` and it may mislead the user if the live preview tries to show off itself as phcode.dev when user opens an untrusted project.
So on evry project switch/new tab open, we will show the trust live preview dialog. This is only an issue in browser as in desktop, live previews will be loaded from loaclhost instead of virtual server at `phcode.dev`.
=> Live Preview Desktop first draft

src/extensions/default/Phoenix-live-preview/main.js, src/extensions/default/Phoenix-live-preview/trust-project.html, src/features/QuickViewManager.js, src/features/SelectionViewManager.js, src/live-preview-loader.html, src/nls/root/strings.js, src/project/ProjectManager.js
In desktop builds, each project is securely sandboxed in its own live preview server:port domain.
This setup ensures security within the browser sandbox, eliminating the need for a trust confirmation dialog. We can display the live preview immediately.
In browsers, since all live previews for all projects uses the same `phcode.live` domain,  untrusted projects can access data of past opened projects. So we have to show a `trust project?`  dialog in live preview in browser.
Future plans for browser versions include adopting a similar approach to dynamically generate URLs in the format `project-name.phcode.live`. This will streamline the workflow by removing the current reliance on users to manually verify and trust each project in the browser.
```console
QuickViewManager.js:457 …
```
=> feat: add a trust project for live preview in phoenix iframe- browser only

src/extensions/default/Phoenix-live-preview/StaticServer.js, src/extensions/default/Phoenix-live-preview/main.js
1. Increase live preview startup speed by removing 1 second start delay and only relying on server start event to trigger preview show.
2. Live preview briefls flickers a github 404 on very first boot(test in incognito window) as the vritual server is being setup. This is fixed as we now only open preview pane after server start event.
3. On untrusted projects on boot, the live preview was a blank page which never switched on.
=> fix: 1.live preview start speed, 2.flicker 3.not showing in untrusted projects

.gitignore, gulpfile.js/thirdparty-lib-copy.js, package-lock.json, package.json, src/index.html, src/main.js, src/storage.js, src/thirdparty/licences/idb-keyval.markdown, test/SpecRunner.html
Browsers can only store up to 5 MiB of local storage, so we have to move to indexed DB for PhStore in browser - https://developer.mozilla.org/en-US/docs/Web/API/Storage_API/Storage_quotas_and_eviction_criteria#web_storage
=> chore: move to indexed db for PhStore instead of localstorage with 5MB Storage limit

src/extensions/default/Phoenix-live-preview/main.js, src/extensions/default/Phoenix-live-preview/panel.html, src/live-preview-loader.html
Since its an HTML development tool, it will confuse users if we disable window.open/ anchor tag hrefs not opening up new windows. So we enable that.
The security posture wont change due to this as 1, since the iframe is sandboxed, the popout that escaped the sandox will no loger be able to communicate with phcode, and hence isolated.
Another thing to note is that, for virtual serving urls, the popout will result in a 404 as the virtual server is sandboxed within a tab/phcode. But this is the case even before this change. Normal click-navigations will not be affected, just `open link in new tab` workflows with virtual server target urls will fail.
=> fix: live preview should allow tab popout on window.open or href click

src-node/index.js, src-node/live-preview.js, src-node/lmdb.js, src-node/www/externalProject/reamde.md, src/LiveDevelopment/BrowserScripts/pageLoaderWorker.js, src/document/DocumentCommandHandlers.js, src/extensionsIntegrated/Phoenix-live-preview/NodeStaticServer.js, src/extensionsIntegrated/Phoenix-live-preview/main.js, src/nls/root/strings.js, src/phoenix/shell.js, test/spec/LiveDevelopmentMultiBrowser-test.js, test/spec/SpecRunnerUtils.js
Overview:
- This feature allows for the preview of files that are not part of the current project.
It's specifically for files that users open in the editor but which are outside the scope
of the project being worked on. Useful when users want to quickly view or edit files that are not
part of the project without integrating them into the project's environment.
- The previews for these external files are loaded from a static server URL, not the usual live preview
server URL.
- This separation ensures that the active live preview environment does not have access to resources
from external projects.
- For security reasons, only the content of the currently viewed file is served in this special
live preview mode.
- HTML files are specifically not served in the live preview of external …
=> feat: non-live preview of non project files

src/LiveDevelopment/MultiBrowserImpl/protocol/LiveDevProtocol.js, src/phoenix/shell.js, test/spec/LiveDevelopmentMultiBrowser-test.js
chore: reverse highlight should also be disabled when live preview highlight feature deisabled
=> chore: reverse highlight should also be disabled when live preview highlight feature deisabled

src/project/ProjectModel.js, test/spec/ProjectModel-test.js
Earlier, for external project files, this used to do nothing, and the user would be a bit confused on where the file is located or if they actually clicked on the icon as nothing happened. Address the UX.
=> feat: click binoculor icon/locate in file tree for non project files now opens file in os explorer

src/document/DocumentCommandHandlers.js, src/phoenix/shell.js, src/project/ProjectManager.js, test/spec/Tauri-platform-test.js
This pull request introduces enhancements to our Tauri application to ensure it operates as a single instance. Additionally, it implements functionality to handle files and folders opened from the OS file explorer, improving user experience across Windows, macOS, and Linux platforms.
The proposed changes leverage the Tauri single instance plugin- see taur changes here: https://github.com/phcode-dev/phoenix-desktop/pull/184 . This approach guarantees that only one instance of our application runs at any given time. If a user attempts to open a new instance (e.g., by double-clicking a file associated with our app in the file explorer), the new instance will pass its command line arguments (CLI args) to the existing instance and then exit.
1. **Single Instance Check**: On launch, the …
=> feat: desktop open with from file explorer working for files and folders

src/base-config/keyboard.json, src/command/KeyBindingManager.js, src/extensionsIntegrated/NoDistractions/main.js, test/spec/KeyBindingManager-test.js
Fixes: https://github.com/phcode-dev/phoenix/issues/1078
We were using physical keys which are mostly suited for gaming with international keyboards using the `wasd` keys.
Chnaged to use logical keys. 
This was not ain issue in brackets as brackets used `event.keyCode` which was deprectaed by w3c and was inconsistant when we moved to modern browsers from brackets shell. We earlier moved to physical key apis as the recommended replacement by w3c along with logical `key` api. Now moved to logical.
=> fix: non english keyboard shortcut change from physical to logical keys

src/brackets.js, src/command/KeyBindingManager.js, src/command/Menus.js, src/extensionsIntegrated/RecentProjects/main.js, src/styles/brackets_patterns_override.less, src/view/MainViewManager.js, src/widgets/PopUpManager.js
1. `Ctrl/Cmd-Space` doesnt trigger code hints. This is a regression that happened after we moved KeyBindingManager to use `event.key`.
2. A bug in project dropdown where the keyboard search filter doesnt get reset on popup close.
=> feat: keyboard navigation of top menu (left and right arrow)

.github/workflows/desktop-mac-m1-test-pull.yml
M1 github actions runners are now available
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
=> ci: m1 runners for desktop integ tests

src/brackets.js, src/command/KeyBindingManager.js, src/command/KeyboardOverlayMode.js, src/command/Keys.js, src/command/Menus.js, src/index.html, src/styles/brackets.less, src/styles/brackets_theme_default.less, src/styles/brackets_variables.less, src/view/WorkspaceManager.js
1. Double click on ctr/command key to start the keyboard workflows
2. hide mouse cursor when the user is typing something in editor, on mouse move, it will be shown again.
=> feat: all new keyboard navigation workflows

src/document/DocumentCommandHandlers.js, src/extensionsIntegrated/Phoenix/new-project.js
1. when a file/folder is opened with phcode, we dont show the new project dialog.
2. In mac, we get the file opened event later as an event, special handling in that case
3. Open wil with multiple windows present, special handling.
=> chore: close new project dialog if open with trigerred from os

src/editor/EditorStatusBar.js, src/extensionsIntegrated/appUpdater/main.js, src/features/TaskManager.js, src/styles/brackets.less, src/tauri-updater.html, test/spec/TaskManager-integ-test.js
To make the task spinner less distracting, the following changes were made:
1. The spinner will only be shown for 3 seconds when a task is created.
2. The spinner will be shown coninuously in green color if there is a success notification that the user should see.
3. the pinner will spin in red on any task failure untill user cicks the tasks list, or the faulre is resoved automatically.
4. When the task closes itself, the spinner will adjust to the most appropriate color based on success/fail tasks pending in the list.
To verify after scripts deployment
=> feat: task spinner ux improvement and integ tests

src/extensionsIntegrated/RecentProjects/main.js, src/storage.js, test/spec/TaskManager-integ-test.js
This pull request addresses data consistency issues in Tauri applications with multiple windows. Previously, each window committed its storage changes to disk on exit or every 30 seconds, leading to potential stale data when a new window is created and the new window will read stale dump file.
The solution introduces a local memory cache in Tauri's Rust backend. This cache consolidates storage changes from all windows, providing immediate access to the latest data before disk commit. It ensures all windows work with the most current storage state, bypassing the delay of dump file creation in multi window mode. This works as our app in a ingle instance - multiple window app.
Changes:
- Added a local memory cache in Rust to aggregate storage updates from multiple windows.
- Updated storage …
=> chore: multi window sync for phstore

src/assets/new-project/assets/js/code-editor.js
The github project option in desktop will overload our poor servers, and its unnecessary as desktop builds can clone themselves. So disabing this feature in desktop builds till we have native git integration.
=> chore: remove github project option from desktop builds till git integration

src/assets/new-project/assets/css/style.css, src/assets/new-project/assets/js/code-editor.js, src/nls/root/strings.js, src/preferences/PreferencesImpl.js, src/preferences/StateManager.js
Bin icon generally means delete and is not the correct one to remove folder from list without deleting the folder.
Earlier:
In browser, we still have users in the old state manager, so if we just switch to phstore, they will loose their recent projects(which can seem like a data loss for browser only projects, thought the underlying virtual fs folders are not deleted.), 
We don't restore everything from previous state manager as it may lead to corruption if there is some custom state injected by extensions, just enough to not lose project data.
=> chore: migrate legacy state and change bin icon for remove from recent projects 

src/project/ProjectManager.js, src/project/ProjectModel.js, src/search/FindInFiles.js, test/spec/FindInFiles-integ-test.js, test/spec/FindReplace-test-files/node_modules/node_modules/test2.js, test/spec/FindReplace-test-files/node_modules/test.js
Selecting the node_modules folder and selecting `find in` should override the node module or other filters and trigger a find in the folder. Useful when you want to search within a specific package in the node_modules folder
=> fix: force find in node_modules should work

.github/workflows/desktop-linux-prod-test-pull.yml, .github/workflows/desktop-linux-test-pull.yml, .github/workflows/desktop-mac-m1-test-pull.yml, .github/workflows/desktop-mac-test-pull.yml, .github/workflows/desktop-windows-test-pull.yml, src/styles/brackets.less
The colors of toast notification has been improved for error, info, etc.. see info style color scheme in below pic.
fix mac frequent node download failures by using GitHub auth downloads.
=> fix: frequent 403 for node download in desktop tests and toast notification better visual hyperlink colors

src-node/installer/download-file.js, src/extensionsIntegrated/appUpdater/main.js, src/node-loader.js
See phoenix code `3.3.4` in applicastions folder and `3.3.6` in `<appdata>/installer/extracted/Phoenix Code.app` folder both being listed in open with in mac. This was happening as we downloaded and extracted the update while `3.3.4` was running into the appdata folder, and Mac will detect `3.3.6` and will start to list the app in the `open with menu` even though its not yet installed.
=> fix: mac updates will be extracted nad deleted on appquit to prevent multiple app listing in open with

src/command/KeyBindingManager.js, src/command/KeyboardOverlayMode.js, src/nls/root/strings.js, test/spec/Keyboard-nav-integ-test.js
1. To prevent accidental activation as from user feedback, changed ui nav shortcut to triple ctrl/cmd key press instead of double.
2. Added shortcut `Ctel-P` to ui visual nav as this will be our visual command palette workflow.
=> Feat: visual command navigation palette on ctrl-p and triple ctrl key

gulpfile.js/thirdparty-lib-copy.js, package-lock.json, src-node/package-lock.json, src-node/package.json, src-node/utils.js, src/extensionsIntegrated/Phoenix-live-preview/live-preview.css, src/extensionsIntegrated/Phoenix-live-preview/main.js, src/extensionsIntegrated/Phoenix-live-preview/panel.html, src/nls/root/strings.js, src/utils/NodeUtils.js
In desktop browsers, hovering over the live preview title bar will reveal the `open live preview in chrome, edge, safari and firefox buttons`
[Screencast from 01-04-24 04:15:48 PM IST.webm](https://github.com/phcode-dev/phoenix/assets/5336369/49830b88-192c-411c-a2db-bd44daefbdd9)
Fixes https://github.com/phcode-dev/phoenix/issues/1449
=> feat: open live preview in chrome, edge, safari and firefox buttons

src/brackets.js, src/command/Commands.js, src/command/DefaultMenus.js, src/editor/EditorOptionHandlers.js, src/nls/root/strings.js, src/styles/brackets.less, test/spec/EditorOptionHandlers-integ-test.js
Addresses part of https://github.com/phcode-dev/phoenix/issues/1237
```json
// An array of ruler colors corresponding to the rulers option in the editor. Eg: ["#3d3d3d", "red"]
"editor.rulerColors": [],
// An array of column numbers to draw vertical rulers in the editor. Eg: [80, 100]
"editor.rulers": [],
// true to enable editor rulers, else false
"editor.rulersEnabled": true,
```
=> feat: vertical ruler in editor, supports multiple vertical rulers

src/LiveDevelopment/BrowserScripts/LiveDevProtocolRemote.js, src/LiveDevelopment/MultiBrowserImpl/protocol/LiveDevProtocol.js, src/extensionsIntegrated/Phoenix-live-preview/BrowserStaticServer.js, src/extensionsIntegrated/Phoenix-live-preview/NodeStaticServer.js, src/extensionsIntegrated/Phoenix-live-preview/live-preview.css, src/extensionsIntegrated/Phoenix-live-preview/main.js, src/nls/root/strings.js, src/view/MainViewManager.js, src/view/Pane.js, test/spec/LiveDevelopment-MultiBrowser-test-files/cssLive.css, test/spec/LiveDevelopment-MultiBrowser-test-files/cssLive1.less, test/spec/LiveDevelopment-MultiBrowser-test-files/cssLive1.sass, test/spec/LiveDevelopment-MultiBrowser-test-files/cssLive1.scss, test/spec/LiveDevelopment-MultiBrowser-test-files/cssLivePreview.html, test/spec/LiveDevelopmentMultiBrowser-test.js, test/spec/SpecRunnerUtils.js
Add support for selecting css selectors in code if a css file is open as active document when user click on an element in live preview. 
On clicking an html dom node when a related css file(or any less/scss/sass file) is the active document, a css style with the nodes `#id` is searched, then `.class`. IF no match is found, it will search the nodes parents selector id and classes in the css file. If none is found till the root element, it will check for tag styles.
Also Fixes: https://github.com/phcode-dev/phoenix/issues/822
=> feat: live preview reverse CSS highlights and ux improvement

src/LiveDevelopment/LiveDevMultiBrowser.js, src/LiveDevelopment/main.js, src/extensionsIntegrated/Phoenix-live-preview/main.js, src/utils/StringUtils.js, test/spec/LiveDevelopmentMultiBrowser-test.js
Fixes issues:
1. pressing reload button when live previewing HTML file and current file is a css file, will open no preview page instead of just a page reload.
2. Pinned live previews and reload was not working as expected.
3. Added integ tests to cover the cases.
4. Also fixes live preview and editor becomes slow after editing html pages for a long time due to live preview documents not being closed. This leads to event handler attached on the currently edited document being not released. This leads to too mans handler calls on an edit and generally slows down the editor. Proper cleanup is now done.
=> chore: predictable refresh live preview on html/non html/pin files and tests

src/document/DocumentCommandHandlers.js
We cannot distinguish between the user editing a default project file which maybe just testing, or doing any actual editing with the app.
=> chore: seperate out default project file operation metrics

src/brackets.js, src/editor/Editor.js, src/editor/EditorCommandHandlers.js, src/editor/EditorManager.js, src/language/languages.json, test/SpecRunner.js
fixes: https://github.com/phcode-dev/phoenix/issues/1561
=> fix: cannot uncomment markdown comment, fallbak to codemirror comment plugin

src/extensions/default/CSSCodeHints/css-lint.js, src/extensions/default/JSHint/main.js, src/language/CSSUtils.js, src/language/CodeInspection.js, test/spec/Extn-CSSCodeHints-integ-test.js, test/spec/LanguageTools-test-files/css-language-service/css-lint-errors.min.css
Also adds css fetch flooding protection.
External http/s CSS stylesheet fetches only happen once every 10 seconds to prevent loading web servers on every code hint type. Cached external links are never fetched again, but problem happens when links fetch fails, and can be immediately retried on next key press. we need to block that and do it once in 10 seconds only.
=> chore: should not lint minified css and js files

src/brackets.js
Bugfix - fixes issue #310 
I ran into the above issue a few weeks ago...
The current behavior is that Phoenix Code will not check for changes made on the local filesystem if that's where the project is being stored. Although there are checks to ensure that opened files are not out of sync, the `ProjectManager` module does not consistently check for new files in the local directory. 
Since changes on the local filesystem (like the example cited in #310 where a file is created via the terminal) typically occur while the user is not in the Phoenix Code window, we can check the local filesystem for changes when the user returns to the window. 
I added a call to `refreshFileTree()` when Phoenix Code comes back into focus, which has resolved the issue.
- No
Tested on Windows and macOS with …
=> fix: file tree does not refresh automatically

src/htmlContent/problems-panel-table.html, src/language/CodeInspection.js, src/nls/root/strings.js, src/styles/brackets.less
* Users can now select text in problems panel by selecting text with mouse cursor and copying.
* Also added a copy button that will be visible on hover over each problem
=> feat: copy problem button in problems panel

src/extensions/default/DarkTheme/main.less
=> chore: matching tags, refs color scheme change in dark theme

gulpfile.js/index.js, gulpfile.js/thirdparty-lib-copy.js, package-lock.json, package.json, src-node/package-lock.json, src/extensions/default/CSSCodeHints/main.js, src/phoenix/shell.js, src/thirdparty/licences/fuzzball.markdown, src/utils/ColorUtils.js, src/utils/StringMatch.js, test/spec/Phoenix-platform-test.js
* css code hints will now hint full css key-value pairs like `align-content: space-around;` when just typing `around`. Now dont have to remember which value is under which property.
* also enables live previews of those `property:value;` pairs!
* Now we sort popular properties to to. For eg: typing just `b` will list `background-color` to top even though its not alphabetically on top.
* Added new fuzzball liib (GNU/GPL2) for string matching for code hints `Phoenix.libs.fuzzball`
See commits for more details.
=> chore: compound css prop:val; code hints

src/extensionsIntegrated/Phoenix-live-preview/NodeStaticServer.js, src/extensionsIntegrated/Phoenix-live-preview/main.js
`noPreview` flag was not set correctly for text files and other non-previewable file types when opened from the 'Open With' option in the file explorer. Previously, attempting to open these files would mistakenly trigger a `no preview` page, due to the incorrect flag handling.
- Updated the flag assignment logic to correctly identify and set the `noPreview` flag for all supported non-previewable files, regardless of their location relative to the project directory.
opening text files/other non-preview files will no longer open a `no-prview` HTML page on startup.
=> fix: opening text files with open with opens live preview on startup

src/editor/EditorHelper/ChangeHelper.js, src/extensions/default/CSSCodeHints/main.js, src/extensions/default/HTMLCodeHints/main.js
on live code hints, when the user is selecting code hints using arrow keys, the text in the editor changes.
If the text that is being changed falls beyond the editor border(Eg: end of a long line that is part occluded
by live preview panel), then cm will scroll the editor horizontally to show the changed text. On scrolling,
all popups are usually dismissed(see scroll event handler in this file), but that should happen if we
are live code hinting. So we do this.
https://github.com/phcode-dev/phoenix/assets/5336369/ed6b8efc-1172-4a2a-9dd5-6fc2ff604e9d
=> fix: live code hints gets dismissed when pressing arrow keys

src/extensions/default/QuickView/colorGradientProvider.js, src/nls/root/strings.js
Based on feedback: 
> It would be awesome to see a hex editor so that when you hover over the hex code and it displays the color, it also gives a box which has a hex picker, similar to what google has.
Solution: we already have this feature, but not visual indication. So added explicit edit button and text.
=> chore: add edit button to color swatch

src/command/DefaultMenus.js, src/document/DocumentCommandHandlers.js, src/filesystem/impls/appshell/AppshellFileSystem.js
Fixes: https://github.com/orgs/phcode-dev/discussions/1653
Save As is now available in desktop apps:
save as is not yet supported in browser as in our vfs implements only open folder, so vfs needs to
be changed. Also, we don't know how the ux for save as will be in virtual paths.
=> feat: enable save as file dialog in desktop builds

src/extensionsIntegrated/Phoenix/guided-tour.js
In the current method, all the existing desktop apps which has not been updated will use the browser survey, not what we want.
=> chore: survey so that all existing desktop installs use dekstop survey

src/desktop-metrics.html, src/drop-files.html, src/nls/root/strings.js, src/phoenix/shell.js, src/utils/DragAndDrop.js
Related shell change: https://github.com/phcode-dev/phoenix-desktop/pull/441
Tauri's file drag and drop is broken. See: 
https://discord.com/channels/616186924390023171/1245330514404048896
So we create a hidden fileDrop window that has `fileDropEnabled` set to true. When we detect a file drop drag over event using html5 apis, we use tauri apis to show the `fileDrop` window over the html element. the bounds over which the window should be rendered is calculated with tauri api's as well. it is tested in multi monitor setups to work in linux, windows and mac.
In linux there is this strange artifact coming when dropping files over a droppable window. 
so we have disabled this is linux for the time being. 
No yet implemented as we wont get write access to the dropped file/folder in most …
=> feat: add drag and drop support in windows and mac desktop apps

src/extensions/default/DebugCommands/main.js, src/nls/root/strings.js, src/utils/DragAndDrop.js, src/utils/Metrics.js
This menu is shown only in desktop Linux builds as
1. drag and drop is supported in windows/mac.
2. In Linux, there is some icon ghosting seen, so its under a flag.
3. in browsers drag and drop is not supported at all for now.
=> feat: drag and drop experimental menu in linux

src/drop-files.html, src/utils/DragAndDrop.js
Related to https://github.com/phcode-dev/phoenix/pull/1699
We now draw the drop area as full window
Note that the drop window may be on different screens if multi window setup. in windows os, there can be
of different scale factors like 1x and 1.5x on another monitor. Additionally, we may apply our own zoom
settings. So its is always better to just use the tauri provided positions. the tauri api returned values
will position the window to the correct monitor as well.
so we removed the old html element relative drawing as its not trivial to account for all the scale factor/zoom/display resolutions combos when the tauri api itself behaves unpredictable in different platforms/display conditions. We now draw over the full window bounds.
=> drag and drop in native builds ui rendering fixes for tauri

src/base-config/keyboard.json, src/command/Commands.js, src/command/DefaultMenus.js, src/command/Menus.js, src/document/DocumentCommandHandlers.js, src/extensionsIntegrated/DisplayShortcuts/templates/bottom-panel.html, src/extensionsIntegrated/DisplayShortcuts/vscode.json, src/extensionsIntegrated/NavigationAndHistory/keyboard.json, src/extensionsIntegrated/NavigationAndHistory/main.js, src/language/CodeInspection.js, src/nls/root/strings.js, src/styles/brackets_patterns_override.less, test/UnitTestSuite.js, test/spec/Generic-integ-test.js, test/spec/SpecRunnerUtils.js
* `ctrl-shift-T` is reassigned from navigate.jump to definition in project as only 7 people has used it in the last month and i suspect they were trying to do reopen closed workflow as in vscode.
* `ctrl-shift-T` shortcut is not assignable in browser as it is open last closed tab browser shortcut. So in browser, this is left blank for user to choose.
=> Reopen closed files - ctrl-shift-t

src/base-config/keyboard.json, src/command/Commands.js, src/command/DefaultMenus.js, src/editor/Editor.js, src/extensionsIntegrated/DisplayShortcuts/vscode.json, src/language/CodeInspection.js, src/nls/root/strings.js, test/spec/CodeInspection-integ-test.js
* Brackets had got to first problem option only. That is not very useful.
* This matches vscode implementation to go to next and prev problem from cursor.
* Goto first problem command is there for backward compatibility, but it has been omitted from UI.
* shortcut is `ctrl-i` and `ctrl-shift-i` in all platforms. we didnt use vscodes `f8` key as `f8` will be reserved for browser dev tools operations as phcode is web first editor and we will try to use browser shortcuts when possible.
* Vscode shortcut pack will use `f8` and `shift f8`
=> feat: go to next and previous problem

src/index.html
Fixes: https://github.com/phcode-dev/phoenix/issues/1729
There is no `~/Documents` folder in some Linus distros, which we assumed Tauri resolves in all platforms. So now we will fall back to the home folder itself if we can't determine the user documents folder, and if we can't resolve that, we will fall back again to the appdata folder.
=> fix: wont start up in some fedora distors coz no document folder in some

src/extensionsIntegrated/Phoenix/guided-tour.js, src/extensionsIntegrated/Phoenix/html/survey-template.html, src/index.html
Surveys now popup instantly without waiting for the loading screen, which will reduce user frustration on seeing a loading screen without knowing what it is and possibly increasing the survey participation rate.
=> chore: survey prefetch for better UX

src-node/package-lock.json, src/extensions/default/QuickView/ImagePreviewProvider.js, src/extensions/default/QuickView/unittests.js, src/filesystem/File.js, test/spec/quickview-extn-test-files/img/chinese.svg, test/spec/quickview-extn-test-files/test.css
This was as we always read images for quick view as binary and base64 encoded it. But for SVG files, if we read it as binary once, it gets cached as binary encoding, and will never read as htf8 text if not explicitly specified. since normal flows wont specify it, the file cannot be opened again due to encoding mismatch.
=> fix: clicking on svg image quick views break open of that svg file

src/extensions/default/DarkTheme/main.less
Earlier the dark theme gutter was so  close to background color. The dark theme was affected as we changed the `.codemirror`  CSS elements hierarchy on an earlier change for fixing active line HTML black highlights mostly.
=> fix: code folding markers disapear when hovering over gutter in dark theme

src/editor/Editor.js, src/extensions/default/DefaultExtensions.json, src/extensionsIntegrated/htmlTagSyncEdit/main.js, src/extensionsIntegrated/loader.js, src/nls/root/strings.js, src/styles/brackets.less
Automatically rename paired HTML/XML/SVG/et.al tags.
[Screencast from 20-07-24 04:36:17 PM IST.webm](https://github.com/user-attachments/assets/54e6b05a-e832-4f00-b36e-a975d2d80373)
1. Only works in `html/xhtml/htm/xml/svg/php/jsp` files for now.
2. pressing escape will temporarily disable the sync. but it can be enabled by moving cursor out of tag pair and coming back.
3. Menu item to disable it permanently with `Edit > Auto Rename HTML Tags` ![image](https://github.com/user-attachments/assets/fc9d58a1-7828-4872-b146-ebde3b6b3def)
=> feat: auto rename html/XML/SVG tags

src/command/KeyBindingManager.js, src/command/KeyboardOverlayMode.js, src/nls/root/strings.js
Address: https://www.reddit.com/r/brackets/comments/1eam4vq/comment/leymxt4/?context=3
* Changed triple key detect algorithm to be more robust to prevent accidental engagement of the visual command palette ui
* Also added preference `tripleCtrlPalette`: `true/false` to enable/disable feature
=> chore: better robustness for triple control key press detect and disable preference

src/LiveDevelopment/MultiBrowserImpl/protocol/LiveDevProtocol.js, test/spec/LiveDevelopmentMultiBrowser-test.js
Currently, when live previewing an HTML file (e.g., a.html) and switching to an unrelated file (e.g., a.json or a TypeScript file generated by a build step), clicking on the live preview unexpectedly switches the editor back to the main HTML file. This behavior disrupts the user’s workflow, especially when working on files indirectly related to the HTML being previewed. Users might find themselves forcibly navigated away from the task at hand, leading to potential confusion and inefficiency.
The behavior was initially added to phoenix to help new users navigate better, but is not hindering more advanced workflows that needs more user context. So we are reverting this change.
This pull request introduces a change to maintain workflow continuity:
1. **Preserve Current Editor State:** If a …
=> fix: live preview UX where clicking on lp will open html when editing unrelated ts/json/js file

src/brackets.js, src/editor/Editor.js, src/editor/EditorHelper/EditorPreferences.js, src/editor/EditorHelper/IndentHelper.js, src/editor/EditorStatusBar.js, src/extensions/default/DebugCommands/MacroRunner.js, src/extensions/default/Phoenix-prettier/main.js, src/extensions/default/Phoenix-prettier/unittests.js, src/index.html, src/nls/root/strings.js, src/preferences/PreferencesImpl.js, src/preferences/StateManager.js, src/storage.js, src/styles/brackets.less, src/thirdparty/licences/credits.md, src/utils/Metrics.js, test/UnitTestSuite.js, test/spec/Document-integ-test.js, test/spec/SpecRunnerUtils.js, test/spec/prettier-test-files/js/test-pretty-8-indent.js, test/spec/space-detect-test-files/space-1.js, test/spec/space-detect-test-files/space-12.js, test/spec/space-detect-test-files/space-none.js, test/spec/space-detect-test-files/tab-12.js, test/spec/space-detect-test-files/tab-2.js, test/spec/spacing-auto-detect-integ-test.js
This will be the default mode. This can be toggled from the status bar by using the fixed/Auto toggle as shown below.
1. The auto detcted indents of each file can be overriden by manually entering the spacing and tab config as usual in the status bar. Those details will be persited for that file across reboots.
2. To recompute the tab spacing config for a file, just click on the `auto` toggle in status bar twice. (to change mode to fixed and back to auto will recompute the spacing for the current file). Not entirely intuitive, but should be a very rare use case and didnt wanted to complicate the ui with more options and dropdows like in other editors.
3. changing to fixed mode will set to fixed spaic across the system.
4. There is also a json preference available to toggle this setting: …
=> feat: auto tab spacing detection

src/LiveDevelopment/BrowserScripts/LivePreviewTransportRemote.js, src/extensionsIntegrated/Phoenix-live-preview/main.js, src/extensionsIntegrated/Phoenix-live-preview/markdown.html
reverting https://github.com/phcode-dev/phoenix/pull/1750 after latest tauri integration.
confirmed working in windows and linux where the patch was applied selectiveley.
Doesnt work in macos!! Last versions too isnt working, so this is not a regression in macos. Not sure why. https://discord.com/channels/616186924390023171/1258736272814374964
=> fix: remove alert patch as tauri fixed alert issue in windows

src/main.js
The crash dialog only used to say `something went wrong` in an alert dialog. This gave little option to anyone on how to fix. Improved the experience with more support options on crash.
Related to https://github.com/brackets-cont/brackets/issues/328
=> chore: new Boot time crash recovery dialog ux

src/index.html, src/main.js
Some linux distors doesnt appear to have appconfig dir in which case we cannot boot.
Related to https://github.com/brackets-cont/brackets/issues/328
=> chore: alert if app data directory canot be found as boot will fail

src/LiveDevelopment/BrowserScripts/LivePreviewTransportRemote.js, src/LiveDevelopment/MultiBrowserImpl/transports/LivePreviewTransport.js, src/nls/root/strings.js
address: https://github.com/orgs/phcode-dev/discussions/1734
=> fix: window.alert, confirm and prompt apis not present in embedded tauri mac live preview

src/brackets.js, src/nls/root/strings.js
Right now we just delete the preferences file if we detect a corrupt preference file.
Was planning to keep last known preference and revert to it, but only 19 users had the issue and one repeat user over the last 30 days on 32,000 total users. So the error rate is pretty low. Not worth effort.
In the future, with settings sync, this should be not an issue at all.
=> chore: corrupt preferences auto reset

src/phoenix/shell.js, src/utils/NodeUtils.js
Address False positive of Kaspersky detects phnode.exe and index.js as trojan horse https://github.com/phcode-dev/phoenix/issues/1821
Kaspersky is terating the background node process we use as a trojan horse if it opens a URL. We are onboarding to Kaspersky trusted applications program via kaspersky allowed lists to prevent this in the future. 
This is an interim mitigation for the time being.
Related desktop pr: https://github.com/phcode-dev/phoenix-desktop/pull/514
=> fix: kaspersky trojan horse false positive mitigation

src-node/node-connector.js
Fixes https://github.com/phcode-dev/phoenix/issues/1791
Node exited after sleep as web sockets gets disconnected at sleep, and our orphan exit timer will  inccorectly determine that too much time has passed including the time the app was asleep and terminated node.
We dont need orpahn exit timers anymore as node is terminated oon stdio disconnect, which is a much more reliable way to detect process exit. We did not remove this code at node connector as it maybe a miss during the algo change?
=> fix: node crashes after computer sleep

src/assets/default-project/en/Newly_added_features.md, src/extensionsIntegrated/DisplayShortcuts/templates/bottom-panel.html, src/htmlContent/about-dialog.html
=> chore: release note for v3.9 and hide vscode shortcut feature as its not ready yet

src/editor/Editor.js, src/editor/EditorHelper/EditorPreferences.js, test/spec/spacing-auto-detect-integ-test.js
**Summary:**
We've updated the behavior of the `Tab Size` setting in auto mode to address a misunderstanding in its implementation. Previously, we incorrectly equated the `Tab Size` with the number of tab characters used for indentation in a file. This has been corrected to reflect a more standard approach, ensuring a consistent and intuitive editing experience across various files.
**Detailed Explanation:**
The `Tab Size` setting determines the display width of a single tab character on the screen, not the number of tab characters used for indentation. In our previous approach, if a file was auto-detected to use two tab characters for indentation, we mistakenly set the `Tab Size` to 2. This interpretation was incorrect as `Tab Size` should define the width in spaces that a tab character …
=> Fix: auto spacing detection doesnt work reliabily

src/extensions/default/CSSCodeHints/css-lint.js, src/extensions/default/HTMLCodeHints/html-lint.js, src/extensions/default/JSLint/JSHint.js, src/extensionsIntegrated/appUpdater/main.js
The error happens as we load a lint extension in a web worker and phoenix calls the worker apis before the worker is loaded. This will eventually get resolved as teh worker gets loaded within a second of app load and another lint is trigerred on file change, but we get stray bugsnag errors for this expected error.
=> fix: bugsnag errors like Unknown exec function received htmlLint

.github/workflows/verify_cla_signature_pr.yml, src/extensibility/ExtensionManagerDialog.js, src/htmlContent/themes-settings.html, src/nls/root/strings.js, src/view/ThemeSettings.js
Added a `Get More...` button in themes dialog. Clicking it will open themes tab in Extension Manager dialog.
=> feat: get more themes button in themes dialog for discoverability

src/command/Commands.js, src/extensionsIntegrated/indentGuides/main.js, src/extensionsIntegrated/loader.js, src/nls/root/strings.js, src/preferences/StateManager.js, src/styles/brackets_codemirror_override.less, src/styles/images/indent-guide-line.svg, test/spec/Generic-integ-test.js
Also adds a editor preferences
```json
{
// true to show indent guide lines, else false.
"editor.indentGuides": true,
// true to show the first Indent Guide line else false.
"editor.indentHideFirst": false,
}
```
=> Feat: indent guides 

build/api-docs-generator.js, package.json, src/features/QuickViewManager.js, src/features/SelectionViewManager.js, src/utils/EventManager.js, src/utils/ExtensionInterface.js, src/utils/FeatureGate.js, src/utils/StringUtils.js, src/widgets/NotificationUI.js, src/worker/IndexingWorker.js
Changes :- 
1. Updated JavaScript files in the src directory to resolve compatibility issues with Docusaurus.
2. Modified package.json (Script can now be executed using the command :-
`npm run createMDDocs` )
3. Update the script to generate Markdown files from the source code.
=> Script to automatically generate Markdown API docs from source code.

src/worker/IndexingWorker.js, src/worker/WorkerComm.js
This PR makes the following changes :
1. In indexingWorker.js and workerComm.js, the jsdoc has import statements, so removing them as the script automatically adds import statements. 
2. The build failed issue on docs site was because of the link inside indexingWorker file. The link was supposed to lead to workerComm file, but was pointing to an invalid path.
=> Remove redundant import statements, and fix broken links

docs/API-Reference/worker/IndexingWorker.md
Fixed the invalid file path in previously generated API docs.
=> fix: broken links in previously generated API docs

src/extensionsIntegrated/NavigationAndHistory/FileRecovery.js
Adding basic integrity checks before we backup and restore files.
address: https://github.com/orgs/phcode-dev/discussions/1790#discussioncomment-10936845
part of https://github.com/phcode-dev/phoenix/issues/1885 and
=> chore: integrity checks for file recovery after crash

docs/API-Reference/command/Menus.md, src/command/Menus.js, src/extensionsIntegrated/Phoenix/guided-tour.js
The new doc infrastructure does not work the same as the old docs framework, so made the following changes:
1. All APIS declared `exports.*` is the public API and it should come in the docs.
2. All APIs starting with an _ is a private api, even if its exported, and added `@private` tag to make it not appear in API docs. 
3. Exported module EVENT_NAME constants should appear in docs.
4. ENUM declaration for exported named constants to appear in docs.
5. Some public APIs wont come up in docs if it doesnt have a jsdoc declaration, Eg. see `openMenu` api in this PR. so added a jsdoc section to missing public APIs to appear in docs.
=> docs: refine api docs of Menus

src/editor/EditorStatusBar.js, src/index.html, src/nls/root/strings.js, src/styles/brackets.less
* also added functionality so that on clicking the section, the goto line command is triggered now.
=> chore: move line:col status to right to accommodate plugin status bar tab panels

docs/API-Reference/document/Document.md, docs/API-Reference/document/DocumentManager.md, docs/API-Reference/document/TextRange.md, src/document/Document.js, src/document/DocumentManager.js, src/document/TextRange.js
Refine the API docs to remove the internal APIs from docs.
Also, now the `deprecated` methods are made `private`, So they don't appear in API docs.
=> docs: refine API docs for files in Document dir

docs/API-Reference/JSUtils/Preferences.md, docs/API-Reference/JSUtils/ScopeManager.md, docs/API-Reference/JSUtils/Session.md, src/JSUtils/Preferences.js, src/JSUtils/ScopeManager.js, src/JSUtils/Session.js
In file `ScopeManager.js`, the parameter definition has been updated like this:
<---- Removed ---->
* @param {from: {line:number, ch: number}, to: {line:number, ch: number}}
<---- Added ---->
* @param {{line:number, ch: number}} changeList {from: {line:number, ch: number}, to: {line:number, ch:number}}
This change was made because Docusaurus is unable to parse nested objects as parameter types.
=> docs: refine API docs for files in JSUtils dir

docs/API-Reference/editor/CodeHintManager.md, docs/API-Reference/editor/Editor.md, docs/API-Reference/editor/EditorCommandHandlers.md, docs/API-Reference/editor/EditorManager.md, src/editor/CodeHintManager.js, src/editor/Editor.js, src/editor/EditorCommandHandlers.js, src/editor/EditorManager.js
The following changes are made :
Removed CommandHandler.md from the API docs
– This file is removed from API docs, as this in an internal module.
Marked deprecated methods as `@private` in EditorManager.js
– The deprecated methods are now marked as `@private` to remove them from API docs,
Tweaked jsdoc style comments in Editor.js where required
– Changed `/** ... */` to `/* ... */` so they don’t show up in the API docs. Now, the comments stay in the code without cluttering the docs.
=> docs: refine API docs for files in Editor dir

docs/API-Reference/project/FileSyncManager.md, docs/API-Reference/project/FileTreeView.md, docs/API-Reference/project/FileTreeViewModel.md, docs/API-Reference/project/FileViewController.md, docs/API-Reference/project/ProjectManager.md, docs/API-Reference/project/ProjectModel.md, docs/API-Reference/project/SidebarView.md, docs/API-Reference/project/WorkingSetSort.md, docs/API-Reference/project/WorkingSetView.md, src/project/FileSyncManager.js, src/project/FileTreeView.js, src/project/FileTreeViewModel.js, src/project/FileViewController.js, src/project/ProjectManager.js, src/project/ProjectModel.js, src/project/SidebarView.js, src/project/WorkingSetSort.js, src/project/WorkingSetView.js
In ProjectManager.js and ProjectModel.js, JSDoc comments were missing for some constants that needed to be included in the API documentation. These have now been added.
In workingSetView.js, certain comments were written using /*...*/. These have been reformatted to /**...*/ to maintain consistency across the codebase.
=> docs: refine API docs for files in Project dir

src/extensibility/ExtensionManager.js, src/loggerSetup.js, test/spec/ExtensionManager-test.js
earlier, we used to cache the full uncompressed registry in ls which has a usual size limit of 5mb, and the
registry takes a few MB. So we moved this storage to file system. 
For migration, we will clear local storage on any existing installs on next update. The migration code `localStorage.removeItem(EXTENSION_REGISTRY_LOCAL_STORAGE_KEY);`  can be removed after July 2025(6 Months).
=> fix: extension manager not showing updated extensions due to local storage quota exceeded

src/editor/EditorStatusBar.js, src/index.html, src/nls/root/strings.js, src/phoenix/shell.js, src/styles/brackets.less, src/styles/brackets_core_ui_variables.less
For git integration:
Highlight js and related css for code coloring in markdown integrated for AI panel integration
=> feat: status bar icons initial scaffolding

.gitignore, gulpfile.js/thirdparty-lib-copy.js, src/extensibility/ExtensionManager.js, src/nls/root/strings.js
The extension registry (`extensions/registry/registry.json`), which is approximately 1.5MB in size, takes noticeable time to download, causing delays in the user experience. Users have reported frustration with this delay, particularly when opening the extension manager for the first time.
we have packaged a **local copy** of the registry in the `src/extensions/registry/` folder, to load extension manager instantly on the first launch, even if the online registry is still downloading. 
- **Behavior on First Launch**:
- The local copy of the registry is loaded to display extensions instantly. While this local registry may be outdated if the installer is old, it provides immediate functionality.
- **Updating the Registry**:
- When the user opens the extension manager, the application …
=> chore: extension registry embed in distributable for better first use UX

src/extensions/default/DarkTheme/main.less, src/styles/brackets_codemirror_override.less
=> fix: indent guides gaps when setting custom lineheight like 1.5

src/extensions/default/DebugCommands/MacroRunner.js, src/main.js, test/SpecRunner.js, test/spec/Generic-integ-test.js
Integration tests for the editor line height theme setting feature https://github.com/phcode-dev/phoenix/pull/1943
=> test: integ tests for line height theme setting

docs/API-Reference/editor/CodeHintManager.md, src/editor/CodeHintManager.js
Some jsdoc content were missing in API docs due to incorrect jsdoc syntax. Added it!
=> docs: add missing jsdoc

src/styles/brackets_codemirror_override.less
=> fix: split matching tags in light theme

src/extensionsIntegrated/CSSColorPreview/main.js
Now as soon as user toggles the preference to set it to false, the colors are automatically removed, the editor need not be focused. 
Also when user sets it to true, all the colors are added automatically.
=> Dynamically update colors when user toggles the preference

src/extensions/default/CodeFolding/main.less, src/extensionsIntegrated/CSSColorPreview/main.js, src/styles/Extn-CSSColorPreview.less, src/styles/brackets.less, test/spec/Editor-test.js
1. Refactor to not use cm gutter apis directly and use editor gutter apis
2. code folding gutter set its width to 1.1em above gutter width of 1em. this caused the gutter to render over the left most indent line or even cursor at the beginning of the line at certain sidebar widths! Note that this appears only at certain sidebar width and doesnt come in the default sidebar width. This is an issue in all existing builds. See image:
4. Address layout issues in the color gutter.
=> Moving the color gutter to right

src/extensionsIntegrated/CSSColorPreview/main.js
When the color icon button is clicked, the cursor is set to the color value and the quick edit option is toggled on/off.
=> Set cursor pos and opens quick edit when color icon is clicked

src/extensionsIntegrated/CSSColorPreview/main.js, src/styles/Extn-CSSColorPreview.less
1. On hover over the color box, we now zoom in for better visibility
2. individual color edit tracking.
[Screencast from 02-12-24 01:14:46 PM IST.webm](https://github.com/user-attachments/assets/02db3606-ff1d-4647-adbe-0c991f10a9e6)
=> chore: ux improvement for interacting with color gutter

docs/API-Reference/editor/CodeHintManager.md, docs/API-Reference/editor/Editor.md, src/editor/CodeHintManager.js
The docusaurus build fail issue coming from CodeHintManager file is fixed.
=> Fix: docusaurus build fail issue

.github/workflows/minor-version-bump.yml, .github/workflows/patch-version-bump.yml, .github/workflows/yearly-major-version-bump.yml, .husky/pre-push, src/extensions/default/DarkTheme/main.less, src/extensions/default/LightTheme/main.less, src/styles/brackets_codemirror_override.less
Fixes: https://www.reddit.com/r/brackets/comments/1h8dnb3/word_wrap_movement/
happened as we changed the line style to `inline-block` from the default for codemirror spans which is `inline` to enable continuous matching tag highlight. but that broke down word wrap which wont work properly in an inline-block context. so we moved to a border based impl.
=> fix: line jumps on cursor movement when word wrap is enabled

src/extensionsIntegrated/CSSColorPreview/main.js
The main problem is that it is hard for devs to visually see hex color values in text code. The color gutter addresses this to some extend but it is much eazier to associate the color to near where the text is in large boxes. Now the line is colored only on hover over the small color box, so it aligns with the user intent of wanting to see the color than to show colors on just cursor movement
https://github.com/phcode-dev/phoenix/pull/1979 was introduces to address this, but tracking this on every cursor movement was too jarring in a editing workflow and too distracting.
This is a variation of the inline color preview feature but with the in your face ux issues fixed. The color highlights on line now only comes if you hover over the color box. This is intuitive as the user deliberately …
=> feat: inline color preview on hover on the color box

docs/API-Reference/editor/Editor.md, src/extensionsIntegrated/CSSColorPreview/main.js, test/spec/CSSColorPreview-test-files/base.svg, test/spec/Extn-CSSColorPreview-integ-test.js
=> feat: svg color gutter previews

README.md, src/extensionsIntegrated/CSSColorPreview/main.js, src/extensionsIntegrated/RecentProjects/main.js, src/project/ProjectManager.js, test/spec/CSSColorPreview-test-files/base.css
1. If we switch project and path doesn't exist, then we used to switch to the default project which is not expected. Now if path doesn't exist, we show an error dialog and not switch from the current project.
2. Project error messages shown to user was virtual `/tauri` or `/fs` or `/mnt/`, ie vfs paths. Now we resolve to a user readable path.
3. update readme
4. also add sass variables test case in color gutter tests.
=> fix: ux issues in project open workflows when path doesnt exist

src/brackets.js, src/project/FileTreeView.js, src/widgets/bootstrap-dropdown.js
Fixes: https://github.com/orgs/phcode-dev/discussions/1993
This issue existed from our first desktop version released in Apr 2024 which used the safari engine. In the desktop app, we cant open context menus with `ctrl-click` on mac as it will get dismissed as soon as it opens.
This is a mac desktop and safari only issue with `ctrl-click` based context menu activation. Context menu activation with right mouse button click works as expected.
The issue happens only in safari as it treats `ctrl-click` based right click in mac differently:
- In Chrome, when you Cmd+Click, it treats it as a special context menu event and doesn't trigger the normal click handlers
- In Safari, Cmd+Click generates both a context menu event AND a regular click event, which triggers the clearMenus handler. The twin …
=> fix: ctrl-click in mac app and safari didnt open context menu

src/LiveDevelopment/BrowserScripts/LivePreviewTransportRemote.js
Fixes https://github.com/phcode-dev/phoenix/issues/1996
In tauri desktop builds, we tap into `<a>` tag clicks to open browser tabs with tauri api. But in some cases like in the referenced issue, we should not do that if the page programmatically handles the click. So added a check for that.
=> fix: clicking on prevent defaulted A tags in dekstop live preview opens browser tab

src/extensions/default/DarkTheme/main.less, src/extensions/default/LightTheme/main.less, src/search/FindBar.js, src/search/FindReplace.js, src/styles/brackets_codemirror_override.less, test/spec/FindInFiles-integ-test.js, test/spec/FindReplace-integ-test.js
fixes https://github.com/orgs/phcode-dev/discussions/1998
1. Addresses numerous UX issues with wind in files and find in a file.
1. fix bug where clicking on tag search match highlight makes it disappear due to matching tag styles black background overriding search highlight css styles.
=> fix: find in files and search ux issues

src/features/ParameterHintsManager.js, src/view/WorkspaceManager.js, test/spec/MainViewManager-integ-test.js
fixes https://github.com/orgs/phcode-dev/discussions/2001
=> fix: escape key toggles panels when code hints popup is present

src/extensionsIntegrated/RecentProjects/main.js, src/utils/DropdownEventHandler.js, src/widgets/PopUpManager.js
click on the project dropdown, then click on the langugae drop down in status bar. you can see that two dropdowns are simultaneously open. 
This happened as the add dropdown API did not clear existing dropdowns as that may not be needed all the time(and to prevent braking legacy extensions). So we now add a parameter to also dismiss exiting popups while adding a new popup.
=> fix: dropdowns doesnt close reliably and multiple dropdowns may come

src-node/utils.js, src/command/Commands.js, src/command/DefaultMenus.js, src/document/DocumentCommandHandlers.js, src/nls/root/strings.js, src/utils/NodeUtils.js
=> feat: add open in terminal, open in cmd and powershell feature

src-node/utils.js, src/command/Commands.js, src/command/DefaultMenus.js, src/document/DocumentCommandHandlers.js, src/nls/root/strings.js, src/utils/NodeUtils.js
Will be useful to open external binary files like pdf, videos, images etc..
=> feat: open in system default app in project and working set context menu

src/command/KeyBindingManager.js, test/spec/Keyboard-nav-integ-test.js
in Windows and Chrome (as well as most modern browsers), holding down a key like `Ctrl` will repeatedly fire the keydown event. The keydown event is triggered continuously while the key is pressed and held down. This behavior is called `keyboard auto-repeat`.
So this launched the ui overlay workflow accidentally. bad ux fix!
=> fix: accdental triple ctrlx3 press event in windows for ui overlay mode

src/command/Menus.js, test/spec/Menu-integ-test.js
This will be helpful for extensions which needs to know when certain menu items were added or removed to put in their menus and menu items at the correct position.
=> chore: raise events when menus, submenus and menu items are added

src/assets/new-project/code-editor.html, src/base-config/keyboard.json, src/extensionsIntegrated/RecentProjects/htmlContent/projects-menu.html, src/extensionsIntegrated/RecentProjects/main.js, src/nls/root/strings.js, src/styles/Extn-RecentProjects.less, src/widgets/PopUpManager.js, test/spec/Extn-RecentProjects-integ-test.js
Also removed private command `let TOGGLE_DROPDOWN = "recentProjects.toggle";` . verified that its only being used by one ancient(2014) recent 200 projects extension which has not been downloaded in years.
=> chore: simplilfy recent projects dropdown impl

src/extensionsIntegrated/NavigationAndHistory/main.js, src/styles/Extn-NavigationAndHistory.less
Adds an x button next to each file, visible on hover. Clicking the button removes the file from the Recent Files dialog.
Note: Files that are active in the 'Working Set' cannot be removed, as it would break the logic of Recent Files. The x icon is only displayed for files that are not part of the 'Working Set'.
* Dark Theme
https://github.com/user-attachments/assets/a898a942-6b8a-4558-9511-f39b8fdaffc2
* Light Theme
https://github.com/user-attachments/assets/bef9132b-d868-4c73-95a8-c1e461a497ee
=> Add functionality to remove specific files from Recent Files

src/extensionsIntegrated/NavigationAndHistory/main.js
In the 'Recent Files' dialog box, at the bottom left and in the tooltip for each file, the file path was previously displayed as a virtual path, containing segments like /mnt/ or /tauri/e. This is not the expected behaviour.
This issue is now resolved to show paths correctly.
=> fix: update virtual path before displaying in the UI

src/styles/brackets_core_ui_variables.less, src/styles/brackets_patterns_override.less
Introduces a lower warning style to be not as alarming. available if you apply the class `alert alert-warning` to the div.
observe the yellow alert banner
same as before
=> chore: alert divs styling for low warnings

gulpfile.js/index.js
```json
["CloseOthers", "CodeFolding", "DebugCommands", "Git",
"HealthData", "JavaScriptCodeHints", "JavaScriptRefactoring", "QuickView"]
```
```json
["CSSAtRuleCodeHints", "CSSCodeHints",
"CSSPseudoSelectorHints", "DarkTheme", "HandlebarsSupport", "HTMLCodeHints", "HtmlEntityCodeHints",
"InlineColorEditor", "InlineTimingFunctionEditor", "JavaScriptQuickEdit", "JSLint",
"LightTheme", "MDNDocs", "Phoenix-prettier", "PrefsCodeHints", "SVGCodeHints", "UrlCodeHints"
]
```
also added code to break build if any new extension is added in `defaultExtensions.json` list. they should be part of one of these list to pass build.
=> build: minify extensions framework

src/search/QuickOpen.js, test/spec/QuickOpen-integ-test.js
This update modifies the `Ctrl+G` "Go to Line" command to accept the `ln:col` format (e.g., `13:15`) in addition to the existing `line,col` format. 
Reason: The status bar shows the cursor position in the `ln:col` format since last release, replacing the earlier `line 13, column 15` format  to save space in the status bar. so for UX consistency we need to do this now.
https://discord.com/channels/879126209114542181/879126209554948116/1329280951188062209
=> feat: go to line will accept :ln:col format along with :ln,col

src/LiveDevelopment/LiveDevMultiBrowser.js, src/extensions/default/Git/src/GutterManager.js, src/extensions/default/Git/src/Panel.js, src/extensions/default/Git/src/Utils.js, src/extensions/default/Git/src/git/GitCli.js, src/extensions/default/Git/styles/git-styles.less, src/extensions/default/Git/templates/history-viewer.html
This was caused by fractional .7em rendering of git gutter. The css pixel approximation will hide
the 1px cursor line in certain window widths, so we should not use fractional em in the gutter.
if was to use a 1em gutter and set a fractional em inset border so that gutter width not fractional
also added hover style so that when user hovers over 1em gutter, it expands to 2 em to have
the user not work with needle threading precision to click git gutter. the green git-added-lines
gutter will not expand as there is currently no action associated with it.
=> fix: cursor not seen if line is empty and no git gutter marker in line in git projects

src/document/DocumentCommandHandlers.js, src/extensionsIntegrated/NavigationAndHistory/FileRecovery.js, src/extensionsIntegrated/Phoenix/html/new-project-template.html, src/styles/brackets.less, test/spec/Extn-NavigationAndHistory-integ-test.js
Following changes are done to file recovery logix:
1. We should not show file recovery dialog if the user selected dont save in when exiting phcode
2. Our integrity checks saves the file as `checksum,filecontent`. but if file content itself has a comma, our logic used to break due to improper `string.split(",")` usage
Defaulting to bigger size for new project dialog for small screens for better UX. The dialog is no longer re-sizable and gives the same ui experience in all screen sizes.
=> fix: file recovery not working if file has comma in it. don't save not be treated as crash, new project dialog size change

docs/02-List-of-Built-In-Libraries.md, src/extensions/default/HealthData/HealthDataManager.js, src/extensionsIntegrated/Phoenix/guided-tour.js, src/nls/root/strings.js, src/styles/brackets.less, src/utils/Metrics.js, src/widgets/NotificationUI.js
To improve UX, we need to not show blocking Dialog for surveys as we got feedback that its distracting.
See image for new survey UX. You can switch between dialog and notification from Back-end based on survey feedback for new ux.
=> new survey notification UX to not take user attention

src/assets/new-project/assets/css/style.css, src/extensions/default/Git/src/Panel.js, src/extensionsIntegrated/Phoenix/guided-tour.js, src/nls/root/strings.js, src/styles/brackets.less, src/styles/brackets_core_ui_variables.less, src/styles/brackets_patterns_override.less, src/widgets/NotificationUI.js
Also includes Better UI layout of notification bubbles and color changes.
=> chore: notification bubble ui changes. add git feature help bubble on first git panel show

src/assets/new-project/assets/css/style.css, src/assets/new-project/assets/js/code-editor.js, src/nls/root/strings.js
We got survey reports indicating people are confused about the default project. so giving more info in start time bubble.
=> chore: rephrase default project bubble note to better understand what it is about

src/extensions/default/Git/src/Branch.js, src/extensions/default/Git/src/Panel.js, src/extensions/default/Git/src/dialogs/Progress.js, src/extensions/default/Git/src/dialogs/Pull.js, src/extensions/default/Git/src/dialogs/Push.js, src/extensions/default/Git/src/dialogs/RemoteCommon.js, src/loggerSetup.js, src/nls/root/strings.js
The catch block was attached after a delay in some cases and errors before attaching the catch block in progress dialog used to get treated as uncaught exceptions and get logged in bugsnag fixed by modifying the timing chain and have a catch handler attached to promise at first itself.
=> fix: bugsnag errors in git workflows due to race conditions

src/extensions/default/Git/src/ErrorHandler.js, src/extensions/default/Git/src/Panel.js, src/nls/root/strings.js, src/styles/brackets.less, src/widgets/NotificationUI.js
expected errors in staging on click on the stage file/all checkbox in git panel should not be logged as error in bugsnag. Now its shown to user as error notification as the user needs to know the operation failed.
```
This usually happens hwen a git index is locked Eg. error.
Error: Error: fatal: Unable to create 'E:/.../test-git/.git/index.lock': File exists.
Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```
=> fix: bugsnag error logs in git when staging fails is an expected error

src/extensionsIntegrated/indentGuides/main.js, src/styles/brackets_codemirror_override.less
Users reported that deeply indented HTML elements caused misalignment between the text inside elements and their corresponding tags. The issue worsened as indentation depth increased, resulting in a noticeable shift of approximately **one or two spaces** at deep indentation levels.
Fixes https://github.com/orgs/phcode-dev/discussions/2108
Previously, the `.cm-phcode-indent-guides::before` selector was used to create indent guides via a `border-left`:
```css
.cm-phcode-indent-guides::before {
content: " ";
width: 1px;
display: inline-block;
position: relative;
border-left: 1px solid rgba(128, 128, 128, 0.3);
}
```
However, this approach **added a 1px tax per indentation level**, meaning that each additional indent slightly shifted the text outward. The cumulative effect of this offset …
=> fix: indent guides causes 1px drift in word wrapped lines

.gitignore, docs/API-Reference/widgets/NotificationUI.md, gulpfile.js/thirdparty-lib-copy.js, package-lock.json, package.json, src-node/package-lock.json, src/phoenix/shell.js, src/thirdparty/licences/emmet.markdown
The lib is now globally available via:
1. `Phoenix.libs.Emmet.expand` for the default exported main api and
2. `Phoenix.libs.Emmet.module` for all other apis in Emmet
=> build: add emmet into thirdparty libs. `Phoenix.libs.Emmet.expand` and `Phoenix.libs.Emmet.module`

src/brackets.js, src/extensions/default/CSSCodeHints/main.js, src/extensions/default/CSSCodeHints/unittests.js, src/extensions/default/HTMLCodeHints/emmet-snippets.js, src/extensions/default/HTMLCodeHints/main.js, src/extensions/default/HTMLCodeHints/unittests.js, src/nls/root/strings.js, src/preferences/AllPreferences.js, src/styles/brackets_core_ui_variables.less, src/styles/brackets_patterns_override.less, test/SpecRunner.js
NB: Full commit history in https://github.com/phcode-dev/phoenix/pull/2129 , this was re-raised as some rebase conflicts could not be fixed easily.
This PR adds built-in Emmet support to Phoenix.
* Displays code hints when an abbreviation can be expanded. (Code hints felt crucial—without them, most users might not realize that Phoenix supports Emmet by default.) A small "emmet" icon is shown at the bottom-right of the hint to indicate that the hint is coming from Emmet.
* Places the cursor at the correct position after expansion, in a manner that users can directly start typing.
* Preserves indentation to match the surrounding code.
* Users can enable/disable from preferences file.
https://github.com/user-attachments/assets/546c62fe-36fc-4227-a50f-e443daad3bb3
=> Emmet Integration

src/search/FindReplace.js, src/search/ScrollTrackMarkers.js, test/spec/FindReplace-integ-test.js, test/spec/ScrollTrackHandler-integ-test.js
=> chore: visually show adjucent line git marks for add/del/change as a single scroll line

src/extensibility/ExtensionManager.js, src/file/FileUtils.js, src/filesystem/File.js, src/filesystem/impls/appshell/AppshellFileSystem.js
Looks like we have bricked a lot of installations from updating the extension registry. This will only get fixed in the next release, till then, if users cached the corrupted registry, the users wont be able to get extension updates!
=> fix: extension registry not getting updated

src/extensions/default/CSSCodeHints/main.js, src/extensions/default/DefaultExtensions.json, src/extensions/default/HTMLCodeHints/main.js
=> chore: add emmet metrics and minor refactor

src/extensions/default/CSSCodeHints/main.js, test/spec/LiveDevelopmentMultiBrowser-test.js
Previously used colors within a file will be prioritized in the color hint suggestions. These colors will be sorted in descending order based on their frequency of occurrence, ensuring that the most frequently used color appears at the top. This prioritization happens before displaying any other color hints.
Works for all color types. (hex, rgb, named colors)
=> feat: suggest previously used colors in file

src/extensions/default/HTMLCodeHints/main.js, src/extensions/default/HTMLCodeHints/unittests.js, src/styles/brackets_patterns_override.less
Now emmet can expand 'lorem' text in html 
https://github.com/user-attachments/assets/e7495fb5-74f8-4411-8b9b-6542ba30f9f5
=> feat: add lorem support in emmet-html

test/spec/Tauri-platform-test.js
tests for https://github.com/phcode-dev/phoenix-desktop/pull/598
=> test: unit tests for tauri credentials totp store apis

docs/API-Reference/command/Commands.md, src/command/Commands.js, src/extensions/default/Phoenix-prettier/unittests.js, src/extensionsIntegrated/TabBar/drag-drop.js, src/extensionsIntegrated/TabBar/global.js, src/extensionsIntegrated/TabBar/helper.js, src/extensionsIntegrated/TabBar/html/tabbar-pane.html, src/extensionsIntegrated/TabBar/html/tabbar-second-pane.html, src/extensionsIntegrated/TabBar/main.js, src/extensionsIntegrated/TabBar/more-options.js, src/extensionsIntegrated/TabBar/overflow.js, src/extensionsIntegrated/TabBar/preference.js, src/extensionsIntegrated/loader.js, src/nls/root/strings.js, src/styles/Extn-TabBar.less, src/styles/brackets.less
https://github.com/user-attachments/assets/10c09e55-e81c-4053-8e0a-b7ed121dbfc0
=> TabBar Integration

src/extensionsIntegrated/TabBar/drag-drop.js, src/extensionsIntegrated/TabBar/main.js, src/extensionsIntegrated/TabBar/overflow.js, src/styles/Extn-TabBar.less
This PR does the following changes:
1. Allow dragging between panes. 
2. Moving the mouse wheel now scrolls the tab bar.
3. Increase the scroll speed for tab bar.
4. Improved styling.
=> Allow dragging tabs between panes and improved tab bar scrolling functionality

src/extensionsIntegrated/TabBar/more-options.js, src/extensionsIntegrated/TabBar/overflow.js, src/nls/root/strings.js
Now when a tab is right clicked, along with other options we show two options i.e. close tabs to the right of the _right-clicked_ tab and the left of the _right-clicked_ tab.
=> feat: add support for closing tabs to right & left in context menu

src/extensionsIntegrated/TabBar/main.js, src/extensionsIntegrated/TabBar/overflow.js, src/styles/Extn-TabBar.less
When a file is opened from the file tree but is not added to the working set, a temporary placeholder tab is created in the tab bar. This tab is styled differently from regular tabs to make it visually distinct. 
Clicking on the placeholder tab adds it to the working set.
Visual Reference :-
https://github.com/user-attachments/assets/a4360f5c-ac4c-45a5-88ea-4a1e142931e1
=> Add placeholder tab when a file is opened from file tree but not yet added to working set

package-lock.json, src-node/package-lock.json, src/extensions/default/Git/main.js, src/extensions/default/Git/src/TabBarIntegration.js, src/extensionsIntegrated/TabBar/drag-drop.js, src/extensionsIntegrated/TabBar/main.js, src/extensionsIntegrated/TabBar/more-options.js, src/nls/root/strings.js, src/styles/Extn-TabBar.less
1. Reserve space for dirty icon always to prevent tabs shift when a file is modified/saved.
**Before**
https://github.com/user-attachments/assets/50ff6184-081f-4bfe-82b1-facbb1c83ade
**After**
https://github.com/user-attachments/assets/5ed7b0c4-bd4a-4eae-b53c-7c15ec2d9e74
2. Add option to rename, delete file and show in file tree in the tab context menu
3. Made drag-drop scroll smoother
4. Currently active tab is always shown on the tab bar even if user manually sets a number in the numberOfTabs preference option
5. Fix: Now, we show the display path when a tab is hovered instead of the tauri path
6. We also show the git change markers in the tab to visually identify the tab that is added/modified
=> fix: tab bar bug fixes and improvements

src/command/Commands.js, src/command/DefaultMenus.js, src/nls/root/strings.js, src/project/SidebarView.js, src/styles/brackets.less
**Visual Reference**
https://github.com/user-attachments/assets/d11d67e0-f144-4674-acab-e4726327bdaf
=> Add option in sidebar to toggle the visibility of working set and tab bar

src/extensionsIntegrated/Phoenix/html/login-dialog.html, src/extensionsIntegrated/Phoenix/html/profile-panel.html, src/extensionsIntegrated/Phoenix/profile-menu.js, src/styles/Extn-UserProfile.less, src/styles/brackets.less
**Visual Reference**
https://github.com/user-attachments/assets/f3004f0c-8cab-4878-a378-db14a0cdf370
=> Refactor the UI of the user profile popup

docs/API-Reference/command/Commands.md, src/extensionsIntegrated/Phoenix/html/login-dialog.html, src/extensionsIntegrated/Phoenix/html/profile-panel.html, src/styles/Extn-UserProfile.less, src/styles/brackets.less
This PR does the following 2 changes:
1. Reduced the size of the profile icon on the toolbar to make it consistent with other buttons.
2. Made the contact support button similar in both the sign in and the profile popup.
**Visual reference**
=> Refactor styling for profile page

docs/API-Reference/command/Commands.md, src/extensionsIntegrated/TabBar/drag-drop.js, src/styles/Extn-TabBar.less
This PR does the following changes:
1st Commit:- Earlier it was not possible to drop a dragged tab over the editor area. This commit fixes that issue. Now users can drag a tab from one pane and drop it in the editor area of the other pane and the tab successfully gets placed.
2nd Commit:- When a tab was dragged from one pane to the other pane, the dragged tab now becomes active. Earlier it was not possible.
3rd Commit:- Earlier, after dragging dropping tabs, sometimes tab bar becomes unresponsive. this was because _registerHandlers was not attaching all the events properly. fixed that.
4th commit:- Just updated the pane border styling.
5th commit:- Sometimes when a tab was dragged from one pane to other pane, then a placeholder(temporary tab) used to appear on the first pane from where …
=> Fix tab bar drag-drop issues in between panes

src/extensions/default/HTMLCodeHints/main.js, src/styles/brackets_patterns_override.less
This PR does the following 2 fixes. Refer to https://github.com/phcode-dev/phoenix/issues/2269
1st commit: The Emmet icon in HTML and Stylesheet files are a bit different. Updated the Emmet icon to look same in both the files for consistency.
2nd commit: In very large emmet abbreviations the code hints can get extremely large covering the whole screen space. Gave it a max-width so that it doesn't cover up the whole screen space.
**Before**
**After**
=> Fixed UI issues with emmet code hints in HTML files

src/document/DocumentCommandHandlers.js, src/index.html, src/phoenix/shell.js, src/phoenix/trust_ring.js, src/utils/ExtensionLoader.js, test/spec/Tauri-platform-test.js
related dekstop app APIS: https://github.com/phcode-dev/phoenix-desktop/pull/635
KernalModeTrust is a security mechanism in Phoenix that provides a trust base for core components before any extensions
are loaded. It establishes a secure communication channel between core modules and the Tauri shell, preventing
unauthorized access to sensitive information by extensions or other potentially malicious code.
The primary purposes of KernalModeTrust are:
1. **Secure Boot Process**: Ensures that the application can only boot with a properly initialized trust ring.
2. **Secure Communication**: Enables core modules to communicate securely without worrying about interception by
extensions.
3. **API Key Management**: Provides secure storage and retrieval of Phoenix API keys.
4. **Security …
=> feat: add framework for KernalModeTrust to secure core modules from extensions

src/editor/Editor.js
Scroll horizontally when mouse wheel is scrolled along with `Shift` key press. 
**Visual reference**
https://github.com/user-attachments/assets/a55e2cbe-4e5d-4bbe-adec-59441741dca0
=> Horizontall scrolling on shift + mouse wheel scroll

src/nls/root/strings.js, src/services/html/otp-dialog.html, src/services/login.js
=> chore: add a check login status button on login otp screen

src/extensions/default/Git/styles/git-styles.less, src/extensionsIntegrated/CollapseFolders/main.js, src/extensionsIntegrated/loader.js, src/styles/Extn-CollapseFolders.less, src/styles/brackets.less, test/UnitTestSuite.js, test/spec/Extn-CollapseFolders-integ-test.js
This PR adds a 'Collapse' button in the sidebar area, specifically 'project-files-header' section.
this button when clicked closes all the opened folders recursively. it is really useful to keep things organized.
Now, to keep the UI simpler, we hide the button by default and only show it when the sidebar area is hovered. 
Issue reference: https://github.com/phcode-dev/phoenix/issues/2126
**Visual Reference**
https://github.com/user-attachments/assets/968a871d-9a17-4d85-838f-81b850b775b4
=> [FEAT] A collapse button in the sidebar which when clicked closes all the open folders

src/styles/Extn-TabBar.less
=> fix: tab icon colors in light theme

src/extensions/default/Git/src/Main.js, src/extensions/default/Git/src/git/GitCli.js
This PR fixes the issue of git panel not getting updated properly when changes were made from external sources.
**Before**
Earlier, we had a 5seconds of focus switch dedupe time. The problem with this was that if user switch from the external source to Phoenix very quickly (maybe right after executing the command) then we were not refreshing the Git as it had a timer. Secondly, the hasStatusChanged only tracked for commit changes, and not the push/pull and other changes, that also prevented the panel to update when needed.
**After**
Now, when Phoenix gains focus, we check if the git panel is open. If its open it likely means that user performed some git changes externally, so we refresh the git panel. But if the git panel is not open, we just refresh the branch. This approach makes sure …
=> Git panel not getting updated when phoenix gains focus

src/editor/Editor.js
fixes: https://github.com/orgs/phcode-dev/discussions/2354
in safari there was a ghost image when dragging text:
[Screencast from 25-08-25 04:21:01 PM IST.webm](https://github.com/user-attachments/assets/2be1656d-6309-4abd-806c-7d7e78f79c31)
=> fix: safari code mirror drag creates ghost image

serve-proxy.js, src/services/html/profile-popup.html, src/services/login-browser.js, src/services/login-desktop.js, src/services/profile-menu.js, src/services/readme-login-browser-no_dist.md
Implement iframe integration to display full user details securely in browser profile
popup, avoiding masked data exposure to extensions. Adds consistent getAccountBaseURL
API across both login services and proper proxy URL handling for localhost development.
=> Feat: add secure iframe user details for browser login 

test/BootstrapReporterView.js, test/SpecRunner.js, test/UnitTestReporter.js
* Increased `awaitsFor` API poll interval from **20ms → 30ms** to improve test stability.
* Only minor variations in performance observed.
**Desktop App Integration Tests**
* 25ms → `5m:20s`
* 30ms → `5m:10s` (Run 1), `4m:48s` (Run 2)
**Browser App Unit Tests**
* 10ms → `1m:56s`, `1m:59s`
* 20ms → `2m:01s`, `2m:00s`, `1m:59s`
* 50ms → `2m:02s`, `2m:04s`
* **Improved stability** with negligible impact on runtime.
* Chosen interval: **30ms** for integration tests, balancing consistency and performance.
=> chore: improved UX for test runner and increase `awaitsFor` poll interval

src/LiveDevelopment/LivePreviewEdit.js
and continue with phoenix ai dialog
=> chore: ai wire in from live preview for disabled dialogs
