src/filesystem/impls/appshell/AppshellFileSystem.js
src/index-web.html
src/index.html
src/nls/bg/urls.js
src/nls/cs/urls.js
src/nls/da/urls.js
src/nls/de/urls.js
src/nls/el/urls.js
src/nls/es/urls.js
src/nls/fa-ir/urls.js
src/nls/fi/urls.js
src/nls/fr/urls.js
src/nls/id/urls.js
src/nls/it/urls.js
src/nls/ja/urls.js
src/nls/ko/urls.js
src/nls/nl/urls.js
src/nls/pl/urls.js
src/nls/pt-br/urls.js
src/nls/pt-pt/urls.js
src/nls/root/urls.js
src/nls/ru/urls.js
src/nls/sv/urls.js
src/nls/uk/urls.js
src/nls/zh-cn/urls.js
src/nls/zh-tw/urls.js
src/phoenix/init_vfs.js
src/project/ProjectManager.js
test/SpecRunner.html

- Remove getting started project urls. https://github.com/aicore/phoenix/issues/22
- Setting up trash folder.
- Load Phoenix from a web server instead of file:/// URL https://github.com/aicore/phoenix/issues/24

Load Phoenix from a web server instead of file url

---

src/filesystem/impls/appshell/AppshellFileSystem.js
src/index-web.html
src/phoenix/init_vfs.js
src/phoenix/shell.js
src/project/ProjectManager.js
src/utils/Global.js

https://github.com/aicore/phoenix/issues/11

Phoenix app shel enable. Works in browsers with this change now.

---

src/phoenix/errno.js
src/phoenix/shell.js

* This is to enable phoenix vfs error code decoding as phoenix vfs complies with node error codes.
https://github.com/aicore/phoenix/issues/11

Adding Node Error code decode logic.

---

src/phoenix/errno.js

Node compatible fs error message utility lib 
https://github.com/aicore/phoenix/issues/22

fs lib error message decode utils 

---

src/filesystem/impls/appshell/AppshellFileSystem.js
src/phoenix/errno.js
src/phoenix/shell.js

- fs lib error message decode utils 
- Wiring appshell fs into filer 
https://github.com/aicore/phoenix/issues/22

Wiring appshell fs into filer

---

src/file/FileUtils.js
src/filesystem/impls/appshell/AppshellFileSystem.js
src/phoenix/init_vfs.js
src/phoenix/shell.js

- Patching fs to include recursive directory create function fs.mkdirs. ACK: https://github.com/bpedro/node-fs
- Adding filer path utils to global context.
- Enabling recursive directory creation in app shell file system.
- Phoenix native directory will now point to the window base URL instead of from file system.

improved pheonix vfs handling

---

src/brackets.js
src/phoenix/shell.js

Part of https://github.com/aicore/phoenix/issues/11

Adding openURLInDefaultBrowser phoenix shell command.

---

src/document/DocumentCommandHandlers.js

Tested in phoenix web/chrome.
part of: https://github.com/aicore/phoenix/issues/11

new file will always create a new file in project.

---

src/command/DefaultMenus.js
src/project/ProjectManager.js

- new file will always create a new file in project.
- file>new folder will create new folder in project, open folder support message.

newFile/folder workflows. 

---

src/command/DefaultMenus.js
src/extensibility/ExtensionManagerDialog.js

- Removing file>quit menu 
- extension manager under development message.

quit and extension manager ui update.

---

src/LiveDevelopment/main.js
src/command/DefaultMenus.js

- Live preview coming soon messaging. 
- https://github.com/aicore/phoenix/issues/29

Live preview coming soon messaging

---

README.md

* beautifying hyperlinks for Github pages.

Update phoenix links for github pages

---

package.json

Feature to be reinstated as part of:  https://github.com/aicore/phoenix/issues/86

Remove prepush lint checks to modernise node 

---

src/extensions/default/CSSAtRuleCodeHints/package.json
src/extensions/default/CSSCodeHints/package.json
src/extensions/default/CSSPseudoSelectorHints/package.json
src/extensions/default/CloseOthers/package.json
src/extensions/default/DebugCommands/package.json
src/extensions/default/HTMLCodeHints/package.json
src/extensions/default/HandlebarsSupport/package.json
src/extensions/default/HtmlEntityCodeHints/package.json
src/extensions/default/InAppNotifications/package.json
src/extensions/default/InlineColorEditor/package.json
src/extensions/default/InlineTimingFunctionEditor/package.json
src/extensions/default/JSLint/package.json
src/extensions/default/JavaScriptQuickEdit/package.json
src/extensions/default/JavaScriptRefactoring/package.json
src/extensions/default/LESSSupport/package.json
src/extensions/default/MDNDocs/package.json
src/extensions/default/NavigationAndHistory/package.json
src/extensions/default/NoDistractions/package.json
src/extensions/default/PrefsCodeHints/package.json
src/extensions/default/QuickOpenCSS/package.json
src/extensions/default/QuickOpenHTML/package.json
src/extensions/default/QuickOpenJavaScript/package.json
src/extensions/default/QuickView/package.json
src/extensions/default/RecentProjects/package.json
src/extensions/default/RemoteFileAdapter/package.json
src/extensions/default/SVGCodeHints/package.json
src/extensions/default/UrlCodeHints/package.json
src/package-lock.json

error loggings due to missing package.json is removed.
with reference to closed PR #107

package.json files added, removing 404 error loggings in console

---

src/phoenix/init_vfs.js

Adding more context on features to default welcome project.

Helpful welcome messaging in intro project 

---

src/project/FileTreeView.js

* Performance improvement of file tree: select file on mouse down event instead of click.
* +20 hp +20 armour +20 skill for files
* no change for folders.

Performance improvement of file tree 

---

src/editor/ImageViewer.js
src/extensions/default/QuickView/main.js
src/features/FindReferencesManager.js
src/file/FileUtils.js
src/filesystem/File.js
src/phoenix/fslib.js
src/phoenix/fslib_native.js
src/phoenix/init_vfs.js
src/search/QuickOpen.js

- Bug fix: image previews not working.& Binary file handling. 
- Bug fix: image previews not working on html popups. 
https://github.com/aicore/phoenix/issues/96

Bug fix: image previews not working

---

src/extensions/default/QuickView/main.js

remove image load error in console.
https://github.com/aicore/phoenix/issues/96

remove image load error in console 

---

src/extensions/default/DebugCommands/main.js

Enable run tests in debug menu 

Enable run tests in debug menu 

---

test/SpecRunner.html
test/spec/LowLevelFileIO-test.js
test/spec/SpecRunnerUtils.js

* More unit tests working. 
* Removed chmod from tests as it is not relevant in phoenix vfs 

More unit tests working. Removed chmod from tests as it is not relevant in phoenix vfs https://github.com/aicore/phoenix/issues/91

---

.husky/commit-msg
.husky/pre-commit
.husky/pre-push
README.md
package-lock.json
package.json
src/editor/ImageViewer.js
src/extensions/default/QuickView/main.js

- Fix eslint errors
- Removed idb from deps as it is integrated in src in thirdparty folder. Dynamic dep management will later take care of these deps.
- Setup lint/build before commit/push git. Git commit message lint https://github.com/aicore/phoenix/issues/86
- build: git commit lint https://github.com/aicore/phoenix/issues/86

Auto lint and git commit/push hooks for build/text

---

.github/workflows/build_verify.yml
.husky/pre-push
package.json

ci: adding build tasks - github action build/test on pull request and push to main branch
https://github.com/aicore/phoenix/issues/86

ci: adding build tasks 

---

.eslintrc.js
.husky/pre-push
gulpfile.js/index.js
package-lock.json
package.json

build: integrating gulp build 
https://github.com/aicore/phoenix/issues/223

build: integrating gulp build https://github.com/aicore/phoenix/issues/223

---

README.md
gulpfile.js/index.js
package-lock.json
package.json

build: npm run clean script and doc update 
https://github.com/aicore/phoenix/issues/223

build: npm run clean script and doc update

---

README.md
gulpfile.js/index.js
package-lock.json
package.json

build: npm server scripts and doc update 
* run `npm run srve` in the terminal.
* NB: To test Phoenix from an external mobile or machine, use `npm run serveExternal` instead of `serve`   
* Use chrome/edge browser to navigate to [http://localhost:8000/src/index.html](http://localhost:8000/src/index.html)
https://github.com/aicore/phoenix/issues/223

build: npm server scripts and doc update 

---

gulpfile.js/index.js
package-lock.json
package.json
src/index.html

build: npm release scripts and doc update 
TODO: The actual release scripts that are not written, only a no-op release command dummy has been enabled.
https://github.com/aicore/phoenix/issues/223
https://github.com/aicore/phoenix/issues/94

build: npm release scripts and doc update 

---

.gitignore
gulpfile.js/index.js
package-lock.json
package.json
src/thirdparty/jszip-utils.js
src/thirdparty/licences/jsZip.markdown
test/SpecRunner.html
test/SpecRunner.js

* Add jszip for compressing and uncompressing zip files.
* Infrastructure to copy third party deps
* https://github.com/aicore/phoenix/issues/91
* https://github.com/aicore/phoenix/issues/10

test: adding unzip utils for test folder compression in tests 

---

README.md
test/SpecRunner.html
test/SpecRunner.js

- test: helpful messaging when starting tests and when there are failures.
- docs: clean build commands 
- https://github.com/aicore/phoenix/issues/91

Docs and helpful messaging for running tests

---

.sonarcloud.properties

ci: sonar cloud code quality checks 
https://github.com/aicore/phoenix/issues/108

ci: sonar cloud code quality checks 

---

.github/workflows/codeql-analysis.yml

integrate with codeql analysis for security

---

README.md
src/extensions/default/HealthData/package.json
src/phoenix/shell.js

- fix: add extension default config files to prevent console error messages
- docs: add IDE setup for sonar lint instructions
- fix: add missing getElapsedMilliseconds API. Unit Tests pass now at 108 from 200

More unit test fixes

---

src/phoenix/filerlib_copy.js
src/phoenix/fslib.js
src/phoenix/fslib_mounts.js
src/phoenix/fslib_native.js
src/phoenix/init_vfs.js
src/phoenix/shell.js
test/SpecRunner.js
test/spec/LowLevelFileIO-test.js
test/spec/SpecRunnerUtils.js

LowLevel file io unit tests passing

LowLevel file io unit tests passing

---

test/SpecRunner.html
test/spec/SpecRunnerUtils.js

- fix: basic integration test framework working
- fix: remove no-host server as we are moving to phoenix server and nohost server is failing

basic integration test framework working

---

README.md
src/utils/ExtensionLoader.js

- docs: how to browse the virtual file system
- fix: reload without user extensions working

fix: reload without user extensions working

---

src/command/DefaultMenus.js
src/document/DocumentCommandHandlers.js
src/languageTools/ClientLoader.js

fix: all find replace integration tests working
The tests failed as we changed file>new behavior earlier to open the file in project as default. WE changed the menu item entry instead in this fix and reinstated the old impl for find replace

All find replace integration tests working 

---

test/spec/MainViewManager-test.js
test/spec/SpecRunnerUtils.js

fix: mainViewmanager integration tests doesn't crash anymore 

fix: mainViewmanager integration tests doesn't crash anymore 

---

src/extensions/default/CloseOthers/unittests.js
src/utils/ExtensionLoader.js
test/SpecRunner.js

fix: extension unit and integration tests working 

fix: extension unit and integration tests working

---

test/SpecRunner.js

* fix: only load extension tests if extension suite is selected
* Other Sonar lint fixes

fix: only load extension tests if extension suite is selected

---

src/thirdparty/requirejs/require.js

chore: update requirejs to latest 

chore: update requirejs to latest 

---

src/main.js
src/thirdparty/requirejs/amd-loader.js
src/thirdparty/requirejs/extension-loader.js
src/utils/ExtensionLoader.js
src/utils/ExtensionUtils.js

- fix: requirejs extension loader from virtual fs working 
- https://github.com/aicore/phoenix/issues/91
- Verified code folding extension loaded from Dev and User dir
- Verified Less styles are loaded
- To Verify if CSS files in extensions are properly loaded.

Extension load from virtual FS working

---

src/extensions/default/DebugCommands/keyboard.json
src/extensions/default/DebugCommands/main.js
src/main.js

- fix: switch language working ![language switch](https://user-images.githubusercontent.com/5336369/147556407-afe5350a-eb65-4af5-b746-6d137cf97c2b.gif)
- feat: auto-detect system language for phoenix ![system language](https://user-images.githubusercontent.com/5336369/147556476-8f3f4fd5-38ee-41c6-9681-0d7f2c951082.gif)
- chore: remove showDeveloperTools option as it is not supported in the browser
- Fixes: https://github.com/aicore/phoenix/issues/141

Auto Language switch based on user pref, overrides

---

src/command/DefaultMenus.js
src/extensions/default/HealthData/main.js

Help menu prettify

---

src/extensions/default/NavigationAndHistory/NavigationProvider.js
src/htmlContent/main-view.html
src/styles/brackets.less
src/styles/images/select-triangles.svg
src/styles/images/sprites.svg

- feat: adding forward and backward nav button UI
- feat: forward and backward nav button initial
- feat: forward and backward nav button fixes
* Back and forward navigation not working as expected even before. We need to fix the root cause of bugs.

adding forward and backward nav button UI

---

.gitignore
gulpfile.js/index.js
package-lock.json
package.json
src/extensions/default/NavigationAndHistory/NavigationProvider.js
src/index.html
src/styles/brackets.less
test/SpecRunner.html

- feat: navigation button disable/enable
- feat: navigation flow fixes
- feat: navigation flow fixes
- feat: integrate underscore library
- fix: navigation between files except nav within file working

navigation between files except nav within file working

---

src/extensions/default/NavigationAndHistory/NavigationProvider.js

- fix: navigation within files working initial
* Open a project. Double click on a word to select
* Click on back button, the back button is not disabled even after the last back nav is done.
* fix in progress

navigation within files working initial

---

src/extensions/default/NavigationAndHistory/NavigationProvider.js

- feat: shift-click to navigate to previous file skipping current file nav points
- - fix: navigation was failing as the start and end pos was inverted and compares failed

shift-click to navigate to previous file skipping current file nav points

---

src/extensions/default/NavigationAndHistory/NavigationProvider.js
src/styles/brackets.less
src/styles/images/sprites.svg

* Adding search button in nav bar for find in files

Search nav button for find in files

---

src/extensions/default/NavigationAndHistory/NavigationProvider.js

* Right-click forward and reverse nav buttons to nav to prev/next file skipping the changes in the current file.
* This helps if you want to fast forward to prev/next file skipping a lot of changes made in the current file.

Right click forward and reverse nav buttons to nav to prev/next file

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/custom.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE/bug_fix.md
.github/PULL_REQUEST_TEMPLATE/new_feature.md
.github/PULL_REQUEST_TEMPLATE/remove_feature.md

Add GitHub issue and pull request template

ci: add github templates

---

src/extensions/default/DefaultExtensions.json
src/extensions/default/Phoenix/main.js
src/extensions/default/Phoenix/package.json
src/htmlContent/main-view.html
src/styles/brackets_patterns_override.less

- feat: survey monkey feedback after 30 seconds
- - feat: add plugin panel styles and div, a new toolbar panel to the right just for plugins scaffolding

survey monkey feedback after 30 seconds

---

src/htmlContent/main-view.html
src/styles/brackets_patterns_override.less

- fix: ui layout issues with bottom toolbar buttons
- fix: ui fine tuning

UI fine tuning for toolbar button

---

src/htmlContent/main-view.html
src/styles/brackets_core_ui_variables.less
src/styles/brackets_patterns_override.less
src/view/PluginPanelManager.js
src/view/WorkspaceManager.js

- fix: ui resize bug where the main-toolbar disappears when plugin panel with content get minimised
- feat: add PluginPanelManager
- feat: plugin panel scaffolding

plugin panel scaffolding

---

README.md

a minor change in readme.md

---

src/extensions/default/Phoenix-Markdown/main.js
src/utils/Resizer.js
src/view/PanelView.js
src/view/WorkspaceManager.js

* Refactor out panel view from workspace manager to share with plugin panel
* Change min-height of markdown panel to 300 as 650 takes too much space.
* No change in UT pass/fail.

chore: refactor out panel view from workspace manager to share with plugin panel

---

src/extensions/default/Phoenix-extension-store/main.js
src/htmlContent/main-view.html

See `experimental build` text at top right

feat: inform users of experimental build

---

src/extensions/default/Phoenix-live-preview/extension-store.css
src/extensions/default/Phoenix-live-preview/panel.html
src/extensions/default/Phoenix/serverSync.js

Live preview infra updates

---

src/LiveDevelopment/main.js
src/extensions/default/Phoenix-live-preview/panel.html
src/extensions/default/Phoenix-live-preview/utils.js

* This is not exactly live preview, the page reloads on every save.

feat: limited live preview enable for user testing

---

package.json
src/extensions/default/Phoenix/new-project.js
test/spec/FeatureGate-test.js

* This is required to run tests that are served from the test folder
* Also a minor cleanup in feature gate tests

chore: move http-server to serve from root dir instead of src

---

src/extensions/default/Phoenix-live-preview/extension-store.css
src/extensions/default/Phoenix-live-preview/main.js

feat: remember scroll positions on live preview and reduce flicker

---

src/assets/phoenix-splash/index.html
src/brackets.js
src/index.html
src/main.js
src/phoenix/shell.js

- feat: splash screen interactive load time messaging
- chore: more error handling and logging
- chore: fix sonar lint issues
- chore: helpful code comments

splash screen updates and interactivity

---

src/assets/phoenix-splash/no-preview.html
src/extensions/default/Phoenix-live-preview/main.js
src/extensions/default/Phoenix-live-preview/panel.html
src/nls/root/strings.js

- feat: live preview update title with file name
- fix: sonar lint fix

 feat: live preview update title with file name

---

src/extensions/default/Phoenix-live-preview/images/sprites.svg
src/extensions/default/Phoenix-live-preview/live-preview.css
src/extensions/default/Phoenix-live-preview/main.js
src/extensions/default/Phoenix-live-preview/panel.html

user will now be able to lock a live preview url, while he edits other html/related files

feat: adding pin url for live preview

---

src/extensions/default/Phoenix-live-preview/main.js
src/extensions/default/Phoenix-live-preview/panel.html

live preview outside of the phoenix code editor with real time sync
within the browser

feat: live preview popout to a new tab

---

src/extensions/default/Phoenix-live-preview/main.js
src/extensions/default/Phoenix/serverSync.js

- chore: unpin a live preview url on project change if pinned
- chore: remove incremental server sync on share

remove incremental server sync on share

---

src/LiveDevelopment/main.js
src/command/DefaultMenus.js
src/extensions/default/Phoenix-live-preview/main.js

chore: wiring in live preview shortcuts and menu items

---

src/assets/default-project/en/index.html
src/extensions/default/Phoenix/main.js
src/extensions/default/Phoenix/new-project.js
src/extensions/default/Phoenix/serverSync.js
src/extensions/default/Phoenix/startup-project.js
src/extensions/default/Phoenix/survey.js
src/phoenix/init_vfs.js
src/project/ProjectManager.js
src/styles/brackets_variables.less

- feat: download default zip project on first boot
- chore: increasing sidebar width to accommodate all new icons
- fix: sonar lint issues
-

feat: download default zip project on first boot

---

src/extensions/default/Phoenix/main.js
src/extensions/default/Phoenix/unsupported-browser.html
src/phoenix/browserDetails.js
src/styles/images/opera-logo.svg

* Added code to detect chrome based opera

chore: add opera chromium to supported browsers

---

.github/workflows/prod-deploy.yml
README.md

- ci: update readme with deployment steps
- ci: adding prod push action

adding prod push action

---

src/utils/Resizer.js

Promote staging to prod

---

.github/workflows/dev-deploy.yml

dev.phcode.dev  ci deploy on pus to main

ci: main branch push will deploy to dev.phcode.dev instantly

---

src/brackets.config.dist.json
src/brackets.config.staging.json
src/config.json

fix: phoenix showing out of date notification

---

src/assets/phoenix-splash/index.html
src/assets/phoenix-splash/styles.css

modified css for button. 
added montserrat font

CSS changes

---

package-lock.json
package.json
src/assets/new-project/assets/js/phoenix.js
src/assets/new-project/code-editor-new-html-project.html
src/assets/new-project/code-editor-new-project-github.html
src/assets/new-project/code-editor-new-project-website.html
src/assets/new-project/code-editor-new-project.html
src/assets/new-project/code-editor.html
src/brackets.js
src/extensions/default/Phoenix/new-project.js
src/utils/EventManager.js
test/UnitTestSuite.js
test/spec/EventManager-test.js

1. Add Event manager to communicate with named events from anywhere within phoenix, and also from external iframes that hosts phoenix or is hosted by phoenix. Related unit tests.
2. Add close button functionality with the help of the new event manager infra.

feat: cancel btn on new project dialogue working, eventManager

---

package-lock.json
package.json

* Fixed root cause in lib and merging fix in.
* Observed when two Pheonix windows edits same project too causing live preview changes in one window to not update the other.

fix: cannot save file after phcode-fs lib migration

---

.gitignore
gulpfile.js/index.js
package-lock.json
package.json
src/extensions/default/Phoenix-live-preview/main.js
src/extensions/default/Phoenix-live-preview/markdown.html
src/extensions/default/Phoenix-live-preview/utils.js
src/thirdparty/licences/marked.markdown

feat: markdown live preview initial draft

---

src/assets/default-project/en/features.markdown
src/assets/default-project/en/index.html
src/assets/default-project/en/styles.css
src/assets/default-project/en/video.js
src/extensions/default/Phoenix-live-preview/utils.js

feat: welcome experience feature videos

---

README.md

We have done significant changes to the code base, so its more of a derivative work now.

Update copyright string

---

src/extensions/default/Phoenix/survey.js

address: https://github.com/phcode-dev/phoenix/issues/423

chore: increase user survey show time to 2 minutes

---

src/assets/default-project/en/Features.md
src/assets/default-project/en/Newly_added_features.md
src/assets/default-project/en/index.html

feat: add share and publish website feature video

---

.github/workflows/comment_pr.yml
.github/workflows/python/verify_cla_signature_pr.py
.github/workflows/verify_cla_signature_pr.yml

Add check that validates that the pull request raiser has signed the CLA and every commit in the pull request belongs to a user that has signed the CLA .
Solve issue task 2 in issue https://github.com/phcode-dev/contributor-license-agreement/issues/6#issue-1221770881

Add CLA checks

---

src/utils/Metrics.js
test/spec/Metrics-test.js

- chore: metrics utils and tests for analytics
These core utils brings in a unified light weight metrics logging and audit mechanism.
Currently sends event to both core and google analytics

metrics utils and tests for analytics

---

src/LiveDevelopment/LiveDevelopment.js
src/document/DocumentCommandHandlers.js
src/editor/CSSInlineEditor.js
src/editor/EditorStatusBar.js
src/extensions/default/HealthData/HealthDataManager.js
src/extensions/default/HealthData/HealthDataPreview.js
src/extensions/default/HealthData/SendToAnalytics.js
src/extensions/default/HealthData/main.js
src/extensions/default/JavaScriptQuickEdit/main.js
src/extensions/default/JavaScriptRefactoring/main.js
src/extensions/default/MDNDocs/InlineDocsViewer.js
src/extensions/default/MDNDocs/main.js
src/extensions/default/NoDistractions/main.js
src/languageTools/LanguageClientWrapper.js
src/main.js
src/preferences/PreferencesDialogs.js
src/search/FindBar.js
src/search/FindInFilesUI.js
src/search/FindUtils.js
src/search/SearchResultsView.js
src/utils/HealthLogger.js
src/utils/Metrics.js
test/UnitTestSuite.js
test/spec/Metrics-test.js

- refactor: misc
- refactor: moving to Metrics module from HealthLogger
- refactor: moving to Metrics module from HealthLogger
- refactor: findInFiles to Metrics module from HealthLogger
- refactor: noDistractions to Metrics module from HealthLogger
- refactor: init metrics for core and google analytics

refactor: moving to Metrics module from HealthLogger

---

src/extensions/default/HealthData/HealthDataPreview.js
src/utils/Metrics.js

We now keep track and show sums, counts and running averages for metric events raised

feat: improved health report preview for users

---

src/extensions/default/HealthData/HealthDataManager.js
src/extensions/default/HealthData/HealthDataPreview.js
src/extensions/default/HealthData/htmlContent/healthdata-preview-dialog.html
src/extensions/default/NavigationAndHistory/NavigationProvider.js
src/extensions/default/Phoenix-live-preview/main.js
src/extensions/default/Phoenix-live-preview/utils.js
src/extensions/default/Phoenix/serverSync.js
src/utils/Metrics.js

- chore: add metrics for ui buttons, live preview, sharing
- feat: add clear health data button in preview

Health data UI improvements and more metrics

---

.gitignore
README.md
SECURITY.md
package-lock.json
package.json
require.min.config.js
src/assets/new-project/assets/css/style.css
src/assets/new-project/assets/js/new-github-project.js
src/assets/new-project/assets/js/phoenix.js
src/assets/new-project/code-editor-new-project-github.html
src/assets/new-project/code-editor.html
src/brackets.js
src/config.json
src/extensions/default/Phoenix/new-project.js
src/nls/root/strings.js

- build: minimizer initial research using r.js
- feat: new github project workflow initial
- feat: new github project select folders and dialogues

new github project workflow UI and loc

---

src/assets/new-project/assets/js/code-editor.js
src/assets/new-project/assets/js/new-github-project.js
src/assets/new-project/assets/js/new-project-from-url.js
src/assets/new-project/code-editor.html
src/assets/new-project/new-project-from-url.html
src/extensions/default/Phoenix/new-project.js
src/nls/root/strings.js
src/phoenix/shell.js

- feat: new bootstrap blog new porject
- fix: check for write perms before project create

new bootstrap blog new porject

---

gulpfile.js/index.js
src/assets/new-project/assets/js/code-editor.js
src/assets/sample-projects/HTML5/index.html
src/assets/sample-projects/HTML5/script.js
src/assets/sample-projects/HTML5/styles.css
src/nls/root/strings.js

- feat: new HTML project
- fix: strings for default html project name

new HTML project

---

src/assets/new-project/assets/js/code-editor.js
src/assets/new-project/assets/js/new-project-from-url.js
src/assets/new-project/new-project-from-url.html
src/nls/root/strings.js

feat: new project license attributions in new project ui

---

docs/generatedApiDocs/utils/Metrics-API.md
src/extensions/default/Phoenix/new-project.js
src/index.html
src/thirdparty/jszip-utils-phoenix.js
test/SpecRunner.html

feat: new project download cancel option

---

src/assets/new-project/assets/css/style.css
src/assets/new-project/code-editor.html
src/styles/brackets_patterns_override.less

chore: moving recent projects to left and notify popup color changes

---

src/assets/new-project/assets/css/responsive.css
src/assets/new-project/assets/js/code-editor.js
src/nls/root/strings.js
src/phoenix/virtualServer/webserver.js
src/thirdparty/licences/credits.md

* Sometimes, the file served from virtual server gives 404 if the file is just saved. Virtual server will retry to load a file from disk if the first read fails as a mitigation. 
* Minor alignment fixes in small screens for new project 
* `HTML game/explore` project will not be listed in recent projects as it has a dedicated button in new projects section.
* License attributions

fix: more robust virtual server

---

docs/generatedApiDocs/widgets/NotificationUI-API.md
src/assets/new-project/assets/css/responsive.css
src/extensions/default/Phoenix/guided-tour.js
src/extensions/default/Phoenix/main.js
src/extensions/default/Phoenix/new-project.js
src/nls/root/strings.js
src/phoenix/virtualServer/webserver.js
src/widgets/NotificationUI.js

* Guided tour
* some doc changes and refactoring

feat: first launch guided expereince

---

src/brackets.config.dist.json
src/brackets.config.staging.json
src/config.json
src/index.html
src/utils/Metrics.js

evaluating mixpanel instead of Google Analytics
Tracking issue: https://github.com/phcode-dev/phoenix/issues/495

feat: evaluating mixpanel instead of Google Analytics

---

src/assets/new-project/assets/css/style.css
src/assets/new-project/assets/js/code-editor.js
src/assets/new-project/assets/js/new-project-from-url.js
src/assets/new-project/assets/js/phoenix.js
src/assets/new-project/new-project-from-url.html
src/nls/root/strings.js

feat: preview in new project dialogue

---

src/assets/new-project/assets/js/code-editor.js
src/assets/new-project/assets/js/new-project-from-url.js
src/assets/new-project/assets/js/new-project-more.js
src/assets/new-project/code-editor.html
src/assets/sample-projects/new-project-list.json
src/nls/root/strings.js

- feat: default project featured in new project section
- feat: streamline metrics

default project featured in new project section

---

src/filesystem/FileSystem.js
src/filesystem/impls/appshell/AppshellFileSystem.js
src/utils/Metrics.js
test/spec/FileSystem-test.js
test/spec/Metrics-test.js
test/spec/MockFileSystemImpl.js

- fix: metrics unit tests
- feat: api Filesystem.getFreePath and tests to get a path that dont exist

Filesystem.getFreePath and tests to get a path that dont exist

---

package-lock.json
package.json
src/command/Commands.js
src/command/DefaultMenus.js
src/extensions/default/Phoenix-live-preview/utils.js
src/filesystem/FileSystem.js
src/filesystem/impls/appshell/AppshellFileSystem.js
src/nls/root/strings.js
src/project/ProjectManager.js

feat: duplicate file and folder in files sidebar

---

.eslintrc.js
package.json
src/extensions/default/Phoenix-live-preview/utils.js
src/extensions/default/Phoenix/new-project.js
src/extensions/default/Phoenix/utils.js
src/phoenix/virtualServer/webserver.js
src/project/ProjectManager.js

- build: upgrade eslint
- fix: eslint new rule errors

fix eslint upgrade with new rule no-async-promise-executor

---

src/styles/brackets.less

feat: increase working files panel height

---

docs/Customize-Icons-For-File-And-Folder.md
src/styles/brackets.less
src/styles/brackets_variables.less
src/styles/jsTreeTheme.less

feat: ui tweaks, increase font size

---

src/search/FindInFilesUI.js

feat: search based on current selection as soon as find in files is opened

---

package-lock.json
package.json
src/extensions/default/Phoenix-live-preview/main.js
src/extensions/default/Phoenix/guided-tour.js
src/extensions/default/Phoenix/new-project.js
src/index.html
src/main.js
src/nls/root/strings.js
src/phoenix/shell.js
src/utils/Metrics.js
src/view/WorkspaceManager.js

* The notification is shown only after the user edits and saves the first HTML file
* fix bug where the debug mode is not set consistently across the system.

feat: popout live preview notification

---

.github/workflows/dev-deploy.yml
.gitignore
README.md

To run tests against these stacks go to the following url: 
* dev: https://dev.phcode.dev/distToDeploy/testing/test/SpecRunner.html
* staging: https://staging.phcode.dev/distToDeploy/testing/test/SpecRunner.html
* prod: https://phcode.dev/distToDeploy/testing/test/SpecRunner.html

feat: running tests in deployed stages

---

.github/workflows/dev-deploy.yml
README.md
src/extensions/default/DebugCommands/main.js

* Wiring debug menu to the correct test urls
* Fix test zip not being generated bug

fix: test urls

---

src/phoenix/virtualServer/config.js
src/phoenix/virtualServer/webserver.js

fix: pheonix src now loads in phoenix live preview

---

src/extensions/default/DarkTheme/main.less
src/extensions/default/DarkTheme/package.json
src/styles/brackets_codemirror_override.less
src/styles/brackets_theme_default.less
src/view/ThemeManager.js

* Improved syntax coloring for variables and globals in light and dark theme. See image below.
* Fix issues with theme reload after install

feat: default theme improve syntax coloring

---

src/extensions/default/DarkTheme/main.less
src/styles/brackets_theme_default.less

feat: color regular expressions

---

src/extensions/default/DarkTheme/main.less
src/search/worker/file-Indexing-Worker.js
src/styles/brackets_theme_default.less

feat: code coloring changes and minor error check

---

src/search/FindBar.js

removed unnecessary timers that was slowing down search

feat: instant seacrh inprove responsiveness

---

src/extensions/default/LightTheme/package.json
src/htmlContent/main-view.html
src/nls/root/strings.js
src/phoenix/init_vfs.js
src/styles/brackets.less
src/view/ThemeManager.js
src/view/ThemeSettings.js

- feat: auto detect theme and switch based on system dark mode
- fix: first lauch theme always default to light theme

system dark/light theme based theme selection

---

src/htmlContent/main-view.html
src/nls/root/strings.js
src/project/ProjectManager.js
src/project/ProjectModel.js
src/styles/brackets.less
test/spec/ProjectManager-test.js

- feat: project busy spinner initial draft
- feat: project busy spinnr tootlip and public api

project busy spinner, tootlip and public api

---

src/search/FindBar.js

feat: replace in files will also instant search now

---

src/extensions/default/HealthData/unittests.js
test/BootstrapReporterView.js
test/SpecRunner.html
test/SpecRunner.js

- feat: test spec runner printable report and copy
- fix: test spec runner layout issues
for generating test reports: https://docs.google.com/spreadsheets/d/16f_h6pOZbBAs2Im5yonQR6n9yNT6IqjppoYyr6ID9tY/edit#gid=0

test spec runner printable report and copy

---

src/brackets.js
src/htmlContent/problems-panel-table.html
src/htmlContent/problems-panel.html
src/htmlContent/search-results.html
src/language/CodeInspection.js
src/search/SearchResultsView.js
src/view/PanelView.js
src/view/PluginPanelView.js
src/view/WorkspaceManager.js
test/spec/MainViewManager-integ-test.js

- feat: escape key will toggle last shown/closed panel
- test: fix integration tests with new escape to close panel flow
- test: add integration test for escape key panel visibility toggle
* All unit and integration tests behaving as expected (no change in failures from previous run).
* manual sanity test

escape key will toggle last shown/closed panel

---

src/editor/Editor.js
src/editor/EditorHelper/ChangeHelper.js
src/editor/EditorHelper/EditorPreferences.js
src/editor/EditorHelper/ErrorPopupHelper.js
src/editor/EditorHelper/IndentHelper.js
src/editor/EditorHelper/InlineWidgetHelper.js
src/editor/EditorManager.js
src/editor/InlineWidget.js
src/view/WorkspaceManager.js
test/spec/EditorOptionHandlers-integ-test.js

- feat: highlight active line by default
- refactor: editor indent functions to IndentHelper
- refactor: editor preferences
- refactor: editor change handler
- refactor: editor ErrorPopupHelper.js
- refactor: update comments
- refactor: editor InlineWidgetHelper.js
- fix: integ test failure
- docs: update editor js docs
- fix: escape in inline editor not dismissing inline editor

editor fixes

---

src/assets/new-project/assets/css/style.css

fix:Theme the main scrollbar

---

package-lock.json
package.json
src/thirdparty/licences/prettier.markdown
src/thirdparty/licences/underscore.markdown

* Full test suite run, all unit and integration tests running as before.

build: upgrade all dependencies

---

test/spec/HTMLInstrumentation-test.js
test/spec/RemoteFunctions-test.js
test/spec/SpecRunnerUtils.js
test/spec/WorkerComm-test.js

* Unit test suite runs in local/dev stack
* suite runs in simulated staging stack.

fix: test suite wont run in staging and likely prod stack

---

gulpfile.js/translateStrings.js

We deduce if there are any manual translations done in `<locale>/strings.js` as users can explicitly provide
translations like these: https://github.com/phcode-dev/phoenix/pull/588 . We check the `<lang>/strings.js` with
`<lang>/lastTranslatedLocale.json` to determine translation overrides and update the `expertTranslations.json`
dictionary with the overrides.

feat: support user provided locale/strings.js translations

---

src/JSUtils/ScopeManager.js
src/JSUtils/worker/tern-main.js
src/JSUtils/worker/testTern.js
src/extensions/default/JavaScriptCodeHints/main.js

As we integrated latest tern.js tghere was some API changes. modified those.

fix: jump to definition working

---

src/extensions/default/JavaScriptRefactoring/RenameIdentifier.js

fix: disaable refactoring in single file if multi file refactor is detected

fix: disaable refactoring in single file if multi file refactor is detected

---

src/editor/Editor.js
src/extensions/default/JavaScriptRefactoring/RenameIdentifier.js
test/spec/Editor-test.js

Editor APIs to 
* getToken at current cursor or given cursor position
* getNextToken at current cursor or given cursor position
* getPreviousToken at current cursor or given cursor position
Tests

chore: get token from editor APIs

---

src/htmlContent/problems-panel-table.html
src/language/CodeInspection.js
src/styles/brackets.less
src/styles/brackets_core_ui_variables.less

- style: ui icons and color changes for problems panel
- refactor: codeInspector

style: ui icons and color changes for problems panel

---

src/extensions/default/Phoenix/new-project.js
src/extensions/default/Phoenix/utils.js
src/nls/root/strings.js

- feat: git project zip file extraction progress ux
- chore: batched file extraction to improve unzip performance

git project zip file extraction progress ux

---

src/editor/Editor.js
src/editor/EditorManager.js
src/extensions/default/QuickView/main.js
src/features/JumpToDefManager.js
src/styles/brackets.less

- fix: lint issues
- feat: ctrl-or cmd-click to jump to definition

ctrl-or cmd-click to jump to definition

---

src/JSUtils/ScopeManager.js
src/JSUtils/worker/tern-main.js
src/editor/Editor.js
src/extensions/default/DarkTheme/main.less
src/extensions/default/JavaScriptRefactoring/HighLightReferences.js
src/extensions/default/JavaScriptRefactoring/RenameIdentifier.js
src/extensions/default/JavaScriptRefactoring/main.js
src/extensions/default/JavaScriptRefactoring/unittests.js
src/styles/brackets.less

- feat: hilight references under cursor
- feat: hilight references integ tests
- refactor: highlight code into HighLightReferences.js

hilight references under cursor

---

src/extensions/default/Phoenix-prettier/main.js

Prettier is configured with default line width of 80. So prettier will try to set each line of code to below 80 chars in length.
In selections, we have to reduce line width according to the selection width offset(see gifs below). We only do this if padding takes less than 70% of total line width.

feat: prettier adjust line width based on selection offset

---

src/extensions/default/Phoenix-prettier/main.js

Use space and tabs settings from the editor to prettify

feat: use prettier space and tab config from editor

---

src/extensions/default/Phoenix-prettier/main.js
src/features/BeautificationManager.js

* disable beautify if a beautification provider is not registered to beautify a specific file type
* add svg,xml,jsx,hbs support

feat: disable beautify for unsupported langs. add svg,xml,jsx,hbs support

---

docs/generatedApiDocs/worker/ExtensionsWorker-API.md
docs/generatedApiDocs/worker/IndexingWorker-API.md
gulpfile.js/thirdparty-lib-copy.js
package-lock.json
package.json
src/extensions/default/Phoenix-prettier/main.js
src/extensions/default/Phoenix-prettier/worker/prettier-helper.js
src/thirdparty/licences/prettier-php.markdown
src/worker/ExtensionsWorker.js
src/worker/IndexingWorker.js

- feat: add PHP beautify support
- feat: lazy loading prettier plugins to improve memory and load bandwidth efficiency
- feat: very lazy loading prettier plugins just before use
- feat: add typescript beautification support
- docs: update worker docs

Beautify typescript, react, php & lazy load beautify plugins

---

docs/generatedApiDocs/features/BeautificationManager-API.md
package-lock.json
package.json
src/command/KeyBindingManager.js
src/editor/Editor.js
src/extensions/default/Phoenix-prettier/main.js
src/extensions/default/Phoenix-prettier/package.json
src/extensions/default/Phoenix-prettier/worker/prettier-helper.js
src/features/BeautificationManager.js
src/nls/root/strings.js
src/project/ProjectManager.js
test/spec/Editor-test.js

chore: prettier error messaging, ux, edge cases, remove some complex handling

---

docs/generatedApiDocs/features/BeautificationManager-API.md
src/extensions/default/Phoenix-prettier/main.js
src/features/BeautificationManager.js
src/nls/root/strings.js
src/preferences/PreferencesManager.js
test/UnitTestSuite.js
test/spec/BeautificationManager-test.js
test/spec/SpecRunnerUtils.js
test/spec/beautification-test-files/simple.js

- feat: support beautifyTextProvider API
- refactor: beautifyEditor
- unit tests for BeautificationManager

support beautifyTextProvider API & refactor beautifyEditor

---

src/editor/Editor.js
src/extensions/default/JavaScriptRefactoring/RenameIdentifier.js
src/extensions/default/JavaScriptRefactoring/unittests.js
src/styles/brackets.less

feat: border around renamed variable for better ux

---

src/extensions/default/HealthData/SendToAnalytics.js
src/extensions/default/Phoenix/html/create-project-dialogue.html
src/extensions/default/Phoenix/html/new-project-template.html
src/extensions/default/Phoenix/html/replace-keep-project-dialogue.html
src/extensions/default/Phoenix/html/replace-project-dialogue.html
src/extensions/default/Phoenix/main.js
src/nls/root/strings.js
src/utils/Metrics.js
src/virtual-server-main.js

- chore: storage quota and usage metrics of cache
- chore: storage quota persistance request to browser
- chore: storage quota persistance request after 1 minute of startup. this will give enough time for user to start working. once the permission is granted, it will be retained in further sessions. chrome will not show any user popup(uses heuristics to self determine if site is used sufficiently to grant persistence rights), but firefox will show user popup to confirm site permission.
- chore: cache expiration in 30 days and management
- chore: change string open recent to recent files to avoid confusion

cache management

---

src/phoenix/virtual-server-loader.js
src/phoenix/virtualServer/webserver.js
src/virtual-server-main.js

- chore: move external opaque urls to seperate cache
- chore: consistent cache updates using manifest files

chore: consistent cache updates using manifest files

---

src/LiveDevelopment/main.js
src/htmlContent/main-view.html
src/nls/root/strings.js
src/phoenix/virtualServer/webserver.js

- chore: live preview stability improvement and panel title
- feat: graduate from experimental build to alpha build

graduate from experimental build to alpha build

---

src/LiveDevelopment/MultiBrowserImpl/transports/ServiceWorkerTransport.js
src/extensions/default/DebugCommands/main.js
src/index.html
src/nls/root/strings.js
src/phoenix/virtual-server-loader.js
src/virtual-server-main.js

chore: adding log live preview option in debug menu

---

src/LiveDevelopment/BrowserScripts/RemoteFunctions.js

fix: live preview hilight at wrong places in default project

---

src/LiveDevelopment/BrowserScripts/RemoteFunctions.js

fix: live preview redraw highlights on resize

---

src/extensions/default/Phoenix/newly-added-features.js
src/nls/root/strings.js
src/phoenix/virtual-server-loader.js
src/virtual-server-main.js

feat: update pending reload dialog on startup

---

src/LiveDevelopment/BrowserScripts/DocumentObserver.js
src/phoenix/virtual-server-loader.js
test/UnitTestSuite.js
test/spec/ExtensionUtils-integ-test.js
test/spec/LiveDevelopmentMultiBrowser-test.js
test/spec/SpecRunnerUtils.js

- test: live preivew integ tests
- fix: integ test failure due to test url change

 live preivew integ tests

---

src/LiveDevelopment/BrowserScripts/RemoteFunctions.js
test/spec/LiveDevelopment-MultiBrowser-test-files/simple2.html
test/spec/LiveDevelopmentMultiBrowser-test.js

- test: live preview hilight integ tests
- test: live preview reverse hilight integ tests

live preview hilight and reverse highlight integ tests

---

src/extensions/default/Phoenix/new-project.js
src/nls/root/strings.js
src/project/ProjectManager.js

https://github.com/phcode-dev/phoenix/issues/130

fix: open folder menu not doing anything in firefox

---

src/LiveDevelopment/main.js
src/extensions/default/Phoenix-live-preview/images/sprites.svg
src/extensions/default/Phoenix-live-preview/live-preview.css
src/extensions/default/Phoenix-live-preview/main.js
src/extensions/default/Phoenix-live-preview/panel.html
src/nls/root/strings.js

feat: toggle live highlight feature

---

src/LiveDevelopment/BrowserScripts/DocumentObserver.js
src/extensions/default/Phoenix-live-preview/main.js
src/extensions/default/StaticServer/markdown.html
src/utils/Global.js
test/spec/LiveDevelopmentMultiBrowser-test.js

fixes: https://github.com/phcode-dev/phoenix/issues/792

fix: ctrl-s on live preview should not bring up browser save dialogue

---

src/extensions/default/Phoenix/newly-added-features.js
src/phoenix/virtual-server-loader.js

- Bugfix address issue- https://github.com/phcode-dev/phoenix/issues/802
no console errors ni phoenix

fix: too many update dialogues shown

---

src/extensions/default/Phoenix/serverSync.js
src/main.js
src/utils/AppInit.js
src/utils/Metrics.js
test/spec/Metrics-test.js

- fix: remove crypto.uuid api use to imporve compat with old browsers
- chore: add error metrics for unhandled exeptions and rejections
* all unit tests pass as before
* integ test pass as before.

chore: add error metrics for unhandled exeptions and rejections

---

src/logger.js

* Disable bugsnag on localhost as we don't want to log errors on development.
* added support for Tauri dev, staging, and prod environments.

chore: bugsnag logger tauri build support and disable bugsnag on localhost

---

src/LiveDevelopment/LiveDevMultiBrowser.js
src/LiveDevelopment/MultiBrowserImpl/transports/ServiceWorkerTransport.js
src/command/KeyBindingManager.js
src/command/Menus.js
src/extensions/default/DebugCommands/main.js
src/extensions/default/HealthData/HealthDataManager.js
src/logger.js
src/phoenix/virtual-server-loader.js
src/utils/ExtensionLoader.js
src/worker/ExtensionsWorker.js
src/worker/IndexingWorker.js
test/SpecRunner.js

- refactor: add global logger
- chore: leave breadcrumbs for better debugging from bugsnag

leave breadcrumbs for better debugging

---

src/phoenix/virtual-server-loader.js

dev.phcode.dev site update failed due to the logger not found

fix: dev site update failed due to logger not found

---

src/LiveDevelopment/BrowserScripts/ServiceWorkerTransportRemote.js
src/LiveDevelopment/BrowserScripts/pageLoaderWorker.js
src/LiveDevelopment/LiveDevMultiBrowser.js
src/LiveDevelopment/MultiBrowserImpl/protocol/LiveDevProtocol.js
src/LiveDevelopment/MultiBrowserImpl/transports/ServiceWorkerTransport.js
src/LiveDevelopment/main.js
src/LiveDevelopment/pageLoader.html
src/extensions/default/Phoenix-live-preview/main.js
src/extensions/default/Phoenix-live-preview/panel.html
src/extensions/default/StaticServer/StaticServer.js
src/phoenix/virtualServer/webserver.js
src/thirdparty/licences/jsZip.markdown
test/spec/LiveDevelopmentMultiBrowser-test.js

fixes: 
* https://github.com/phcode-dev/phoenix/issues/831
* https://github.com/phcode-dev/phoenix/issues/791

fix: debugger breakpoints in live preview popout tabs causes phoenix to be unresposive

---

src/phoenix/virtual-server-loader.js

fix: virtual server loader fails to load in dev.phcode.dev

---

src/phoenix/virtual-server-loader.js

* we made a change to call _forceClearCacheIfNeeded after app init, to prevent inconsistent load of js between live and cached versiosn.
* unfortunately, the call refresh cache after app init code is new and was not in the users cached code, and hence the force refresh part was never called if a cache already exists. 
* Current change made

fix: dev.phcode.dev fails to update to latest code

---

src/extensions/default/Phoenix-live-preview/main.js
src/extensions/default/Phoenix/newly-added-features.js

fixes: https://github.com/phcode-dev/phoenix/issues/802
Also fixes bugsnag issue

chore: remove update dialogue as we do transparent updates now

---

src/LiveDevelopment/MultiBrowserImpl/documents/LiveHTMLDocument.js
src/LiveDevelopment/MultiBrowserImpl/language/HTMLInstrumentation.js
src/LiveDevelopment/pageLoader.html
src/assets/phoenix-splash/no-preview.html
src/extensions/default/Phoenix-live-preview/main.js
src/extensions/default/Phoenix-live-preview/utils.js
src/index.html
src/logger.js
src/nls/root/strings.js
test/spec/LiveDevelopmentMultiBrowser-test.js

Fixes:
* https://github.com/phcode-dev/phoenix/issues/789
* https://github.com/phcode-dev/phoenix/issues/791
* selected bugsnag errors

fix: live preview render issues on beautify

---

src/extensibility/ExtensionDownloader.js
src/extensibility/ExtensionManager.js
src/extensibility/Package.js
test/SpecRunner.html
test/UnitTestSuite.js
test/spec/ExtensionInstallation-test.js
test/spec/InstallExtensionDialog-integ-test.js

- chore: change default sort for extensions by downloads
- test: enable install extension dialogue integ test
- test: extension installation tests
- add new tests
* full test suite run, new test and all existing tests working as expected.

Extension installation unit and integ tests

---

package.json
src/config.json

* Full test suite run, works as expected with no new failures introduced.
* Manually tested in chome, firefox and Edge

build: bump minor version to 3.1 added extension store support

---

src/command/KeyBindingManager.js

Emmet was registering enter key as its shortcut.
* if emment didn't handle the key as it didn't have any action to do, then we prevent default action.
* This prevention was initiated to prevent default browser action, say pressing `ctrl-e` would open google chrome address bar instead of quick edit if there was nothing to quick edit.
* Now changed the implementation so that we don't capture single keys line a-z, 0-9, and enter, page up etc..

fix: enter key not working in js files when emmet extension is installed

---

src/LiveDevelopment/BrowserScripts/LiveDevProtocolRemote.js
src/LiveDevelopment/LiveDevMultiBrowser.js
src/LiveDevelopment/MultiBrowserImpl/protocol/LiveDevProtocol.js
src/LiveDevelopment/main.js
src/devEnable.html
src/extensions/default/DebugCommands/main.js
src/extensions/default/HealthData/HealthDataNotification.js
src/extensions/default/Phoenix-live-preview/main.js
src/extensions/default/Phoenix/guided-tour.js
src/loggerSetup.js
src/nls/root/strings.js
src/utils/ExtensionInterface.js

- chore: first boot notification for popout live preview after click on live preview only
- chore: first boot guided tour and notification streamline

first boot guided tour and notification streamline

---

src/main.js

* metrics might not be available on app crash, but bugsnag will be

feat: crash reporting on app load fail itself

---

docs/generatedApiDocs/widgets/NotificationUI-API.md
src/htmlContent/main-view.html
src/styles/brackets.less
src/widgets/NotificationUI.js
src/widgets/html/toast-popup.html
test/SpecRunner.html
test/SpecRunner.js
test/UnitTestSuite.js
test/spec/NotificationUI-test.js

- feat: basic toast notification support
- feat: multiple toast notification support
Creates a new toast notification popup from given title and html message.
The message can either be a string or a jQuery object representing a DOM node that is *not* in the current DOM.
Type: [function][3]
*   `title` **[string][4]** The title for the notification.
*   `template` **([string][4] | [Element][5])** A string template or HTML Element to use as the dialog HTML.
*   `options` **{dismissOnClick, autoCloseTimeS}?** optional, supported*   options are:
*   `autoCloseTimeS` - Time in seconds after which the notification should be auto closed. Default is never.
*   `dismissOnClick` - when clicked, the notification is closed. Default is true(dismiss). (optional, default `{}`)
Creating a toast …

toast notification support

---

src/assets/new-project/assets/js/code-editor.js
src/assets/new-project/code-editor.html

feat: github stars on welcome screen

---

src/extensions/default/HealthData/HealthDataManager.js
src/extensions/default/Phoenix/guided-tour.js
src/nls/root/strings.js
src/preferences/PreferencesManager.js
src/utils/Metrics.js

- chore: add power user survey
- chore: add metrics for guided tours

add power user survey

---

src/styles/brackets.less

feat: panel resizer color change on hover

---

src/index.html

As we work on native builds and service worker load optimization in all platforms, including ios, in the next changes, the reload situation will be heavily optimized next.

chore: reset cache as this is a large change rolling out

---

src/extensibility/ExtensionManagerView.js
src/extensibility/ExtensionManagerViewModel.js
src/htmlContent/extension-manager-view-item.html
src/nls/root/strings.js
src/utils/Metrics.js
src/view/ThemeManager.js

- feat: theme switch within extension manager
- fix: unit test failure as 1 day passed since we prefixed r. with repeating users

Theme switch within extension manager

---

src/extensibility/ExtensionManagerDialog.js
src/htmlContent/extension-manager-dialog.html

feat: add cancel button in extension manager to cancel theme apply and extension modifications

---

src/htmlContent/extension-manager-dialog.html

refactor: change text of extension close button to done

---

src/extensibility/ExtensionManagerDialog.js
src/extensibility/ExtensionManagerView.js
src/extensibility/ExtensionManagerViewModel.js
src/htmlContent/extension-manager-dialog.html
src/htmlContent/extension-manager-view-item.html
src/nls/root/strings.js
src/styles/brackets_core_ui_variables.less
src/styles/brackets_patterns_override.less
src/view/ThemeManager.js

* red accents to remove buttons
* do not show any disabled buttons and show buttons based on context

feat: theme manager ux tweaks

---

src/view/ThemeManager.js

* All themes were loading into `extensions/user/theme_main.css` instead of `extensions/user/theme/main.css` resulting in invalid load on some themes, and improper cleaup on theme removal. fixed to copy to theme folder.
* default themes will now show up in the installed section to apply. can be removed, but it will be automatically reinstalled on reboot. was a bug, but looks like a feature, so not fixing.

fix: themes not being put into correct user extension folder

---

README.md

Bugsnag attribution for requesting open source license

Bugsnag attribution for requesting open source license

---

src/index.html

chore: reset cache in browser

---

src/extensions/default/Phoenix-live-preview/utils.js

fixes: https://github.com/phcode-dev/phoenix/issues/981

feat: xhtml live previews

---

.sonarcloud.properties
src/extensibility/registry_utils.js
src/index.html

* verified extensions will show verified URL instead of author-name
* Some sonar issues fixed.

chore: verified extensions will show verified url instead of author name

---

src/command/DefaultMenus.js
src/editor/EditorCommandHandlers.js

https://github.com/phcode-dev/phoenix/issues/60

feat: disable paste on firefox

---

src/index.html
src/styles/brackets_patterns_override.less

fixes layout issues with extension manager table contents:

fix: extension manager ui off

---

src/command/KeyBindingManager.js

fixes https://github.com/phcode-dev/phoenix/issues/1017
moved from deprecated `event.keyCode` based shortcut handling to `event.code` based code.

fix: option key shortcuts not working in mac

---

src/editor/Editor.js
src/editor/EditorHelper/EditorPreferences.js
test/spec/EditorCommandHandlers-test.js

fixes: https://github.com/phcode-dev/phoenix/issues/1026

feat: comments will now indent by default

---

docs/generatedApiDocs/widgets/NotificationUI-API.md
package-lock.json
package.json
playwright.config.js

Though its not erroring out now, tests get stuck and seem to do nothing. But at least it loads now.

fix: playwright tests not working in mac. 

---

src/extensions/default/Phoenix/main.js
test/SpecRunner.html
test/spec/ExtensionLoader-test.js
test/spec/KeyBindingManager-test.js
test/spec/LowLevelFileIO-test.js

Pending: to be enabled in GitHub actions

Fixes all unit tests in safari

---

src/command/KeyBindingManager.js
src/loggerSetup.js

Fixes unknown browser tag in bugsnag:

fix: logging safari browser in bugsnag

---

docs/generatedApiDocs/utils/EventManager-API.md
src/document/Document.js
src/document/DocumentManager.js
src/extensions/default/NavigationAndHistory/FileRecovery.js
src/extensions/default/NavigationAndHistory/html/recovery-template.html
src/extensions/default/NavigationAndHistory/main.js
src/file/FileUtils.js
src/filesystem/Directory.js
src/filesystem/FileSystem.js
src/filesystem/FileSystemEntry.js
src/nls/root/strings.js
src/project/ProjectManager.js
src/utils/EventManager.js
src/utils/NativeApp.js
test/spec/Document-test.js
test/spec/FileSystem-test.js

Addresses: https://github.com/phcode-dev/phoenix/issues/408
light theme
dark theme

Feat: document crash recovery and auto save

---

docs/generatedApiDocs/utils/EventManager-API.md
src/utils/EventManager.js
test/spec/EventManager-test.js

This function acts as an event handler for all 'message' events targeted at the window object.
This is useful if you have to send/receive messaged from an embedded cross-domain iframe inside phoenix.
https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage
Instead of directly overriding window.onmessage, extensions or other elements that need to
listen to these events should register their named eventHandler with `EventManager`.
*   `event` **[MessageEvent][6]** The 'message' event targeted at the window object. The event's
'data' property should have a 'handlerName' and `eventName` property that will be triggered in phcode.
```javascript
// We will try to communicate within an embedded iframe and an extension
// In your extension in phoenix, register a handlerName to process a …
```

feat: added EventManager APIs to handle window.onmessage events

---

src/extensions/default/Phoenix-live-preview/StaticServer.js
src/index.html
src/loggerSetup.js
src/utils/ExtensionLoader.js
src/utils/ExtensionUtils.js
src/utils/Metrics.js
test/SpecRunner.html

The initial draft for `tauri://` url support.
1. unit test window not opening in Tauri
2. live preview doesn't work
3. file system support is not done, virtual filesystem is in use.

feat: tauri default extensions loading

---

src/assets/new-project/assets/css/style.css
src/assets/new-project/code-editor.html
src/config.json
src/nls/root/strings-app.js

feat: unify product name: Phoenix Code

---

package-lock.json
src/extensions/default/DebugCommands/keyboard.json
src/extensions/default/DebugCommands/main.js
src/phoenix/shell.js
src/phoenix/tauriShell.js

1. https://github.com/phcode-dev/phoenix-desktop/issues/64
2. https://github.com/phcode-dev/phoenix-desktop/pull/76

feat: add show developer tools in debug menu for tauri

---

src/command/DefaultMenus.js
src/document/DocumentCommandHandlers.js
src/extensions/default/DebugCommands/main.js
src/nls/root/strings.js
src/phoenix/shell.js

In the browser, the menu item is not shown.

feat: open in os file explorer option in tauri

---

src/nls/tr/strings.js

[IMPORT_PROJECT" has been replaced with the correct translation.

[IMPORT_PROJECT" has been replaced with the correct translation.

---

src/phoenix/shell.js
test/spec/Tauri-platform-test.html
test/spec/Tauri-platform-test.js

Also introduces change that allows upto 30 tauri api capable windows to be opened

fix: file>new window working in tauri

---

.github/workflows/desktop-linux-test-pull.yml
.github/workflows/desktop-mac-test-pull.yml
.github/workflows/desktop-windows-test-pull.yml
.github/workflows/playwright-staging-prod.yml
package-lock.json
src-node/package.json

Raise node version to 20LTS fro 18LTS
1. Since we havebranch protection rules applied on staging and prod branch that requires a pull request to merge in changes, test will run on that pull request
2. Since the pull request itself will track the test action, we dont need to raise an issue anymore.

chore: upgrade node to 20LTSfrom 18LTS

---

src/assets/new-project/assets/js/new-project-more.js
src/extensibility/Package.js
src/extensions/default/HTMLCodeHints/HTMLJumpToDef.js
src/extensions/default/QuickView/ImagePreviewProvider.js
src/extensions/default/RemoteFileAdapter/main.js
src/filesystem/FileSystem.js
src/index.html
src/phoenix/shell.js
src/utils/ExtensionLoader.js
src/utils/ExtensionUtils.js
src/view/ThemeManager.js
test/SpecRunner.html

due to this:
https://github.com/phcode-dev/phoenix-desktop/pull/133

chore: rename phcode protcol to phtauri

---

src-node/index.js
src/document/DocumentCommandHandlers.js
src/extensions/default/DebugCommands/main.js
src/nls/root/strings.js
src/node-loader.js
src/phoenix/shell.js

This is a desktop build(tauri) only feature

feat: how to inspect node menu item and dialog

---

src/index.html
src/storage.js
src/utils/EventDispatcher.js
test/SpecRunner.html
test/UnitTestSuite.js
test/spec/Storage-integ-test.js
test/spec/Template-for-integ-test.js

This pull request introduces a unified storage API that seamlessly works in both web browsers and Tauri, our desktop application platform. In web browsers, the API utilizes local storage, providing a consistent and reliable key-value store for small configuration data with persistence guarantees and efficient read-write performance. It's important to note that this storage API is not suitable for storing large data, such as file content or debug-related information.
* Synchronous reads with in-memory caching for optimized performance.
* Read-after-write consistency within a single instance.
* Eventual consistency (within approximately 3 seconds) when used across multiple processes or tabs.
The motivation behind implementing this unified storage API is to address the limitations and …

feat: phoenix persistant storage browse impl

---

src/styles/brackets_scrollbars.less

| Before            | After             |
| ----------------- | ----------------- |
| ![image](https://github.com/phcode-dev/phoenix/assets/5336369/642587dd-3517-41f8-b03f-4b1ac22787b1)  |  ![image](https://github.com/phcode-dev/phoenix/assets/5336369/e05684d7-cc86-4162-8cbf-32d59a9ab2e8) |
| Before            | After             |
| ----------------- | ----------------- |
| ![image](https://github.com/phcode-dev/phoenix/assets/5336369/7bd81e56-bc59-4b78-8ea7-e79753ea86fa) | ![image](https://github.com/phcode-dev/phoenix/assets/5336369/b025de6e-56e1-488a-bd4f-da88d4659d94) |
| ![image](https://github.com/phcode-dev/phoenix/assets/5336369/8c4daa53-2ea2-42e0-a659-4e2bbf9a7c12) | ![image](https://github.com/phcode-dev/phoenix/assets/5336369/5dd2dbd0-5bc5-4a00-8d8e-81accf3ae6ef) |
| …

fix: mac scrollbar rendering

---

src/LiveDevelopment/MultiBrowserImpl/documents/LiveDocument.js
src/LiveDevelopment/MultiBrowserImpl/protocol/LiveDevProtocol.js
src/LiveDevelopment/main.js
src/brackets.js
src/document/DocumentCommandHandlers.js
src/document/DocumentManager.js
src/editor/EditorStatusBar.js
src/editor/MultiRangeInlineEditor.js
src/extensions/default/CodeFolding/Prefs.js
src/extensions/default/HealthData/HealthDataManager.js
src/extensions/default/NavigationAndHistory/main.js
src/extensions/default/RecentProjects/main.js
src/preferences/PreferencesImpl.js
src/preferences/PreferencesManager.js
src/preferences/StateManager.js
src/project/ProjectManager.js
src/search/FileFilters.js
src/storage.js
src/utils/Resizer.js
src/view/MainViewManager.js
test/TestPreferencesImpl.js
test/UnitTestSuite.js
test/spec/CSSInlineEdit-integ-test.js
test/spec/LiveDevelopmentMultiBrowser-test.js
test/spec/MultiRangeInlineEditor-test.js
test/spec/StateManager-test.js

This is needed for multi window preferences sync.

Move Preferences.StateManager to use PhStore

---

src/extensionsIntegrated/NavigationAndHistory/FileRecovery.js
src/extensionsIntegrated/NavigationAndHistory/html/recovery-template.html
src/nls/root/strings.js
test/spec/Extn-NavigationAndHistory-integ-tests.js

feat: add a discard option to file recovery

---

src/document/DocumentCommandHandlers.js
src/nls/root/strings.js
src/node-loader.js
src/utils/Metrics.js
src/widgets/Dialogs.js

feat: node crash recovery

---

src/search/FindBar.js
test/spec/FindReplace-integ-test.js

Fixes https://github.com/phcode-dev/phoenix/issues/1291

feat: up and down arrow keys to move to next and previous find result

---

src/command/KeyBindingManager.js
src/command/Menus.js
src/extensions/default/DebugCommands/main.js
src/styles/brackets_patterns_override.less

feat: keyboard up down arrow key nav in top menu

---

src/command/Menus.js

feat: main menu's submenu keyboard navigation

---

src/command/Commands.js
src/command/KeyboardOverlayMode.js
src/index.html
src/nls/root/strings.js
src/styles/brackets.less
src/styles/brackets_theme_default.less
test/UnitTestSuite.js
test/spec/Keyboard-nav-integ-test.js

double tap ctrl and press left or gith arrow to switch horizontal split panes or up and down arrow for vertical.

feat: keyboard nav with ctrl double click ontinued

---

src/assets/default-project/en/Newly_added_features.md
src/base-config/readme-keyboard.md
src/command/KeyBindingManager.js
src/command/Menus.js
test/spec/KeyBindingManager-test.js

Also fixes: https://github.com/phcode-dev/phoenix/issues/1345

feat: alt-key keyboard shortcuts in windows and mac

---

.eslintrc.js
src/LiveDevelopment/BrowserScripts/LivePreviewTransportRemote.js
src/LiveDevelopment/main.js
src/command/ChangeShortcutTemplate.html
src/command/KeyBindingManager.js
src/command/Menus.js
src/extensionsIntegrated/Phoenix-live-preview/main.js
src/main.js
src/nls/root/strings.js
src/styles/brackets_core_ui_variables.less
src/styles/brackets_patterns_override.less
src/widgets/Dialogs.js
test/SpecRunner.js
test/UnitTestSuite.js
test/spec/KeybindingManager-integ-test.js
test/spec/Keyboard-nav-integ-test.js

feat: shortcut assign dialog

---

src/assets/new-project/code-editor.html
src/config.json
src/strings.js

chore: add beta heading to app name

---

src/node-loader.js

This is a precursor to new linux binary distributions

chore: linux node load from exec dir for new distribution engg

---

src-node/utils.js
src/phoenix/shell.js
src/utils/NodeUtils.js

Remove deprecated linux appimage related apis

---

src/assets/new-project/assets/js/code-editor.js
src/assets/new-project/code-editor.html
src/nls/root/strings.js

feat: support us on open collective button

---

src/assets/default-project/en/Newly_added_features.md
src/assets/phoenix-splash/index.html
src/index.html
src/nls/root/strings.js
src/virtual-server-main.js

Tries to migrate existing cache to new cache with content  sha manifests
update fail recovery

build: web update cache consistant migration and load

---

src/command/DefaultMenus.js
src/extensions/default/DebugCommands/main.js
src/index.html
src/loggerSetup.js
src/nls/root/strings.js

* Removed unhandled rejection and exception handler in the browser so that bugsnag handles it properly.

build: cache and load main fn change index.html

---

gulpfile.js/index.js
src/assets/new-project/code-editor.html
src/assets/phoenix-splash/error.html
src/assets/phoenix-splash/index.html
src/assets/phoenix-splash/live-preview-error.html
src/assets/phoenix-splash/no-preview.html
src/robots.txt
src/search/FindBar.js
src/search/FindInFilesUI.js
src/sitemap-phcode.xml

Also closes find bar on project switch if its open as it retains old project context variables if not closed.

fix: simetimes, click on find in files search/filter history dowpdown item does nothing

---

src/brackets.js
src/editor/EditorManager.js
src/index.html
src/styles/brackets.less

chore: phcode.io on nav bar

---

src/manifest.json

fix: pwa installed name

---

src/command/KeyBindingManager.js
src/editor/Editor.js
src/extensions/default/QuickView/numberPreviewProvider.js
src/extensions/default/QuickView/unittests.js
src/features/QuickViewManager.js
src/utils/StringUtils.js
test/spec/Editor-test.js
test/spec/quickview-extn-test-files/test.html

Also enables number dials to "xhtml",  "less", "scss", "sass" , html inside "jsx" and "tsx" files.

chore: numeric dials over inline html number/styles

---

gulpfile.js/index.js
src/LiveDevelopment/BrowserScripts/LiveDevProtocolRemote.js
src/LiveDevelopment/BrowserScripts/RemoteFunctions.js
src/extensionsIntegrated/Phoenix-live-preview/main.js
src/extensionsIntegrated/Phoenix-live-preview/markdown.html
test/spec/LiveDevelopmentMultiBrowser-test.js

fix: it should be possible to select text in live preview and copy it

---

src-node/package-lock.json
src/document/Document.js
src/htmlContent/findreplace-bar.html
src/search/FindBar.js
src/search/FindReplace.js
src/search/QuickSearchField.js
src/styles/brackets.less
test/spec/FileFilters-integ-test.js
test/spec/FindInFiles-integ-test.js
test/spec/FindReplace-integ-test.js
test/spec/QuickOpen-integ-test.js

fixes https://github.com/phcode-dev/phoenix/issues/1209

Multi line find and replace

---

src/assets/new-project/code-editor.html
src/extensionsIntegrated/Phoenix/guided-tour.js
src/nls/root/strings.js

chore: add sponsor button to stars popup and new project window

---

src/extensionsIntegrated/Phoenix-live-preview/main.js
src/index.html
src/nls/root/strings.js
test/spec/LiveDevelopmentCustomServer-test.js
test/spec/LiveDevelopmentMultiBrowser-test.js

feat: custom server file banner for live preview

---

src/extensionsIntegrated/Phoenix/guided-tour.js
src/nls/root/strings.js

Also shortens new folder index html

chore: dynamic survey urls

---

package-lock.json
package.json
src/assets/default-project/en/styles.css
src/editor/EditorManager.js
src/extensions/default/CSSCodeHints/css-lint.js
src/extensions/default/CSSCodeHints/main.js
src/extensions/default/CSSCodeHints/worker/css-worker.js
src/extensions/default/QuickView/numberPreviewProvider.js
src/extensions/default/QuickView/unittests.js
src/features/QuickViewManager.js
src/language/CodeInspection.js
src/nls/root/strings.js
src/styles/brackets.less
src/styles/brackets_core_ui_variables.less
src/worker/language-service-worker-thread.js
test/UnitTestSuite.js
test/spec/CodeInspection-integ-test.js
test/spec/Editor-test.js
test/spec/Extn-CSSCodeHints-integ-test.js
test/spec/LanguageTools-test-files/css-language-service/css-lint-errors.css
test/spec/LanguageTools-test-files/css-language-service/less-lint-errors.less
test/spec/LanguageTools-test-files/css-language-service/less-lint-errors.scss

feat: css Linter Language service integration

---

.github/workflows/desktop-mac-test-pull.yml
src/phoenix/init_vfs.js

Address https://github.com/phcode-dev/phoenix/issues/1565

chore: better error messaging at app start crash

---

src/assets/default-project/en/Newly_added_features.md
src/extensions/default/Phoenix-prettier/worker/prettier-helper.js
src/htmlContent/about-dialog.html
src/nls/root/strings.js

chore: add release credits section in about box and update newly added features doc

---

src/assets/default-project/en/Newly_added_features.md
src/extensionsIntegrated/Phoenix-live-preview/BrowserStaticServer.js
src/extensionsIntegrated/Phoenix-live-preview/LivePreviewSettings.js
src/extensionsIntegrated/Phoenix-live-preview/NodeStaticServer.js
src/extensionsIntegrated/Phoenix-live-preview/main.js
src/htmlContent/about-dialog.html
src/nls/root/strings.js
test/spec/LiveDevelopmentCustomServer-test.js

chore: live preview outside of custom server root will display an error page

---

src/index.html
src/phoenix/shell.js
test/spec/Tauri-platform-test.js

Related to: https://github.com/phcode-dev/phoenix-desktop/issues/380

chore: add Phoenix.app.getProcessID() API and allow ws://12.0.0.1 urls

---

src/extensibility/ExtensionDownloader.js
src/extensionsIntegrated/Phoenix/guided-tour.js
src/utils/ExtensionLoader.js

Related to: https://github.com/phcode-dev/phoenix-desktop/issues/380

fix: node extensions gives uninstall error in windows

---

src/extensions/default/CSSCodeHints/main.js
src/extensions/default/HTMLCodeHints/main.js
test/spec/LiveDevelopment-MultiBrowser-test-files/inline-style.html
test/spec/LiveDevelopmentMultiBrowser-test.js

https://github.com/phcode-dev/phoenix/assets/5336369/9a2266de-0f92-40f9-9289-22e08b948eaa

feat: css class in html code hint live preview

---

src/extensionsIntegrated/Phoenix-live-preview/main.js
test/spec/LiveDevelopmentCustomServer-test.js

https://github.com/orgs/phcode-dev/discussions/1534

chore: custom server banner should show only if live preview panel open

---

src/assets/new-project/assets/js/code-editor.js
src/brackets.js
src/editor/Editor.js
src/extensionsIntegrated/Phoenix/default-projects.js
src/extensionsIntegrated/Phoenix/main.js
src/extensionsIntegrated/Phoenix/new-project.js
src/extensionsIntegrated/RecentProjects/main.js
src/phoenix/init_vfs.js
src/project/ProjectManager.js
src/project/ProjectModel.js
src/storage.js
src/utils/BuildInfoUtils.js
src/widgets/Dialogs.js
test/spec/ProjectModel-test.js

https://www.reddit.com/r/brackets/comments/1b7bihm/comment/l4rq3k6/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

chore: do not create projects in user documents dir if not needed

---

src-node/package-lock.json
src/editor/EditorOptionHandlers.js
src/extensions/default/Phoenix-prettier/main.js
src/extensions/default/Phoenix-prettier/unittests.js
test/SpecRunner.js
test/spec/prettier-test-files/js/test-pretty-ruler.js

Also will increase default line length to 120.
https://github.com/orgs/phcode-dev/discussions/1657

chore: editor ruler line length will be used for prettier default line length

---

src-node/utils.js
src/language/CodeInspection.js
src/nls/root/strings.js
src/utils/NodeUtils.js
test/SpecRunner.html
test/UnitTestReporter.js
test/spec/CodeInspection-fix-integ-test.js
test/spec/CodeInspection-integ-test.js
test/spec/Extn-CSSCodeHints-integ-test.js
tests-playwright/test-suite.spec.js

Also adds hyperlinks for problem in quick view when clicking will open the problem in problems panel

chore: ux improve for fix problem, fix wrench gutter and panel icon  @abose

---

src/.well-known/assetlinks.json

Configurations to support TWA app in chrome book

feat: adding support for chrome app

---

package-lock.json
package.json
src-node/package-lock.json
src-node/package.json

fixes: https://github.com/phcode-dev/phoenix-desktop/issues/438
* Verified fixed in window- browser and desktop app

fix: windows/mac rename files with different case

---

src-node/package-lock.json
src/extensions/default/HTMLCodeHints/integ-tests.js
src/extensionsIntegrated/Phoenix-live-preview/main.js
src/extensionsIntegrated/Phoenix-live-preview/utils.js
src/nls/root/strings.js
test/spec/Extn-HTMLCodeHints-Lint-integ-test.js
test/spec/LiveDevelopment-MultiBrowser-test-files/htmlOther/inlineStyle.shtml
test/spec/LiveDevelopmentCustomServer-test.js

fixes: https://github.com/phcode-dev/phoenix/issues/1726

feat: add support for shtml custom server live previews

---

src/extensionsIntegrated/Phoenix-live-preview/LivePreviewSettings.js
src/extensionsIntegrated/Phoenix-live-preview/main.js
test/spec/LiveDevelopmentCustomServer-test.js

Address: https://www.reddit.com/r/brackets/comments/1dnd4md/unable_to_get_custom_preview_working/

Custom live preview switch UX when no previewable file present. Eg. react

---

src/language/languages.json
src/nls/root/strings.js

Also reduce non-authed publish window to 3 days from 30 till we have login integrated

chore: add cjs and mjs support as javascript files

---

src/thirdparty/licences/credits.md

Fix: Typo in Credits.md

---

src/editor/CodeHintManager.js
src/nls/ru/expertTranslations.json

fix: https://github.com/orgs/phcode-dev/discussions/1809
Also fixes bad russian translation for word wrap - https://github.com/orgs/phcode-dev/discussions/1805

chore: tabs will insert codehint as every other behaves like that

---

build/api-docs-generator.js
build/config.json
build/jsdoc.json
src/utils/EventManager.js
src/widgets/NotificationUI.js

This script automates the generation of API documentation directly from the source code.
Once the script is run, the API docs are generated  inside build/api and ready for integration into the Docusaurus site.
The build directory has :- 
api-docs-generator.js (this is the main script file that we need to execute)
jsdoc.json (required to convert JS files into MDX. Script automatically handles it. No manual steps required)
config.json (also required to convert JS files into MDX. Script automatically handles it. No manual steps required)

Feat: Add script that generates API documentation automatically from Source Code.

---

build/api-docs-generator.js

Updated the import statement to include the module name using const.

refactor: update import statement to include module name

---

build/api-docs-generator.js

Fixed the file modified issue. where the API docs files were shown as modified by git even though there are no changes.
So, now API-Docs-Generator script first checks whether there are any differences, if yes then only it updates the docs.

fix: file modified issue

---

docs/API-Reference/features/TaskManager.md
src/features/TaskManager.js

The files in the `features` directory looks good for the most part!

docs: refine API docs for files in features dir

---

src/extensionsIntegrated/Phoenix/guided-tour.js

related to : https://github.com/phcode-dev/phoenix-desktop/pull/560

chore: remote config of survey show times

---

src/htmlContent/about-dialog.html

chore: update release credits to prepare for release

---

package-lock.json
package.json

The api-docs script was not working as the library was missing.
Add it to package and package-lock.json

Fix api-docs-generator script issue

---

src/styles/brackets.less
src/styles/brackets_core_ui_variables.less

chore: change table selected item colors in light and dark theme

---

src/command/KeyBindingManager.js
src/extensions/default/CodeFolding/main.js
src/extensionsIntegrated/NavigationAndHistory/keyboard.json
test/spec/KeyBindingManager-test.js

fixes https://github.com/orgs/phcode-dev/discussions/2019

fix: reserved keyboard shortcuts in mac used for nav back and forward

---

docs/API-Reference/command/Commands.md
src/command/Commands.js
src/command/DefaultMenus.js
src/config.json
src/help/HelpCommandHandlers.js
src/index.html
src/nls/root/strings.js

fix: https://github.com/orgs/phcode-dev/discussions/2117

feat: add report issue in help menu

---

src/extensions/default/Git/src/GutterManager.js
src/extensions/default/Git/styles/git-styles.less

feat: git scroll bar markers

---

src/extensionsIntegrated/TabBar/more-options.js
src/nls/root/strings.js
src/styles/brackets_core_ui_variables.less
src/styles/brackets_patterns_override.less

refactor: file tab strings for delete, rename, show in file tree
